/*
Albi Api - v5

This Api will be responsible for overall data distribution and authorization.

API version: v5
Contact: support@albiware.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NewContactModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewContactModel{}

// NewContactModel struct for NewContactModel
type NewContactModel struct {
	FirstName                    string          `json:"firstName"`
	LastName                     string          `json:"lastName"`
	ContactTypeIds               []int64         `json:"contactTypeIds"`
	ContactTypeIdentifiers       []string        `json:"contactTypeIdentifiers,omitempty"`
	OrganizationId               NullableInt64   `json:"organizationId,omitempty"`
	OrganizationIdentifier       NullableString  `json:"organizationIdentifier,omitempty"`
	UseOrganizationAddress       *bool           `json:"useOrganizationAddress,omitempty"`
	Address1                     NullableString  `json:"address1,omitempty"`
	Address2                     NullableString  `json:"address2,omitempty"`
	City                         NullableString  `json:"city,omitempty"`
	State                        NullableString  `json:"state,omitempty"`
	ZipCode                      NullableString  `json:"zipCode,omitempty"`
	Country                      NullableString  `json:"country,omitempty"`
	Latitude                     NullableFloat64 `json:"latitude,omitempty"`
	Longitude                    NullableFloat64 `json:"longitude,omitempty"`
	ParentOrganizationId         NullableInt64   `json:"parentOrganizationId,omitempty"`
	ParentOrganizationName       NullableString  `json:"parentOrganizationName,omitempty"`
	ParentOrganizationIdentifier NullableString  `json:"parentOrganizationIdentifier,omitempty"`
	SalespersonId                NullableInt64   `json:"salespersonId,omitempty"`
	SalespersonIdentifier        NullableString  `json:"salespersonIdentifier,omitempty"`
	SalespersonName              NullableString  `json:"salespersonName,omitempty"`
	ReferralSourceId             NullableInt64   `json:"referralSourceId,omitempty"`
	ReferralSourceIdentifier     NullableString  `json:"referralSourceIdentifier,omitempty"`
	RelationshipStatusId         NullableInt64   `json:"relationshipStatusId,omitempty"`
	RelationshipStatusIdentifier NullableString  `json:"relationshipStatusIdentifier,omitempty"`
	Email                        NullableString  `json:"email,omitempty"`
	PhoneNumber                  NullableString  `json:"phoneNumber,omitempty"`
	Sandbox                      NullableString  `json:"sandbox,omitempty"`
	JobTitle                     NullableString  `json:"jobTitle,omitempty"`
}

type _NewContactModel NewContactModel

// NewNewContactModel instantiates a new NewContactModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewContactModel(firstName string, lastName string, contactTypeIds []int64) *NewContactModel {
	this := NewContactModel{}
	this.FirstName = firstName
	this.LastName = lastName
	this.ContactTypeIds = contactTypeIds
	return &this
}

// NewNewContactModelWithDefaults instantiates a new NewContactModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewContactModelWithDefaults() *NewContactModel {
	this := NewContactModel{}
	return &this
}

// GetFirstName returns the FirstName field value
func (o *NewContactModel) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *NewContactModel) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *NewContactModel) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *NewContactModel) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *NewContactModel) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *NewContactModel) SetLastName(v string) {
	o.LastName = v
}

// GetContactTypeIds returns the ContactTypeIds field value
func (o *NewContactModel) GetContactTypeIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.ContactTypeIds
}

// GetContactTypeIdsOk returns a tuple with the ContactTypeIds field value
// and a boolean to check if the value has been set.
func (o *NewContactModel) GetContactTypeIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactTypeIds, true
}

// SetContactTypeIds sets field value
func (o *NewContactModel) SetContactTypeIds(v []int64) {
	o.ContactTypeIds = v
}

// GetContactTypeIdentifiers returns the ContactTypeIdentifiers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetContactTypeIdentifiers() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ContactTypeIdentifiers
}

// GetContactTypeIdentifiersOk returns a tuple with the ContactTypeIdentifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetContactTypeIdentifiersOk() ([]string, bool) {
	if o == nil || IsNil(o.ContactTypeIdentifiers) {
		return nil, false
	}
	return o.ContactTypeIdentifiers, true
}

// HasContactTypeIdentifiers returns a boolean if a field has been set.
func (o *NewContactModel) HasContactTypeIdentifiers() bool {
	if o != nil && !IsNil(o.ContactTypeIdentifiers) {
		return true
	}

	return false
}

// SetContactTypeIdentifiers gets a reference to the given []string and assigns it to the ContactTypeIdentifiers field.
func (o *NewContactModel) SetContactTypeIdentifiers(v []string) {
	o.ContactTypeIdentifiers = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetOrganizationId() int64 {
	if o == nil || IsNil(o.OrganizationId.Get()) {
		var ret int64
		return ret
	}
	return *o.OrganizationId.Get()
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetOrganizationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationId.Get(), o.OrganizationId.IsSet()
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *NewContactModel) HasOrganizationId() bool {
	if o != nil && o.OrganizationId.IsSet() {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given NullableInt64 and assigns it to the OrganizationId field.
func (o *NewContactModel) SetOrganizationId(v int64) {
	o.OrganizationId.Set(&v)
}

// SetOrganizationIdNil sets the value for OrganizationId to be an explicit nil
func (o *NewContactModel) SetOrganizationIdNil() {
	o.OrganizationId.Set(nil)
}

// UnsetOrganizationId ensures that no value is present for OrganizationId, not even an explicit nil
func (o *NewContactModel) UnsetOrganizationId() {
	o.OrganizationId.Unset()
}

// GetOrganizationIdentifier returns the OrganizationIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetOrganizationIdentifier() string {
	if o == nil || IsNil(o.OrganizationIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.OrganizationIdentifier.Get()
}

// GetOrganizationIdentifierOk returns a tuple with the OrganizationIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetOrganizationIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationIdentifier.Get(), o.OrganizationIdentifier.IsSet()
}

// HasOrganizationIdentifier returns a boolean if a field has been set.
func (o *NewContactModel) HasOrganizationIdentifier() bool {
	if o != nil && o.OrganizationIdentifier.IsSet() {
		return true
	}

	return false
}

// SetOrganizationIdentifier gets a reference to the given NullableString and assigns it to the OrganizationIdentifier field.
func (o *NewContactModel) SetOrganizationIdentifier(v string) {
	o.OrganizationIdentifier.Set(&v)
}

// SetOrganizationIdentifierNil sets the value for OrganizationIdentifier to be an explicit nil
func (o *NewContactModel) SetOrganizationIdentifierNil() {
	o.OrganizationIdentifier.Set(nil)
}

// UnsetOrganizationIdentifier ensures that no value is present for OrganizationIdentifier, not even an explicit nil
func (o *NewContactModel) UnsetOrganizationIdentifier() {
	o.OrganizationIdentifier.Unset()
}

// GetUseOrganizationAddress returns the UseOrganizationAddress field value if set, zero value otherwise.
func (o *NewContactModel) GetUseOrganizationAddress() bool {
	if o == nil || IsNil(o.UseOrganizationAddress) {
		var ret bool
		return ret
	}
	return *o.UseOrganizationAddress
}

// GetUseOrganizationAddressOk returns a tuple with the UseOrganizationAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewContactModel) GetUseOrganizationAddressOk() (*bool, bool) {
	if o == nil || IsNil(o.UseOrganizationAddress) {
		return nil, false
	}
	return o.UseOrganizationAddress, true
}

// HasUseOrganizationAddress returns a boolean if a field has been set.
func (o *NewContactModel) HasUseOrganizationAddress() bool {
	if o != nil && !IsNil(o.UseOrganizationAddress) {
		return true
	}

	return false
}

// SetUseOrganizationAddress gets a reference to the given bool and assigns it to the UseOrganizationAddress field.
func (o *NewContactModel) SetUseOrganizationAddress(v bool) {
	o.UseOrganizationAddress = &v
}

// GetAddress1 returns the Address1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetAddress1() string {
	if o == nil || IsNil(o.Address1.Get()) {
		var ret string
		return ret
	}
	return *o.Address1.Get()
}

// GetAddress1Ok returns a tuple with the Address1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetAddress1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address1.Get(), o.Address1.IsSet()
}

// HasAddress1 returns a boolean if a field has been set.
func (o *NewContactModel) HasAddress1() bool {
	if o != nil && o.Address1.IsSet() {
		return true
	}

	return false
}

// SetAddress1 gets a reference to the given NullableString and assigns it to the Address1 field.
func (o *NewContactModel) SetAddress1(v string) {
	o.Address1.Set(&v)
}

// SetAddress1Nil sets the value for Address1 to be an explicit nil
func (o *NewContactModel) SetAddress1Nil() {
	o.Address1.Set(nil)
}

// UnsetAddress1 ensures that no value is present for Address1, not even an explicit nil
func (o *NewContactModel) UnsetAddress1() {
	o.Address1.Unset()
}

// GetAddress2 returns the Address2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetAddress2() string {
	if o == nil || IsNil(o.Address2.Get()) {
		var ret string
		return ret
	}
	return *o.Address2.Get()
}

// GetAddress2Ok returns a tuple with the Address2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetAddress2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address2.Get(), o.Address2.IsSet()
}

// HasAddress2 returns a boolean if a field has been set.
func (o *NewContactModel) HasAddress2() bool {
	if o != nil && o.Address2.IsSet() {
		return true
	}

	return false
}

// SetAddress2 gets a reference to the given NullableString and assigns it to the Address2 field.
func (o *NewContactModel) SetAddress2(v string) {
	o.Address2.Set(&v)
}

// SetAddress2Nil sets the value for Address2 to be an explicit nil
func (o *NewContactModel) SetAddress2Nil() {
	o.Address2.Set(nil)
}

// UnsetAddress2 ensures that no value is present for Address2, not even an explicit nil
func (o *NewContactModel) UnsetAddress2() {
	o.Address2.Unset()
}

// GetCity returns the City field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetCity() string {
	if o == nil || IsNil(o.City.Get()) {
		var ret string
		return ret
	}
	return *o.City.Get()
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.City.Get(), o.City.IsSet()
}

// HasCity returns a boolean if a field has been set.
func (o *NewContactModel) HasCity() bool {
	if o != nil && o.City.IsSet() {
		return true
	}

	return false
}

// SetCity gets a reference to the given NullableString and assigns it to the City field.
func (o *NewContactModel) SetCity(v string) {
	o.City.Set(&v)
}

// SetCityNil sets the value for City to be an explicit nil
func (o *NewContactModel) SetCityNil() {
	o.City.Set(nil)
}

// UnsetCity ensures that no value is present for City, not even an explicit nil
func (o *NewContactModel) UnsetCity() {
	o.City.Unset()
}

// GetState returns the State field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetState() string {
	if o == nil || IsNil(o.State.Get()) {
		var ret string
		return ret
	}
	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// HasState returns a boolean if a field has been set.
func (o *NewContactModel) HasState() bool {
	if o != nil && o.State.IsSet() {
		return true
	}

	return false
}

// SetState gets a reference to the given NullableString and assigns it to the State field.
func (o *NewContactModel) SetState(v string) {
	o.State.Set(&v)
}

// SetStateNil sets the value for State to be an explicit nil
func (o *NewContactModel) SetStateNil() {
	o.State.Set(nil)
}

// UnsetState ensures that no value is present for State, not even an explicit nil
func (o *NewContactModel) UnsetState() {
	o.State.Unset()
}

// GetZipCode returns the ZipCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetZipCode() string {
	if o == nil || IsNil(o.ZipCode.Get()) {
		var ret string
		return ret
	}
	return *o.ZipCode.Get()
}

// GetZipCodeOk returns a tuple with the ZipCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetZipCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ZipCode.Get(), o.ZipCode.IsSet()
}

// HasZipCode returns a boolean if a field has been set.
func (o *NewContactModel) HasZipCode() bool {
	if o != nil && o.ZipCode.IsSet() {
		return true
	}

	return false
}

// SetZipCode gets a reference to the given NullableString and assigns it to the ZipCode field.
func (o *NewContactModel) SetZipCode(v string) {
	o.ZipCode.Set(&v)
}

// SetZipCodeNil sets the value for ZipCode to be an explicit nil
func (o *NewContactModel) SetZipCodeNil() {
	o.ZipCode.Set(nil)
}

// UnsetZipCode ensures that no value is present for ZipCode, not even an explicit nil
func (o *NewContactModel) UnsetZipCode() {
	o.ZipCode.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *NewContactModel) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *NewContactModel) SetCountry(v string) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *NewContactModel) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *NewContactModel) UnsetCountry() {
	o.Country.Unset()
}

// GetLatitude returns the Latitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude.Get()) {
		var ret float64
		return ret
	}
	return *o.Latitude.Get()
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Latitude.Get(), o.Latitude.IsSet()
}

// HasLatitude returns a boolean if a field has been set.
func (o *NewContactModel) HasLatitude() bool {
	if o != nil && o.Latitude.IsSet() {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given NullableFloat64 and assigns it to the Latitude field.
func (o *NewContactModel) SetLatitude(v float64) {
	o.Latitude.Set(&v)
}

// SetLatitudeNil sets the value for Latitude to be an explicit nil
func (o *NewContactModel) SetLatitudeNil() {
	o.Latitude.Set(nil)
}

// UnsetLatitude ensures that no value is present for Latitude, not even an explicit nil
func (o *NewContactModel) UnsetLatitude() {
	o.Latitude.Unset()
}

// GetLongitude returns the Longitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude.Get()) {
		var ret float64
		return ret
	}
	return *o.Longitude.Get()
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Longitude.Get(), o.Longitude.IsSet()
}

// HasLongitude returns a boolean if a field has been set.
func (o *NewContactModel) HasLongitude() bool {
	if o != nil && o.Longitude.IsSet() {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given NullableFloat64 and assigns it to the Longitude field.
func (o *NewContactModel) SetLongitude(v float64) {
	o.Longitude.Set(&v)
}

// SetLongitudeNil sets the value for Longitude to be an explicit nil
func (o *NewContactModel) SetLongitudeNil() {
	o.Longitude.Set(nil)
}

// UnsetLongitude ensures that no value is present for Longitude, not even an explicit nil
func (o *NewContactModel) UnsetLongitude() {
	o.Longitude.Unset()
}

// GetParentOrganizationId returns the ParentOrganizationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetParentOrganizationId() int64 {
	if o == nil || IsNil(o.ParentOrganizationId.Get()) {
		var ret int64
		return ret
	}
	return *o.ParentOrganizationId.Get()
}

// GetParentOrganizationIdOk returns a tuple with the ParentOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetParentOrganizationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentOrganizationId.Get(), o.ParentOrganizationId.IsSet()
}

// HasParentOrganizationId returns a boolean if a field has been set.
func (o *NewContactModel) HasParentOrganizationId() bool {
	if o != nil && o.ParentOrganizationId.IsSet() {
		return true
	}

	return false
}

// SetParentOrganizationId gets a reference to the given NullableInt64 and assigns it to the ParentOrganizationId field.
func (o *NewContactModel) SetParentOrganizationId(v int64) {
	o.ParentOrganizationId.Set(&v)
}

// SetParentOrganizationIdNil sets the value for ParentOrganizationId to be an explicit nil
func (o *NewContactModel) SetParentOrganizationIdNil() {
	o.ParentOrganizationId.Set(nil)
}

// UnsetParentOrganizationId ensures that no value is present for ParentOrganizationId, not even an explicit nil
func (o *NewContactModel) UnsetParentOrganizationId() {
	o.ParentOrganizationId.Unset()
}

// GetParentOrganizationName returns the ParentOrganizationName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetParentOrganizationName() string {
	if o == nil || IsNil(o.ParentOrganizationName.Get()) {
		var ret string
		return ret
	}
	return *o.ParentOrganizationName.Get()
}

// GetParentOrganizationNameOk returns a tuple with the ParentOrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetParentOrganizationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentOrganizationName.Get(), o.ParentOrganizationName.IsSet()
}

// HasParentOrganizationName returns a boolean if a field has been set.
func (o *NewContactModel) HasParentOrganizationName() bool {
	if o != nil && o.ParentOrganizationName.IsSet() {
		return true
	}

	return false
}

// SetParentOrganizationName gets a reference to the given NullableString and assigns it to the ParentOrganizationName field.
func (o *NewContactModel) SetParentOrganizationName(v string) {
	o.ParentOrganizationName.Set(&v)
}

// SetParentOrganizationNameNil sets the value for ParentOrganizationName to be an explicit nil
func (o *NewContactModel) SetParentOrganizationNameNil() {
	o.ParentOrganizationName.Set(nil)
}

// UnsetParentOrganizationName ensures that no value is present for ParentOrganizationName, not even an explicit nil
func (o *NewContactModel) UnsetParentOrganizationName() {
	o.ParentOrganizationName.Unset()
}

// GetParentOrganizationIdentifier returns the ParentOrganizationIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetParentOrganizationIdentifier() string {
	if o == nil || IsNil(o.ParentOrganizationIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.ParentOrganizationIdentifier.Get()
}

// GetParentOrganizationIdentifierOk returns a tuple with the ParentOrganizationIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetParentOrganizationIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentOrganizationIdentifier.Get(), o.ParentOrganizationIdentifier.IsSet()
}

// HasParentOrganizationIdentifier returns a boolean if a field has been set.
func (o *NewContactModel) HasParentOrganizationIdentifier() bool {
	if o != nil && o.ParentOrganizationIdentifier.IsSet() {
		return true
	}

	return false
}

// SetParentOrganizationIdentifier gets a reference to the given NullableString and assigns it to the ParentOrganizationIdentifier field.
func (o *NewContactModel) SetParentOrganizationIdentifier(v string) {
	o.ParentOrganizationIdentifier.Set(&v)
}

// SetParentOrganizationIdentifierNil sets the value for ParentOrganizationIdentifier to be an explicit nil
func (o *NewContactModel) SetParentOrganizationIdentifierNil() {
	o.ParentOrganizationIdentifier.Set(nil)
}

// UnsetParentOrganizationIdentifier ensures that no value is present for ParentOrganizationIdentifier, not even an explicit nil
func (o *NewContactModel) UnsetParentOrganizationIdentifier() {
	o.ParentOrganizationIdentifier.Unset()
}

// GetSalespersonId returns the SalespersonId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetSalespersonId() int64 {
	if o == nil || IsNil(o.SalespersonId.Get()) {
		var ret int64
		return ret
	}
	return *o.SalespersonId.Get()
}

// GetSalespersonIdOk returns a tuple with the SalespersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetSalespersonIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.SalespersonId.Get(), o.SalespersonId.IsSet()
}

// HasSalespersonId returns a boolean if a field has been set.
func (o *NewContactModel) HasSalespersonId() bool {
	if o != nil && o.SalespersonId.IsSet() {
		return true
	}

	return false
}

// SetSalespersonId gets a reference to the given NullableInt64 and assigns it to the SalespersonId field.
func (o *NewContactModel) SetSalespersonId(v int64) {
	o.SalespersonId.Set(&v)
}

// SetSalespersonIdNil sets the value for SalespersonId to be an explicit nil
func (o *NewContactModel) SetSalespersonIdNil() {
	o.SalespersonId.Set(nil)
}

// UnsetSalespersonId ensures that no value is present for SalespersonId, not even an explicit nil
func (o *NewContactModel) UnsetSalespersonId() {
	o.SalespersonId.Unset()
}

// GetSalespersonIdentifier returns the SalespersonIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetSalespersonIdentifier() string {
	if o == nil || IsNil(o.SalespersonIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.SalespersonIdentifier.Get()
}

// GetSalespersonIdentifierOk returns a tuple with the SalespersonIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetSalespersonIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SalespersonIdentifier.Get(), o.SalespersonIdentifier.IsSet()
}

// HasSalespersonIdentifier returns a boolean if a field has been set.
func (o *NewContactModel) HasSalespersonIdentifier() bool {
	if o != nil && o.SalespersonIdentifier.IsSet() {
		return true
	}

	return false
}

// SetSalespersonIdentifier gets a reference to the given NullableString and assigns it to the SalespersonIdentifier field.
func (o *NewContactModel) SetSalespersonIdentifier(v string) {
	o.SalespersonIdentifier.Set(&v)
}

// SetSalespersonIdentifierNil sets the value for SalespersonIdentifier to be an explicit nil
func (o *NewContactModel) SetSalespersonIdentifierNil() {
	o.SalespersonIdentifier.Set(nil)
}

// UnsetSalespersonIdentifier ensures that no value is present for SalespersonIdentifier, not even an explicit nil
func (o *NewContactModel) UnsetSalespersonIdentifier() {
	o.SalespersonIdentifier.Unset()
}

// GetSalespersonName returns the SalespersonName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetSalespersonName() string {
	if o == nil || IsNil(o.SalespersonName.Get()) {
		var ret string
		return ret
	}
	return *o.SalespersonName.Get()
}

// GetSalespersonNameOk returns a tuple with the SalespersonName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetSalespersonNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SalespersonName.Get(), o.SalespersonName.IsSet()
}

// HasSalespersonName returns a boolean if a field has been set.
func (o *NewContactModel) HasSalespersonName() bool {
	if o != nil && o.SalespersonName.IsSet() {
		return true
	}

	return false
}

// SetSalespersonName gets a reference to the given NullableString and assigns it to the SalespersonName field.
func (o *NewContactModel) SetSalespersonName(v string) {
	o.SalespersonName.Set(&v)
}

// SetSalespersonNameNil sets the value for SalespersonName to be an explicit nil
func (o *NewContactModel) SetSalespersonNameNil() {
	o.SalespersonName.Set(nil)
}

// UnsetSalespersonName ensures that no value is present for SalespersonName, not even an explicit nil
func (o *NewContactModel) UnsetSalespersonName() {
	o.SalespersonName.Unset()
}

// GetReferralSourceId returns the ReferralSourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetReferralSourceId() int64 {
	if o == nil || IsNil(o.ReferralSourceId.Get()) {
		var ret int64
		return ret
	}
	return *o.ReferralSourceId.Get()
}

// GetReferralSourceIdOk returns a tuple with the ReferralSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetReferralSourceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferralSourceId.Get(), o.ReferralSourceId.IsSet()
}

// HasReferralSourceId returns a boolean if a field has been set.
func (o *NewContactModel) HasReferralSourceId() bool {
	if o != nil && o.ReferralSourceId.IsSet() {
		return true
	}

	return false
}

// SetReferralSourceId gets a reference to the given NullableInt64 and assigns it to the ReferralSourceId field.
func (o *NewContactModel) SetReferralSourceId(v int64) {
	o.ReferralSourceId.Set(&v)
}

// SetReferralSourceIdNil sets the value for ReferralSourceId to be an explicit nil
func (o *NewContactModel) SetReferralSourceIdNil() {
	o.ReferralSourceId.Set(nil)
}

// UnsetReferralSourceId ensures that no value is present for ReferralSourceId, not even an explicit nil
func (o *NewContactModel) UnsetReferralSourceId() {
	o.ReferralSourceId.Unset()
}

// GetReferralSourceIdentifier returns the ReferralSourceIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetReferralSourceIdentifier() string {
	if o == nil || IsNil(o.ReferralSourceIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.ReferralSourceIdentifier.Get()
}

// GetReferralSourceIdentifierOk returns a tuple with the ReferralSourceIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetReferralSourceIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferralSourceIdentifier.Get(), o.ReferralSourceIdentifier.IsSet()
}

// HasReferralSourceIdentifier returns a boolean if a field has been set.
func (o *NewContactModel) HasReferralSourceIdentifier() bool {
	if o != nil && o.ReferralSourceIdentifier.IsSet() {
		return true
	}

	return false
}

// SetReferralSourceIdentifier gets a reference to the given NullableString and assigns it to the ReferralSourceIdentifier field.
func (o *NewContactModel) SetReferralSourceIdentifier(v string) {
	o.ReferralSourceIdentifier.Set(&v)
}

// SetReferralSourceIdentifierNil sets the value for ReferralSourceIdentifier to be an explicit nil
func (o *NewContactModel) SetReferralSourceIdentifierNil() {
	o.ReferralSourceIdentifier.Set(nil)
}

// UnsetReferralSourceIdentifier ensures that no value is present for ReferralSourceIdentifier, not even an explicit nil
func (o *NewContactModel) UnsetReferralSourceIdentifier() {
	o.ReferralSourceIdentifier.Unset()
}

// GetRelationshipStatusId returns the RelationshipStatusId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetRelationshipStatusId() int64 {
	if o == nil || IsNil(o.RelationshipStatusId.Get()) {
		var ret int64
		return ret
	}
	return *o.RelationshipStatusId.Get()
}

// GetRelationshipStatusIdOk returns a tuple with the RelationshipStatusId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetRelationshipStatusIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.RelationshipStatusId.Get(), o.RelationshipStatusId.IsSet()
}

// HasRelationshipStatusId returns a boolean if a field has been set.
func (o *NewContactModel) HasRelationshipStatusId() bool {
	if o != nil && o.RelationshipStatusId.IsSet() {
		return true
	}

	return false
}

// SetRelationshipStatusId gets a reference to the given NullableInt64 and assigns it to the RelationshipStatusId field.
func (o *NewContactModel) SetRelationshipStatusId(v int64) {
	o.RelationshipStatusId.Set(&v)
}

// SetRelationshipStatusIdNil sets the value for RelationshipStatusId to be an explicit nil
func (o *NewContactModel) SetRelationshipStatusIdNil() {
	o.RelationshipStatusId.Set(nil)
}

// UnsetRelationshipStatusId ensures that no value is present for RelationshipStatusId, not even an explicit nil
func (o *NewContactModel) UnsetRelationshipStatusId() {
	o.RelationshipStatusId.Unset()
}

// GetRelationshipStatusIdentifier returns the RelationshipStatusIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetRelationshipStatusIdentifier() string {
	if o == nil || IsNil(o.RelationshipStatusIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.RelationshipStatusIdentifier.Get()
}

// GetRelationshipStatusIdentifierOk returns a tuple with the RelationshipStatusIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetRelationshipStatusIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RelationshipStatusIdentifier.Get(), o.RelationshipStatusIdentifier.IsSet()
}

// HasRelationshipStatusIdentifier returns a boolean if a field has been set.
func (o *NewContactModel) HasRelationshipStatusIdentifier() bool {
	if o != nil && o.RelationshipStatusIdentifier.IsSet() {
		return true
	}

	return false
}

// SetRelationshipStatusIdentifier gets a reference to the given NullableString and assigns it to the RelationshipStatusIdentifier field.
func (o *NewContactModel) SetRelationshipStatusIdentifier(v string) {
	o.RelationshipStatusIdentifier.Set(&v)
}

// SetRelationshipStatusIdentifierNil sets the value for RelationshipStatusIdentifier to be an explicit nil
func (o *NewContactModel) SetRelationshipStatusIdentifierNil() {
	o.RelationshipStatusIdentifier.Set(nil)
}

// UnsetRelationshipStatusIdentifier ensures that no value is present for RelationshipStatusIdentifier, not even an explicit nil
func (o *NewContactModel) UnsetRelationshipStatusIdentifier() {
	o.RelationshipStatusIdentifier.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *NewContactModel) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *NewContactModel) SetEmail(v string) {
	o.Email.Set(&v)
}

// SetEmailNil sets the value for Email to be an explicit nil
func (o *NewContactModel) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *NewContactModel) UnsetEmail() {
	o.Email.Unset()
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneNumber.Get()
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumber.Get(), o.PhoneNumber.IsSet()
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *NewContactModel) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber.IsSet() {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given NullableString and assigns it to the PhoneNumber field.
func (o *NewContactModel) SetPhoneNumber(v string) {
	o.PhoneNumber.Set(&v)
}

// SetPhoneNumberNil sets the value for PhoneNumber to be an explicit nil
func (o *NewContactModel) SetPhoneNumberNil() {
	o.PhoneNumber.Set(nil)
}

// UnsetPhoneNumber ensures that no value is present for PhoneNumber, not even an explicit nil
func (o *NewContactModel) UnsetPhoneNumber() {
	o.PhoneNumber.Unset()
}

// GetSandbox returns the Sandbox field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetSandbox() string {
	if o == nil || IsNil(o.Sandbox.Get()) {
		var ret string
		return ret
	}
	return *o.Sandbox.Get()
}

// GetSandboxOk returns a tuple with the Sandbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetSandboxOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sandbox.Get(), o.Sandbox.IsSet()
}

// HasSandbox returns a boolean if a field has been set.
func (o *NewContactModel) HasSandbox() bool {
	if o != nil && o.Sandbox.IsSet() {
		return true
	}

	return false
}

// SetSandbox gets a reference to the given NullableString and assigns it to the Sandbox field.
func (o *NewContactModel) SetSandbox(v string) {
	o.Sandbox.Set(&v)
}

// SetSandboxNil sets the value for Sandbox to be an explicit nil
func (o *NewContactModel) SetSandboxNil() {
	o.Sandbox.Set(nil)
}

// UnsetSandbox ensures that no value is present for Sandbox, not even an explicit nil
func (o *NewContactModel) UnsetSandbox() {
	o.Sandbox.Unset()
}

// GetJobTitle returns the JobTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewContactModel) GetJobTitle() string {
	if o == nil || IsNil(o.JobTitle.Get()) {
		var ret string
		return ret
	}
	return *o.JobTitle.Get()
}

// GetJobTitleOk returns a tuple with the JobTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewContactModel) GetJobTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JobTitle.Get(), o.JobTitle.IsSet()
}

// HasJobTitle returns a boolean if a field has been set.
func (o *NewContactModel) HasJobTitle() bool {
	if o != nil && o.JobTitle.IsSet() {
		return true
	}

	return false
}

// SetJobTitle gets a reference to the given NullableString and assigns it to the JobTitle field.
func (o *NewContactModel) SetJobTitle(v string) {
	o.JobTitle.Set(&v)
}

// SetJobTitleNil sets the value for JobTitle to be an explicit nil
func (o *NewContactModel) SetJobTitleNil() {
	o.JobTitle.Set(nil)
}

// UnsetJobTitle ensures that no value is present for JobTitle, not even an explicit nil
func (o *NewContactModel) UnsetJobTitle() {
	o.JobTitle.Unset()
}

func (o NewContactModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewContactModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["firstName"] = o.FirstName
	toSerialize["lastName"] = o.LastName
	toSerialize["contactTypeIds"] = o.ContactTypeIds
	if o.ContactTypeIdentifiers != nil {
		toSerialize["contactTypeIdentifiers"] = o.ContactTypeIdentifiers
	}
	if o.OrganizationId.IsSet() {
		toSerialize["organizationId"] = o.OrganizationId.Get()
	}
	if o.OrganizationIdentifier.IsSet() {
		toSerialize["organizationIdentifier"] = o.OrganizationIdentifier.Get()
	}
	if !IsNil(o.UseOrganizationAddress) {
		toSerialize["useOrganizationAddress"] = o.UseOrganizationAddress
	}
	if o.Address1.IsSet() {
		toSerialize["address1"] = o.Address1.Get()
	}
	if o.Address2.IsSet() {
		toSerialize["address2"] = o.Address2.Get()
	}
	if o.City.IsSet() {
		toSerialize["city"] = o.City.Get()
	}
	if o.State.IsSet() {
		toSerialize["state"] = o.State.Get()
	}
	if o.ZipCode.IsSet() {
		toSerialize["zipCode"] = o.ZipCode.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.Latitude.IsSet() {
		toSerialize["latitude"] = o.Latitude.Get()
	}
	if o.Longitude.IsSet() {
		toSerialize["longitude"] = o.Longitude.Get()
	}
	if o.ParentOrganizationId.IsSet() {
		toSerialize["parentOrganizationId"] = o.ParentOrganizationId.Get()
	}
	if o.ParentOrganizationName.IsSet() {
		toSerialize["parentOrganizationName"] = o.ParentOrganizationName.Get()
	}
	if o.ParentOrganizationIdentifier.IsSet() {
		toSerialize["parentOrganizationIdentifier"] = o.ParentOrganizationIdentifier.Get()
	}
	if o.SalespersonId.IsSet() {
		toSerialize["salespersonId"] = o.SalespersonId.Get()
	}
	if o.SalespersonIdentifier.IsSet() {
		toSerialize["salespersonIdentifier"] = o.SalespersonIdentifier.Get()
	}
	if o.SalespersonName.IsSet() {
		toSerialize["salespersonName"] = o.SalespersonName.Get()
	}
	if o.ReferralSourceId.IsSet() {
		toSerialize["referralSourceId"] = o.ReferralSourceId.Get()
	}
	if o.ReferralSourceIdentifier.IsSet() {
		toSerialize["referralSourceIdentifier"] = o.ReferralSourceIdentifier.Get()
	}
	if o.RelationshipStatusId.IsSet() {
		toSerialize["relationshipStatusId"] = o.RelationshipStatusId.Get()
	}
	if o.RelationshipStatusIdentifier.IsSet() {
		toSerialize["relationshipStatusIdentifier"] = o.RelationshipStatusIdentifier.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.PhoneNumber.IsSet() {
		toSerialize["phoneNumber"] = o.PhoneNumber.Get()
	}
	if o.Sandbox.IsSet() {
		toSerialize["sandbox"] = o.Sandbox.Get()
	}
	if o.JobTitle.IsSet() {
		toSerialize["jobTitle"] = o.JobTitle.Get()
	}
	return toSerialize, nil
}

func (o *NewContactModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"firstName",
		"lastName",
		"contactTypeIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewContactModel := _NewContactModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewContactModel)

	if err != nil {
		return err
	}

	*o = NewContactModel(varNewContactModel)

	return err
}

type NullableNewContactModel struct {
	value *NewContactModel
	isSet bool
}

func (v NullableNewContactModel) Get() *NewContactModel {
	return v.value
}

func (v *NullableNewContactModel) Set(val *NewContactModel) {
	v.value = val
	v.isSet = true
}

func (v NullableNewContactModel) IsSet() bool {
	return v.isSet
}

func (v *NullableNewContactModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewContactModel(val *NewContactModel) *NullableNewContactModel {
	return &NullableNewContactModel{value: val, isSet: true}
}

func (v NullableNewContactModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewContactModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
