/*
Core API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
)

// checks if the GetProjectsStatusCopy200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectsStatusCopy200Response{}

// GetProjectsStatusCopy200Response struct for GetProjectsStatusCopy200Response
type GetProjectsStatusCopy200Response struct {
	Id                   *int32      `json:"id,omitempty"`
	ProjectId            *int32      `json:"projectId,omitempty"`
	Date                 *string     `json:"date,omitempty"`
	Value                *string     `json:"value,omitempty"`
	CreatedAt            *string     `json:"createdAt,omitempty"`
	UpdatedAt            interface{} `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetProjectsStatusCopy200Response GetProjectsStatusCopy200Response

// NewGetProjectsStatusCopy200Response instantiates a new GetProjectsStatusCopy200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectsStatusCopy200Response() *GetProjectsStatusCopy200Response {
	this := GetProjectsStatusCopy200Response{}
	var id int32 = 0
	this.Id = &id
	var projectId int32 = 0
	this.ProjectId = &projectId
	return &this
}

// NewGetProjectsStatusCopy200ResponseWithDefaults instantiates a new GetProjectsStatusCopy200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectsStatusCopy200ResponseWithDefaults() *GetProjectsStatusCopy200Response {
	this := GetProjectsStatusCopy200Response{}
	var id int32 = 0
	this.Id = &id
	var projectId int32 = 0
	this.ProjectId = &projectId
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetProjectsStatusCopy200Response) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectsStatusCopy200Response) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetProjectsStatusCopy200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetProjectsStatusCopy200Response) SetId(v int32) {
	o.Id = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GetProjectsStatusCopy200Response) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectsStatusCopy200Response) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GetProjectsStatusCopy200Response) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *GetProjectsStatusCopy200Response) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *GetProjectsStatusCopy200Response) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectsStatusCopy200Response) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *GetProjectsStatusCopy200Response) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *GetProjectsStatusCopy200Response) SetDate(v string) {
	o.Date = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GetProjectsStatusCopy200Response) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectsStatusCopy200Response) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GetProjectsStatusCopy200Response) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *GetProjectsStatusCopy200Response) SetValue(v string) {
	o.Value = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetProjectsStatusCopy200Response) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectsStatusCopy200Response) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetProjectsStatusCopy200Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetProjectsStatusCopy200Response) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectsStatusCopy200Response) GetUpdatedAt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectsStatusCopy200Response) GetUpdatedAtOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetProjectsStatusCopy200Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given interface{} and assigns it to the UpdatedAt field.
func (o *GetProjectsStatusCopy200Response) SetUpdatedAt(v interface{}) {
	o.UpdatedAt = v
}

func (o GetProjectsStatusCopy200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProjectsStatusCopy200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetProjectsStatusCopy200Response) UnmarshalJSON(data []byte) (err error) {
	varGetProjectsStatusCopy200Response := _GetProjectsStatusCopy200Response{}

	err = json.Unmarshal(data, &varGetProjectsStatusCopy200Response)

	if err != nil {
		return err
	}

	*o = GetProjectsStatusCopy200Response(varGetProjectsStatusCopy200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "projectId")
		delete(additionalProperties, "date")
		delete(additionalProperties, "value")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetProjectsStatusCopy200Response struct {
	value *GetProjectsStatusCopy200Response
	isSet bool
}

func (v NullableGetProjectsStatusCopy200Response) Get() *GetProjectsStatusCopy200Response {
	return v.value
}

func (v *NullableGetProjectsStatusCopy200Response) Set(val *GetProjectsStatusCopy200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectsStatusCopy200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectsStatusCopy200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectsStatusCopy200Response(val *GetProjectsStatusCopy200Response) *NullableGetProjectsStatusCopy200Response {
	return &NullableGetProjectsStatusCopy200Response{value: val, isSet: true}
}

func (v NullableGetProjectsStatusCopy200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectsStatusCopy200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
