/*
Albi Api - v5

This Api will be responsible for overall data distribution and authorization.

API version: v5
Contact: support@albiware.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
	"time"
)

// checks if the TimesheetFilters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimesheetFilters{}

// TimesheetFilters struct for TimesheetFilters
type TimesheetFilters struct {
	UserId            NullableInt64  `json:"userId,omitempty"`
	UserIdentifier    NullableString `json:"userIdentifier,omitempty"`
	ProjectId         NullableInt64  `json:"projectId,omitempty"`
	ProjectIdentifier NullableString `json:"projectIdentifier,omitempty"`
	StartDate         NullableTime   `json:"startDate,omitempty"`
	EndDate           NullableTime   `json:"endDate,omitempty"`
}

// NewTimesheetFilters instantiates a new TimesheetFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimesheetFilters() *TimesheetFilters {
	this := TimesheetFilters{}
	return &this
}

// NewTimesheetFiltersWithDefaults instantiates a new TimesheetFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimesheetFiltersWithDefaults() *TimesheetFilters {
	this := TimesheetFilters{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimesheetFilters) GetUserId() int64 {
	if o == nil || IsNil(o.UserId.Get()) {
		var ret int64
		return ret
	}
	return *o.UserId.Get()
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimesheetFilters) GetUserIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserId.Get(), o.UserId.IsSet()
}

// HasUserId returns a boolean if a field has been set.
func (o *TimesheetFilters) HasUserId() bool {
	if o != nil && o.UserId.IsSet() {
		return true
	}

	return false
}

// SetUserId gets a reference to the given NullableInt64 and assigns it to the UserId field.
func (o *TimesheetFilters) SetUserId(v int64) {
	o.UserId.Set(&v)
}

// SetUserIdNil sets the value for UserId to be an explicit nil
func (o *TimesheetFilters) SetUserIdNil() {
	o.UserId.Set(nil)
}

// UnsetUserId ensures that no value is present for UserId, not even an explicit nil
func (o *TimesheetFilters) UnsetUserId() {
	o.UserId.Unset()
}

// GetUserIdentifier returns the UserIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimesheetFilters) GetUserIdentifier() string {
	if o == nil || IsNil(o.UserIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.UserIdentifier.Get()
}

// GetUserIdentifierOk returns a tuple with the UserIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimesheetFilters) GetUserIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserIdentifier.Get(), o.UserIdentifier.IsSet()
}

// HasUserIdentifier returns a boolean if a field has been set.
func (o *TimesheetFilters) HasUserIdentifier() bool {
	if o != nil && o.UserIdentifier.IsSet() {
		return true
	}

	return false
}

// SetUserIdentifier gets a reference to the given NullableString and assigns it to the UserIdentifier field.
func (o *TimesheetFilters) SetUserIdentifier(v string) {
	o.UserIdentifier.Set(&v)
}

// SetUserIdentifierNil sets the value for UserIdentifier to be an explicit nil
func (o *TimesheetFilters) SetUserIdentifierNil() {
	o.UserIdentifier.Set(nil)
}

// UnsetUserIdentifier ensures that no value is present for UserIdentifier, not even an explicit nil
func (o *TimesheetFilters) UnsetUserIdentifier() {
	o.UserIdentifier.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimesheetFilters) GetProjectId() int64 {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret int64
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimesheetFilters) GetProjectIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *TimesheetFilters) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableInt64 and assigns it to the ProjectId field.
func (o *TimesheetFilters) SetProjectId(v int64) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *TimesheetFilters) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *TimesheetFilters) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetProjectIdentifier returns the ProjectIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimesheetFilters) GetProjectIdentifier() string {
	if o == nil || IsNil(o.ProjectIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectIdentifier.Get()
}

// GetProjectIdentifierOk returns a tuple with the ProjectIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimesheetFilters) GetProjectIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectIdentifier.Get(), o.ProjectIdentifier.IsSet()
}

// HasProjectIdentifier returns a boolean if a field has been set.
func (o *TimesheetFilters) HasProjectIdentifier() bool {
	if o != nil && o.ProjectIdentifier.IsSet() {
		return true
	}

	return false
}

// SetProjectIdentifier gets a reference to the given NullableString and assigns it to the ProjectIdentifier field.
func (o *TimesheetFilters) SetProjectIdentifier(v string) {
	o.ProjectIdentifier.Set(&v)
}

// SetProjectIdentifierNil sets the value for ProjectIdentifier to be an explicit nil
func (o *TimesheetFilters) SetProjectIdentifierNil() {
	o.ProjectIdentifier.Set(nil)
}

// UnsetProjectIdentifier ensures that no value is present for ProjectIdentifier, not even an explicit nil
func (o *TimesheetFilters) UnsetProjectIdentifier() {
	o.ProjectIdentifier.Unset()
}

// GetStartDate returns the StartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimesheetFilters) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimesheetFilters) GetStartDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// HasStartDate returns a boolean if a field has been set.
func (o *TimesheetFilters) HasStartDate() bool {
	if o != nil && o.StartDate.IsSet() {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given NullableTime and assigns it to the StartDate field.
func (o *TimesheetFilters) SetStartDate(v time.Time) {
	o.StartDate.Set(&v)
}

// SetStartDateNil sets the value for StartDate to be an explicit nil
func (o *TimesheetFilters) SetStartDateNil() {
	o.StartDate.Set(nil)
}

// UnsetStartDate ensures that no value is present for StartDate, not even an explicit nil
func (o *TimesheetFilters) UnsetStartDate() {
	o.StartDate.Unset()
}

// GetEndDate returns the EndDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimesheetFilters) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndDate.Get()
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimesheetFilters) GetEndDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDate.Get(), o.EndDate.IsSet()
}

// HasEndDate returns a boolean if a field has been set.
func (o *TimesheetFilters) HasEndDate() bool {
	if o != nil && o.EndDate.IsSet() {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given NullableTime and assigns it to the EndDate field.
func (o *TimesheetFilters) SetEndDate(v time.Time) {
	o.EndDate.Set(&v)
}

// SetEndDateNil sets the value for EndDate to be an explicit nil
func (o *TimesheetFilters) SetEndDateNil() {
	o.EndDate.Set(nil)
}

// UnsetEndDate ensures that no value is present for EndDate, not even an explicit nil
func (o *TimesheetFilters) UnsetEndDate() {
	o.EndDate.Unset()
}

func (o TimesheetFilters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimesheetFilters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.UserId.IsSet() {
		toSerialize["userId"] = o.UserId.Get()
	}
	if o.UserIdentifier.IsSet() {
		toSerialize["userIdentifier"] = o.UserIdentifier.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["projectId"] = o.ProjectId.Get()
	}
	if o.ProjectIdentifier.IsSet() {
		toSerialize["projectIdentifier"] = o.ProjectIdentifier.Get()
	}
	if o.StartDate.IsSet() {
		toSerialize["startDate"] = o.StartDate.Get()
	}
	if o.EndDate.IsSet() {
		toSerialize["endDate"] = o.EndDate.Get()
	}
	return toSerialize, nil
}

type NullableTimesheetFilters struct {
	value *TimesheetFilters
	isSet bool
}

func (v NullableTimesheetFilters) Get() *TimesheetFilters {
	return v.value
}

func (v *NullableTimesheetFilters) Set(val *TimesheetFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableTimesheetFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableTimesheetFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimesheetFilters(val *TimesheetFilters) *NullableTimesheetFilters {
	return &NullableTimesheetFilters{value: val, isSet: true}
}

func (v NullableTimesheetFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimesheetFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
