/*
Albi Api - v5

This Api will be responsible for overall data distribution and authorization.

API version: v5
Contact: support@albiware.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
)

// checks if the CreateProjectStaffModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProjectStaffModel{}

// CreateProjectStaffModel struct for CreateProjectStaffModel
type CreateProjectStaffModel struct {
	ProjectId              *int64         `json:"projectId,omitempty"`
	ProjectIdentifier      NullableString `json:"projectIdentifier,omitempty"`
	StaffId                *int64         `json:"staffId,omitempty"`
	StaffIdentifier        NullableString `json:"staffIdentifier,omitempty"`
	ProjectRoleIds         []int64        `json:"projectRoleIds,omitempty"`
	ProjectRoleIdentifiers []string       `json:"projectRoleIdentifiers,omitempty"`
	CurrentUserId          *int64         `json:"currentUserId,omitempty"`
	CurrentUserIdentifier  NullableString `json:"currentUserIdentifier,omitempty"`
}

// NewCreateProjectStaffModel instantiates a new CreateProjectStaffModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProjectStaffModel() *CreateProjectStaffModel {
	this := CreateProjectStaffModel{}
	return &this
}

// NewCreateProjectStaffModelWithDefaults instantiates a new CreateProjectStaffModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProjectStaffModelWithDefaults() *CreateProjectStaffModel {
	this := CreateProjectStaffModel{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *CreateProjectStaffModel) GetProjectId() int64 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int64
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectStaffModel) GetProjectIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *CreateProjectStaffModel) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int64 and assigns it to the ProjectId field.
func (o *CreateProjectStaffModel) SetProjectId(v int64) {
	o.ProjectId = &v
}

// GetProjectIdentifier returns the ProjectIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateProjectStaffModel) GetProjectIdentifier() string {
	if o == nil || IsNil(o.ProjectIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectIdentifier.Get()
}

// GetProjectIdentifierOk returns a tuple with the ProjectIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateProjectStaffModel) GetProjectIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectIdentifier.Get(), o.ProjectIdentifier.IsSet()
}

// HasProjectIdentifier returns a boolean if a field has been set.
func (o *CreateProjectStaffModel) HasProjectIdentifier() bool {
	if o != nil && o.ProjectIdentifier.IsSet() {
		return true
	}

	return false
}

// SetProjectIdentifier gets a reference to the given NullableString and assigns it to the ProjectIdentifier field.
func (o *CreateProjectStaffModel) SetProjectIdentifier(v string) {
	o.ProjectIdentifier.Set(&v)
}

// SetProjectIdentifierNil sets the value for ProjectIdentifier to be an explicit nil
func (o *CreateProjectStaffModel) SetProjectIdentifierNil() {
	o.ProjectIdentifier.Set(nil)
}

// UnsetProjectIdentifier ensures that no value is present for ProjectIdentifier, not even an explicit nil
func (o *CreateProjectStaffModel) UnsetProjectIdentifier() {
	o.ProjectIdentifier.Unset()
}

// GetStaffId returns the StaffId field value if set, zero value otherwise.
func (o *CreateProjectStaffModel) GetStaffId() int64 {
	if o == nil || IsNil(o.StaffId) {
		var ret int64
		return ret
	}
	return *o.StaffId
}

// GetStaffIdOk returns a tuple with the StaffId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectStaffModel) GetStaffIdOk() (*int64, bool) {
	if o == nil || IsNil(o.StaffId) {
		return nil, false
	}
	return o.StaffId, true
}

// HasStaffId returns a boolean if a field has been set.
func (o *CreateProjectStaffModel) HasStaffId() bool {
	if o != nil && !IsNil(o.StaffId) {
		return true
	}

	return false
}

// SetStaffId gets a reference to the given int64 and assigns it to the StaffId field.
func (o *CreateProjectStaffModel) SetStaffId(v int64) {
	o.StaffId = &v
}

// GetStaffIdentifier returns the StaffIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateProjectStaffModel) GetStaffIdentifier() string {
	if o == nil || IsNil(o.StaffIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.StaffIdentifier.Get()
}

// GetStaffIdentifierOk returns a tuple with the StaffIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateProjectStaffModel) GetStaffIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StaffIdentifier.Get(), o.StaffIdentifier.IsSet()
}

// HasStaffIdentifier returns a boolean if a field has been set.
func (o *CreateProjectStaffModel) HasStaffIdentifier() bool {
	if o != nil && o.StaffIdentifier.IsSet() {
		return true
	}

	return false
}

// SetStaffIdentifier gets a reference to the given NullableString and assigns it to the StaffIdentifier field.
func (o *CreateProjectStaffModel) SetStaffIdentifier(v string) {
	o.StaffIdentifier.Set(&v)
}

// SetStaffIdentifierNil sets the value for StaffIdentifier to be an explicit nil
func (o *CreateProjectStaffModel) SetStaffIdentifierNil() {
	o.StaffIdentifier.Set(nil)
}

// UnsetStaffIdentifier ensures that no value is present for StaffIdentifier, not even an explicit nil
func (o *CreateProjectStaffModel) UnsetStaffIdentifier() {
	o.StaffIdentifier.Unset()
}

// GetProjectRoleIds returns the ProjectRoleIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateProjectStaffModel) GetProjectRoleIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}
	return o.ProjectRoleIds
}

// GetProjectRoleIdsOk returns a tuple with the ProjectRoleIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateProjectStaffModel) GetProjectRoleIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.ProjectRoleIds) {
		return nil, false
	}
	return o.ProjectRoleIds, true
}

// HasProjectRoleIds returns a boolean if a field has been set.
func (o *CreateProjectStaffModel) HasProjectRoleIds() bool {
	if o != nil && !IsNil(o.ProjectRoleIds) {
		return true
	}

	return false
}

// SetProjectRoleIds gets a reference to the given []int64 and assigns it to the ProjectRoleIds field.
func (o *CreateProjectStaffModel) SetProjectRoleIds(v []int64) {
	o.ProjectRoleIds = v
}

// GetProjectRoleIdentifiers returns the ProjectRoleIdentifiers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateProjectStaffModel) GetProjectRoleIdentifiers() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ProjectRoleIdentifiers
}

// GetProjectRoleIdentifiersOk returns a tuple with the ProjectRoleIdentifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateProjectStaffModel) GetProjectRoleIdentifiersOk() ([]string, bool) {
	if o == nil || IsNil(o.ProjectRoleIdentifiers) {
		return nil, false
	}
	return o.ProjectRoleIdentifiers, true
}

// HasProjectRoleIdentifiers returns a boolean if a field has been set.
func (o *CreateProjectStaffModel) HasProjectRoleIdentifiers() bool {
	if o != nil && !IsNil(o.ProjectRoleIdentifiers) {
		return true
	}

	return false
}

// SetProjectRoleIdentifiers gets a reference to the given []string and assigns it to the ProjectRoleIdentifiers field.
func (o *CreateProjectStaffModel) SetProjectRoleIdentifiers(v []string) {
	o.ProjectRoleIdentifiers = v
}

// GetCurrentUserId returns the CurrentUserId field value if set, zero value otherwise.
func (o *CreateProjectStaffModel) GetCurrentUserId() int64 {
	if o == nil || IsNil(o.CurrentUserId) {
		var ret int64
		return ret
	}
	return *o.CurrentUserId
}

// GetCurrentUserIdOk returns a tuple with the CurrentUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectStaffModel) GetCurrentUserIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CurrentUserId) {
		return nil, false
	}
	return o.CurrentUserId, true
}

// HasCurrentUserId returns a boolean if a field has been set.
func (o *CreateProjectStaffModel) HasCurrentUserId() bool {
	if o != nil && !IsNil(o.CurrentUserId) {
		return true
	}

	return false
}

// SetCurrentUserId gets a reference to the given int64 and assigns it to the CurrentUserId field.
func (o *CreateProjectStaffModel) SetCurrentUserId(v int64) {
	o.CurrentUserId = &v
}

// GetCurrentUserIdentifier returns the CurrentUserIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateProjectStaffModel) GetCurrentUserIdentifier() string {
	if o == nil || IsNil(o.CurrentUserIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.CurrentUserIdentifier.Get()
}

// GetCurrentUserIdentifierOk returns a tuple with the CurrentUserIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateProjectStaffModel) GetCurrentUserIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentUserIdentifier.Get(), o.CurrentUserIdentifier.IsSet()
}

// HasCurrentUserIdentifier returns a boolean if a field has been set.
func (o *CreateProjectStaffModel) HasCurrentUserIdentifier() bool {
	if o != nil && o.CurrentUserIdentifier.IsSet() {
		return true
	}

	return false
}

// SetCurrentUserIdentifier gets a reference to the given NullableString and assigns it to the CurrentUserIdentifier field.
func (o *CreateProjectStaffModel) SetCurrentUserIdentifier(v string) {
	o.CurrentUserIdentifier.Set(&v)
}

// SetCurrentUserIdentifierNil sets the value for CurrentUserIdentifier to be an explicit nil
func (o *CreateProjectStaffModel) SetCurrentUserIdentifierNil() {
	o.CurrentUserIdentifier.Set(nil)
}

// UnsetCurrentUserIdentifier ensures that no value is present for CurrentUserIdentifier, not even an explicit nil
func (o *CreateProjectStaffModel) UnsetCurrentUserIdentifier() {
	o.CurrentUserIdentifier.Unset()
}

func (o CreateProjectStaffModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProjectStaffModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	if o.ProjectIdentifier.IsSet() {
		toSerialize["projectIdentifier"] = o.ProjectIdentifier.Get()
	}
	if !IsNil(o.StaffId) {
		toSerialize["staffId"] = o.StaffId
	}
	if o.StaffIdentifier.IsSet() {
		toSerialize["staffIdentifier"] = o.StaffIdentifier.Get()
	}
	if o.ProjectRoleIds != nil {
		toSerialize["projectRoleIds"] = o.ProjectRoleIds
	}
	if o.ProjectRoleIdentifiers != nil {
		toSerialize["projectRoleIdentifiers"] = o.ProjectRoleIdentifiers
	}
	if !IsNil(o.CurrentUserId) {
		toSerialize["currentUserId"] = o.CurrentUserId
	}
	if o.CurrentUserIdentifier.IsSet() {
		toSerialize["currentUserIdentifier"] = o.CurrentUserIdentifier.Get()
	}
	return toSerialize, nil
}

type NullableCreateProjectStaffModel struct {
	value *CreateProjectStaffModel
	isSet bool
}

func (v NullableCreateProjectStaffModel) Get() *CreateProjectStaffModel {
	return v.value
}

func (v *NullableCreateProjectStaffModel) Set(val *CreateProjectStaffModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProjectStaffModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProjectStaffModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProjectStaffModel(val *CreateProjectStaffModel) *NullableCreateProjectStaffModel {
	return &NullableCreateProjectStaffModel{value: val, isSet: true}
}

func (v NullableCreateProjectStaffModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProjectStaffModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
