/*
Core API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
)

// checks if the RetrieveProject200ResponseLinkedProjectInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetrieveProject200ResponseLinkedProjectInner{}

// RetrieveProject200ResponseLinkedProjectInner struct for RetrieveProject200ResponseLinkedProjectInner
type RetrieveProject200ResponseLinkedProjectInner struct {
	Id                    *int32      `json:"id,omitempty"`
	ProjectName           *string     `json:"projectName,omitempty"`
	LinkedProjectId       *int32      `json:"linkedProjectId,omitempty"`
	LinkedProjectName     *string     `json:"linkedProjectName,omitempty"`
	Type                  *string     `json:"type,omitempty"`
	SubType               interface{} `json:"subType,omitempty"`
	InsurancePolicy       interface{} `json:"insurancePolicy,omitempty"`
	LossAdjusterReference interface{} `json:"lossAdjusterReference,omitempty"`
	Notes                 interface{} `json:"notes,omitempty"`
	AdditionalProperties  map[string]interface{}
}

type _RetrieveProject200ResponseLinkedProjectInner RetrieveProject200ResponseLinkedProjectInner

// NewRetrieveProject200ResponseLinkedProjectInner instantiates a new RetrieveProject200ResponseLinkedProjectInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetrieveProject200ResponseLinkedProjectInner() *RetrieveProject200ResponseLinkedProjectInner {
	this := RetrieveProject200ResponseLinkedProjectInner{}
	var id int32 = 0
	this.Id = &id
	var linkedProjectId int32 = 0
	this.LinkedProjectId = &linkedProjectId
	return &this
}

// NewRetrieveProject200ResponseLinkedProjectInnerWithDefaults instantiates a new RetrieveProject200ResponseLinkedProjectInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetrieveProject200ResponseLinkedProjectInnerWithDefaults() *RetrieveProject200ResponseLinkedProjectInner {
	this := RetrieveProject200ResponseLinkedProjectInner{}
	var id int32 = 0
	this.Id = &id
	var linkedProjectId int32 = 0
	this.LinkedProjectId = &linkedProjectId
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RetrieveProject200ResponseLinkedProjectInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *RetrieveProject200ResponseLinkedProjectInner) SetId(v int32) {
	o.Id = &v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *RetrieveProject200ResponseLinkedProjectInner) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *RetrieveProject200ResponseLinkedProjectInner) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetLinkedProjectId returns the LinkedProjectId field value if set, zero value otherwise.
func (o *RetrieveProject200ResponseLinkedProjectInner) GetLinkedProjectId() int32 {
	if o == nil || IsNil(o.LinkedProjectId) {
		var ret int32
		return ret
	}
	return *o.LinkedProjectId
}

// GetLinkedProjectIdOk returns a tuple with the LinkedProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) GetLinkedProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.LinkedProjectId) {
		return nil, false
	}
	return o.LinkedProjectId, true
}

// HasLinkedProjectId returns a boolean if a field has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) HasLinkedProjectId() bool {
	if o != nil && !IsNil(o.LinkedProjectId) {
		return true
	}

	return false
}

// SetLinkedProjectId gets a reference to the given int32 and assigns it to the LinkedProjectId field.
func (o *RetrieveProject200ResponseLinkedProjectInner) SetLinkedProjectId(v int32) {
	o.LinkedProjectId = &v
}

// GetLinkedProjectName returns the LinkedProjectName field value if set, zero value otherwise.
func (o *RetrieveProject200ResponseLinkedProjectInner) GetLinkedProjectName() string {
	if o == nil || IsNil(o.LinkedProjectName) {
		var ret string
		return ret
	}
	return *o.LinkedProjectName
}

// GetLinkedProjectNameOk returns a tuple with the LinkedProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) GetLinkedProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.LinkedProjectName) {
		return nil, false
	}
	return o.LinkedProjectName, true
}

// HasLinkedProjectName returns a boolean if a field has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) HasLinkedProjectName() bool {
	if o != nil && !IsNil(o.LinkedProjectName) {
		return true
	}

	return false
}

// SetLinkedProjectName gets a reference to the given string and assigns it to the LinkedProjectName field.
func (o *RetrieveProject200ResponseLinkedProjectInner) SetLinkedProjectName(v string) {
	o.LinkedProjectName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RetrieveProject200ResponseLinkedProjectInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RetrieveProject200ResponseLinkedProjectInner) SetType(v string) {
	o.Type = &v
}

// GetSubType returns the SubType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RetrieveProject200ResponseLinkedProjectInner) GetSubType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SubType
}

// GetSubTypeOk returns a tuple with the SubType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetrieveProject200ResponseLinkedProjectInner) GetSubTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SubType) {
		return nil, false
	}
	return &o.SubType, true
}

// HasSubType returns a boolean if a field has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) HasSubType() bool {
	if o != nil && !IsNil(o.SubType) {
		return true
	}

	return false
}

// SetSubType gets a reference to the given interface{} and assigns it to the SubType field.
func (o *RetrieveProject200ResponseLinkedProjectInner) SetSubType(v interface{}) {
	o.SubType = v
}

// GetInsurancePolicy returns the InsurancePolicy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RetrieveProject200ResponseLinkedProjectInner) GetInsurancePolicy() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.InsurancePolicy
}

// GetInsurancePolicyOk returns a tuple with the InsurancePolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetrieveProject200ResponseLinkedProjectInner) GetInsurancePolicyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.InsurancePolicy) {
		return nil, false
	}
	return &o.InsurancePolicy, true
}

// HasInsurancePolicy returns a boolean if a field has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) HasInsurancePolicy() bool {
	if o != nil && !IsNil(o.InsurancePolicy) {
		return true
	}

	return false
}

// SetInsurancePolicy gets a reference to the given interface{} and assigns it to the InsurancePolicy field.
func (o *RetrieveProject200ResponseLinkedProjectInner) SetInsurancePolicy(v interface{}) {
	o.InsurancePolicy = v
}

// GetLossAdjusterReference returns the LossAdjusterReference field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RetrieveProject200ResponseLinkedProjectInner) GetLossAdjusterReference() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LossAdjusterReference
}

// GetLossAdjusterReferenceOk returns a tuple with the LossAdjusterReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetrieveProject200ResponseLinkedProjectInner) GetLossAdjusterReferenceOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LossAdjusterReference) {
		return nil, false
	}
	return &o.LossAdjusterReference, true
}

// HasLossAdjusterReference returns a boolean if a field has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) HasLossAdjusterReference() bool {
	if o != nil && !IsNil(o.LossAdjusterReference) {
		return true
	}

	return false
}

// SetLossAdjusterReference gets a reference to the given interface{} and assigns it to the LossAdjusterReference field.
func (o *RetrieveProject200ResponseLinkedProjectInner) SetLossAdjusterReference(v interface{}) {
	o.LossAdjusterReference = v
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RetrieveProject200ResponseLinkedProjectInner) GetNotes() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetrieveProject200ResponseLinkedProjectInner) GetNotesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return &o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *RetrieveProject200ResponseLinkedProjectInner) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given interface{} and assigns it to the Notes field.
func (o *RetrieveProject200ResponseLinkedProjectInner) SetNotes(v interface{}) {
	o.Notes = v
}

func (o RetrieveProject200ResponseLinkedProjectInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetrieveProject200ResponseLinkedProjectInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProjectName) {
		toSerialize["projectName"] = o.ProjectName
	}
	if !IsNil(o.LinkedProjectId) {
		toSerialize["linkedProjectId"] = o.LinkedProjectId
	}
	if !IsNil(o.LinkedProjectName) {
		toSerialize["linkedProjectName"] = o.LinkedProjectName
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.SubType != nil {
		toSerialize["subType"] = o.SubType
	}
	if o.InsurancePolicy != nil {
		toSerialize["insurancePolicy"] = o.InsurancePolicy
	}
	if o.LossAdjusterReference != nil {
		toSerialize["lossAdjusterReference"] = o.LossAdjusterReference
	}
	if o.Notes != nil {
		toSerialize["notes"] = o.Notes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RetrieveProject200ResponseLinkedProjectInner) UnmarshalJSON(data []byte) (err error) {
	varRetrieveProject200ResponseLinkedProjectInner := _RetrieveProject200ResponseLinkedProjectInner{}

	err = json.Unmarshal(data, &varRetrieveProject200ResponseLinkedProjectInner)

	if err != nil {
		return err
	}

	*o = RetrieveProject200ResponseLinkedProjectInner(varRetrieveProject200ResponseLinkedProjectInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "projectName")
		delete(additionalProperties, "linkedProjectId")
		delete(additionalProperties, "linkedProjectName")
		delete(additionalProperties, "type")
		delete(additionalProperties, "subType")
		delete(additionalProperties, "insurancePolicy")
		delete(additionalProperties, "lossAdjusterReference")
		delete(additionalProperties, "notes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRetrieveProject200ResponseLinkedProjectInner struct {
	value *RetrieveProject200ResponseLinkedProjectInner
	isSet bool
}

func (v NullableRetrieveProject200ResponseLinkedProjectInner) Get() *RetrieveProject200ResponseLinkedProjectInner {
	return v.value
}

func (v *NullableRetrieveProject200ResponseLinkedProjectInner) Set(val *RetrieveProject200ResponseLinkedProjectInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRetrieveProject200ResponseLinkedProjectInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRetrieveProject200ResponseLinkedProjectInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetrieveProject200ResponseLinkedProjectInner(val *RetrieveProject200ResponseLinkedProjectInner) *NullableRetrieveProject200ResponseLinkedProjectInner {
	return &NullableRetrieveProject200ResponseLinkedProjectInner{value: val, isSet: true}
}

func (v NullableRetrieveProject200ResponseLinkedProjectInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetrieveProject200ResponseLinkedProjectInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
