/*
Albi Api - v5

This Api will be responsible for overall data distribution and authorization.

API version: v5
Contact: support@albiware.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
)

// checks if the MeetingEventStatusIcon type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeetingEventStatusIcon{}

// MeetingEventStatusIcon struct for MeetingEventStatusIcon
type MeetingEventStatusIcon struct {
	Css             NullableString `json:"css,omitempty"`
	BorderColor     NullableString `json:"borderColor,omitempty"`
	FontCode        NullableString `json:"fontCode,omitempty"`
	TextColor       NullableString `json:"textColor,omitempty"`
	BackgroundColor NullableString `json:"backgroundColor,omitempty"`
}

// NewMeetingEventStatusIcon instantiates a new MeetingEventStatusIcon object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeetingEventStatusIcon() *MeetingEventStatusIcon {
	this := MeetingEventStatusIcon{}
	return &this
}

// NewMeetingEventStatusIconWithDefaults instantiates a new MeetingEventStatusIcon object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeetingEventStatusIconWithDefaults() *MeetingEventStatusIcon {
	this := MeetingEventStatusIcon{}
	return &this
}

// GetCss returns the Css field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeetingEventStatusIcon) GetCss() string {
	if o == nil || IsNil(o.Css.Get()) {
		var ret string
		return ret
	}
	return *o.Css.Get()
}

// GetCssOk returns a tuple with the Css field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeetingEventStatusIcon) GetCssOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Css.Get(), o.Css.IsSet()
}

// HasCss returns a boolean if a field has been set.
func (o *MeetingEventStatusIcon) HasCss() bool {
	if o != nil && o.Css.IsSet() {
		return true
	}

	return false
}

// SetCss gets a reference to the given NullableString and assigns it to the Css field.
func (o *MeetingEventStatusIcon) SetCss(v string) {
	o.Css.Set(&v)
}

// SetCssNil sets the value for Css to be an explicit nil
func (o *MeetingEventStatusIcon) SetCssNil() {
	o.Css.Set(nil)
}

// UnsetCss ensures that no value is present for Css, not even an explicit nil
func (o *MeetingEventStatusIcon) UnsetCss() {
	o.Css.Unset()
}

// GetBorderColor returns the BorderColor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeetingEventStatusIcon) GetBorderColor() string {
	if o == nil || IsNil(o.BorderColor.Get()) {
		var ret string
		return ret
	}
	return *o.BorderColor.Get()
}

// GetBorderColorOk returns a tuple with the BorderColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeetingEventStatusIcon) GetBorderColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BorderColor.Get(), o.BorderColor.IsSet()
}

// HasBorderColor returns a boolean if a field has been set.
func (o *MeetingEventStatusIcon) HasBorderColor() bool {
	if o != nil && o.BorderColor.IsSet() {
		return true
	}

	return false
}

// SetBorderColor gets a reference to the given NullableString and assigns it to the BorderColor field.
func (o *MeetingEventStatusIcon) SetBorderColor(v string) {
	o.BorderColor.Set(&v)
}

// SetBorderColorNil sets the value for BorderColor to be an explicit nil
func (o *MeetingEventStatusIcon) SetBorderColorNil() {
	o.BorderColor.Set(nil)
}

// UnsetBorderColor ensures that no value is present for BorderColor, not even an explicit nil
func (o *MeetingEventStatusIcon) UnsetBorderColor() {
	o.BorderColor.Unset()
}

// GetFontCode returns the FontCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeetingEventStatusIcon) GetFontCode() string {
	if o == nil || IsNil(o.FontCode.Get()) {
		var ret string
		return ret
	}
	return *o.FontCode.Get()
}

// GetFontCodeOk returns a tuple with the FontCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeetingEventStatusIcon) GetFontCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FontCode.Get(), o.FontCode.IsSet()
}

// HasFontCode returns a boolean if a field has been set.
func (o *MeetingEventStatusIcon) HasFontCode() bool {
	if o != nil && o.FontCode.IsSet() {
		return true
	}

	return false
}

// SetFontCode gets a reference to the given NullableString and assigns it to the FontCode field.
func (o *MeetingEventStatusIcon) SetFontCode(v string) {
	o.FontCode.Set(&v)
}

// SetFontCodeNil sets the value for FontCode to be an explicit nil
func (o *MeetingEventStatusIcon) SetFontCodeNil() {
	o.FontCode.Set(nil)
}

// UnsetFontCode ensures that no value is present for FontCode, not even an explicit nil
func (o *MeetingEventStatusIcon) UnsetFontCode() {
	o.FontCode.Unset()
}

// GetTextColor returns the TextColor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeetingEventStatusIcon) GetTextColor() string {
	if o == nil || IsNil(o.TextColor.Get()) {
		var ret string
		return ret
	}
	return *o.TextColor.Get()
}

// GetTextColorOk returns a tuple with the TextColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeetingEventStatusIcon) GetTextColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TextColor.Get(), o.TextColor.IsSet()
}

// HasTextColor returns a boolean if a field has been set.
func (o *MeetingEventStatusIcon) HasTextColor() bool {
	if o != nil && o.TextColor.IsSet() {
		return true
	}

	return false
}

// SetTextColor gets a reference to the given NullableString and assigns it to the TextColor field.
func (o *MeetingEventStatusIcon) SetTextColor(v string) {
	o.TextColor.Set(&v)
}

// SetTextColorNil sets the value for TextColor to be an explicit nil
func (o *MeetingEventStatusIcon) SetTextColorNil() {
	o.TextColor.Set(nil)
}

// UnsetTextColor ensures that no value is present for TextColor, not even an explicit nil
func (o *MeetingEventStatusIcon) UnsetTextColor() {
	o.TextColor.Unset()
}

// GetBackgroundColor returns the BackgroundColor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeetingEventStatusIcon) GetBackgroundColor() string {
	if o == nil || IsNil(o.BackgroundColor.Get()) {
		var ret string
		return ret
	}
	return *o.BackgroundColor.Get()
}

// GetBackgroundColorOk returns a tuple with the BackgroundColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeetingEventStatusIcon) GetBackgroundColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackgroundColor.Get(), o.BackgroundColor.IsSet()
}

// HasBackgroundColor returns a boolean if a field has been set.
func (o *MeetingEventStatusIcon) HasBackgroundColor() bool {
	if o != nil && o.BackgroundColor.IsSet() {
		return true
	}

	return false
}

// SetBackgroundColor gets a reference to the given NullableString and assigns it to the BackgroundColor field.
func (o *MeetingEventStatusIcon) SetBackgroundColor(v string) {
	o.BackgroundColor.Set(&v)
}

// SetBackgroundColorNil sets the value for BackgroundColor to be an explicit nil
func (o *MeetingEventStatusIcon) SetBackgroundColorNil() {
	o.BackgroundColor.Set(nil)
}

// UnsetBackgroundColor ensures that no value is present for BackgroundColor, not even an explicit nil
func (o *MeetingEventStatusIcon) UnsetBackgroundColor() {
	o.BackgroundColor.Unset()
}

func (o MeetingEventStatusIcon) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeetingEventStatusIcon) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Css.IsSet() {
		toSerialize["css"] = o.Css.Get()
	}
	if o.BorderColor.IsSet() {
		toSerialize["borderColor"] = o.BorderColor.Get()
	}
	if o.FontCode.IsSet() {
		toSerialize["fontCode"] = o.FontCode.Get()
	}
	if o.TextColor.IsSet() {
		toSerialize["textColor"] = o.TextColor.Get()
	}
	if o.BackgroundColor.IsSet() {
		toSerialize["backgroundColor"] = o.BackgroundColor.Get()
	}
	return toSerialize, nil
}

type NullableMeetingEventStatusIcon struct {
	value *MeetingEventStatusIcon
	isSet bool
}

func (v NullableMeetingEventStatusIcon) Get() *MeetingEventStatusIcon {
	return v.value
}

func (v *NullableMeetingEventStatusIcon) Set(val *MeetingEventStatusIcon) {
	v.value = val
	v.isSet = true
}

func (v NullableMeetingEventStatusIcon) IsSet() bool {
	return v.isSet
}

func (v *NullableMeetingEventStatusIcon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeetingEventStatusIcon(val *MeetingEventStatusIcon) *NullableMeetingEventStatusIcon {
	return &NullableMeetingEventStatusIcon{value: val, isSet: true}
}

func (v NullableMeetingEventStatusIcon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeetingEventStatusIcon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
