/*
Albi Api - v5

This Api will be responsible for overall data distribution and authorization.

API version: v5
Contact: support@albiware.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
	"fmt"
)

// NoteCreationOriginEnum the model 'NoteCreationOriginEnum'
type NoteCreationOriginEnum int32

// List of NoteCreationOriginEnum
const (
	NOTECREATIONORIGINENUM__0 NoteCreationOriginEnum = 0
	NOTECREATIONORIGINENUM__1 NoteCreationOriginEnum = 1
	NOTECREATIONORIGINENUM__2 NoteCreationOriginEnum = 2
	NOTECREATIONORIGINENUM__3 NoteCreationOriginEnum = 3
	NOTECREATIONORIGINENUM__4 NoteCreationOriginEnum = 4
	NOTECREATIONORIGINENUM__5 NoteCreationOriginEnum = 5
)

// All allowed values of NoteCreationOriginEnum enum
var AllowedNoteCreationOriginEnumEnumValues = []NoteCreationOriginEnum{
	0,
	1,
	2,
	3,
	4,
	5,
}

func (v *NoteCreationOriginEnum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NoteCreationOriginEnum(value)
	for _, existing := range AllowedNoteCreationOriginEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NoteCreationOriginEnum", value)
}

// NewNoteCreationOriginEnumFromValue returns a pointer to a valid NoteCreationOriginEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNoteCreationOriginEnumFromValue(v int32) (*NoteCreationOriginEnum, error) {
	ev := NoteCreationOriginEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NoteCreationOriginEnum: valid values are %v", v, AllowedNoteCreationOriginEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NoteCreationOriginEnum) IsValid() bool {
	for _, existing := range AllowedNoteCreationOriginEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NoteCreationOriginEnum value
func (v NoteCreationOriginEnum) Ptr() *NoteCreationOriginEnum {
	return &v
}

type NullableNoteCreationOriginEnum struct {
	value *NoteCreationOriginEnum
	isSet bool
}

func (v NullableNoteCreationOriginEnum) Get() *NoteCreationOriginEnum {
	return v.value
}

func (v *NullableNoteCreationOriginEnum) Set(val *NoteCreationOriginEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableNoteCreationOriginEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableNoteCreationOriginEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoteCreationOriginEnum(val *NoteCreationOriginEnum) *NullableNoteCreationOriginEnum {
	return &NullableNoteCreationOriginEnum{value: val, isSet: true}
}

func (v NullableNoteCreationOriginEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoteCreationOriginEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
