/*
Core API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
)

// checks if the CreateAEquipmentCopy200ResponseDataTypeImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAEquipmentCopy200ResponseDataTypeImage{}

// CreateAEquipmentCopy200ResponseDataTypeImage struct for CreateAEquipmentCopy200ResponseDataTypeImage
type CreateAEquipmentCopy200ResponseDataTypeImage struct {
	Id                   *int32  `json:"id,omitempty"`
	Name                 *string `json:"name,omitempty"`
	ThumbnailImage       *string `json:"thumbnailImage,omitempty"`
	Svg                  *string `json:"svg,omitempty"`
	Active               *bool   `json:"active,omitempty"`
	Priority             *int32  `json:"priority,omitempty"`
	IsDefault            *bool   `json:"isDefault,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAEquipmentCopy200ResponseDataTypeImage CreateAEquipmentCopy200ResponseDataTypeImage

// NewCreateAEquipmentCopy200ResponseDataTypeImage instantiates a new CreateAEquipmentCopy200ResponseDataTypeImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAEquipmentCopy200ResponseDataTypeImage() *CreateAEquipmentCopy200ResponseDataTypeImage {
	this := CreateAEquipmentCopy200ResponseDataTypeImage{}
	var id int32 = 0
	this.Id = &id
	var active bool = true
	this.Active = &active
	var priority int32 = 0
	this.Priority = &priority
	var isDefault bool = true
	this.IsDefault = &isDefault
	return &this
}

// NewCreateAEquipmentCopy200ResponseDataTypeImageWithDefaults instantiates a new CreateAEquipmentCopy200ResponseDataTypeImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAEquipmentCopy200ResponseDataTypeImageWithDefaults() *CreateAEquipmentCopy200ResponseDataTypeImage {
	this := CreateAEquipmentCopy200ResponseDataTypeImage{}
	var id int32 = 0
	this.Id = &id
	var active bool = true
	this.Active = &active
	var priority int32 = 0
	this.Priority = &priority
	var isDefault bool = true
	this.IsDefault = &isDefault
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) SetName(v string) {
	o.Name = &v
}

// GetThumbnailImage returns the ThumbnailImage field value if set, zero value otherwise.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetThumbnailImage() string {
	if o == nil || IsNil(o.ThumbnailImage) {
		var ret string
		return ret
	}
	return *o.ThumbnailImage
}

// GetThumbnailImageOk returns a tuple with the ThumbnailImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetThumbnailImageOk() (*string, bool) {
	if o == nil || IsNil(o.ThumbnailImage) {
		return nil, false
	}
	return o.ThumbnailImage, true
}

// HasThumbnailImage returns a boolean if a field has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) HasThumbnailImage() bool {
	if o != nil && !IsNil(o.ThumbnailImage) {
		return true
	}

	return false
}

// SetThumbnailImage gets a reference to the given string and assigns it to the ThumbnailImage field.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) SetThumbnailImage(v string) {
	o.ThumbnailImage = &v
}

// GetSvg returns the Svg field value if set, zero value otherwise.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetSvg() string {
	if o == nil || IsNil(o.Svg) {
		var ret string
		return ret
	}
	return *o.Svg
}

// GetSvgOk returns a tuple with the Svg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetSvgOk() (*string, bool) {
	if o == nil || IsNil(o.Svg) {
		return nil, false
	}
	return o.Svg, true
}

// HasSvg returns a boolean if a field has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) HasSvg() bool {
	if o != nil && !IsNil(o.Svg) {
		return true
	}

	return false
}

// SetSvg gets a reference to the given string and assigns it to the Svg field.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) SetSvg(v string) {
	o.Svg = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) SetActive(v bool) {
	o.Active = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) SetPriority(v int32) {
	o.Priority = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *CreateAEquipmentCopy200ResponseDataTypeImage) SetIsDefault(v bool) {
	o.IsDefault = &v
}

func (o CreateAEquipmentCopy200ResponseDataTypeImage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAEquipmentCopy200ResponseDataTypeImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ThumbnailImage) {
		toSerialize["thumbnailImage"] = o.ThumbnailImage
	}
	if !IsNil(o.Svg) {
		toSerialize["svg"] = o.Svg
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.IsDefault) {
		toSerialize["isDefault"] = o.IsDefault
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAEquipmentCopy200ResponseDataTypeImage) UnmarshalJSON(data []byte) (err error) {
	varCreateAEquipmentCopy200ResponseDataTypeImage := _CreateAEquipmentCopy200ResponseDataTypeImage{}

	err = json.Unmarshal(data, &varCreateAEquipmentCopy200ResponseDataTypeImage)

	if err != nil {
		return err
	}

	*o = CreateAEquipmentCopy200ResponseDataTypeImage(varCreateAEquipmentCopy200ResponseDataTypeImage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "thumbnailImage")
		delete(additionalProperties, "svg")
		delete(additionalProperties, "active")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "isDefault")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAEquipmentCopy200ResponseDataTypeImage struct {
	value *CreateAEquipmentCopy200ResponseDataTypeImage
	isSet bool
}

func (v NullableCreateAEquipmentCopy200ResponseDataTypeImage) Get() *CreateAEquipmentCopy200ResponseDataTypeImage {
	return v.value
}

func (v *NullableCreateAEquipmentCopy200ResponseDataTypeImage) Set(val *CreateAEquipmentCopy200ResponseDataTypeImage) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAEquipmentCopy200ResponseDataTypeImage) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAEquipmentCopy200ResponseDataTypeImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAEquipmentCopy200ResponseDataTypeImage(val *CreateAEquipmentCopy200ResponseDataTypeImage) *NullableCreateAEquipmentCopy200ResponseDataTypeImage {
	return &NullableCreateAEquipmentCopy200ResponseDataTypeImage{value: val, isSet: true}
}

func (v NullableCreateAEquipmentCopy200ResponseDataTypeImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAEquipmentCopy200ResponseDataTypeImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
