/*
Albi Api - v5

This Api will be responsible for overall data distribution and authorization.

API version: v5
Contact: support@albiware.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the PublicApiCreateMeetingDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicApiCreateMeetingDetails{}

// PublicApiCreateMeetingDetails struct for PublicApiCreateMeetingDetails
type PublicApiCreateMeetingDetails struct {
	Title              string                  `json:"title"`
	Status             NullableString          `json:"status,omitempty"`
	ProjectId          NullableInt64           `json:"projectId,omitempty"`
	ProjectName        NullableString          `json:"projectName,omitempty"`
	Location           *bool                   `json:"location,omitempty"`
	Notes              NullableString          `json:"notes,omitempty"`
	Start              time.Time               `json:"start"`
	StartTimezone      string                  `json:"startTimezone"`
	End                time.Time               `json:"end"`
	EndTimezone        NullableString          `json:"endTimezone,omitempty"`
	IsAllDay           *bool                   `json:"isAllDay,omitempty"`
	RequiredAttendees  []string                `json:"requiredAttendees,omitempty"`
	OptionalAttendees  []string                `json:"optionalAttendees,omitempty"`
	SendInvite         *bool                   `json:"sendInvite,omitempty"`
	Address1           NullableString          `json:"address1,omitempty"`
	Address2           NullableString          `json:"address2,omitempty"`
	City               NullableString          `json:"city,omitempty"`
	State              NullableString          `json:"state,omitempty"`
	Country            NullableString          `json:"country,omitempty"`
	ZipCode            NullableString          `json:"zipCode,omitempty"`
	CreatedBy          NullableInt64           `json:"createdBy,omitempty"`
	OrganizerEmail     NullableString          `json:"organizerEmail,omitempty"`
	ScheduleCategoryId *int64                  `json:"scheduleCategoryId,omitempty"`
	TagData            []TagData               `json:"tagData,omitempty"`
	StatusIcon         *MeetingEventStatusIcon `json:"statusIcon,omitempty"`
	Longitude          NullableFloat64         `json:"longitude,omitempty"`
	Latitude           NullableFloat64         `json:"latitude,omitempty"`
}

type _PublicApiCreateMeetingDetails PublicApiCreateMeetingDetails

// NewPublicApiCreateMeetingDetails instantiates a new PublicApiCreateMeetingDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicApiCreateMeetingDetails(title string, start time.Time, startTimezone string, end time.Time) *PublicApiCreateMeetingDetails {
	this := PublicApiCreateMeetingDetails{}
	this.Title = title
	this.Start = start
	this.StartTimezone = startTimezone
	this.End = end
	return &this
}

// NewPublicApiCreateMeetingDetailsWithDefaults instantiates a new PublicApiCreateMeetingDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicApiCreateMeetingDetailsWithDefaults() *PublicApiCreateMeetingDetails {
	this := PublicApiCreateMeetingDetails{}
	return &this
}

// GetTitle returns the Title field value
func (o *PublicApiCreateMeetingDetails) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *PublicApiCreateMeetingDetails) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *PublicApiCreateMeetingDetails) SetTitle(v string) {
	o.Title = v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *PublicApiCreateMeetingDetails) SetStatus(v string) {
	o.Status.Set(&v)
}

// SetStatusNil sets the value for Status to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetStatus() {
	o.Status.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetProjectId() int64 {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret int64
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetProjectIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableInt64 and assigns it to the ProjectId field.
func (o *PublicApiCreateMeetingDetails) SetProjectId(v int64) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectName.Get()
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectName.Get(), o.ProjectName.IsSet()
}

// HasProjectName returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasProjectName() bool {
	if o != nil && o.ProjectName.IsSet() {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given NullableString and assigns it to the ProjectName field.
func (o *PublicApiCreateMeetingDetails) SetProjectName(v string) {
	o.ProjectName.Set(&v)
}

// SetProjectNameNil sets the value for ProjectName to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetProjectNameNil() {
	o.ProjectName.Set(nil)
}

// UnsetProjectName ensures that no value is present for ProjectName, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetProjectName() {
	o.ProjectName.Unset()
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *PublicApiCreateMeetingDetails) GetLocation() bool {
	if o == nil || IsNil(o.Location) {
		var ret bool
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicApiCreateMeetingDetails) GetLocationOk() (*bool, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given bool and assigns it to the Location field.
func (o *PublicApiCreateMeetingDetails) SetLocation(v bool) {
	o.Location = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetNotes() string {
	if o == nil || IsNil(o.Notes.Get()) {
		var ret string
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableString and assigns it to the Notes field.
func (o *PublicApiCreateMeetingDetails) SetNotes(v string) {
	o.Notes.Set(&v)
}

// SetNotesNil sets the value for Notes to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetNotes() {
	o.Notes.Unset()
}

// GetStart returns the Start field value
func (o *PublicApiCreateMeetingDetails) GetStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *PublicApiCreateMeetingDetails) GetStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *PublicApiCreateMeetingDetails) SetStart(v time.Time) {
	o.Start = v
}

// GetStartTimezone returns the StartTimezone field value
func (o *PublicApiCreateMeetingDetails) GetStartTimezone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartTimezone
}

// GetStartTimezoneOk returns a tuple with the StartTimezone field value
// and a boolean to check if the value has been set.
func (o *PublicApiCreateMeetingDetails) GetStartTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTimezone, true
}

// SetStartTimezone sets field value
func (o *PublicApiCreateMeetingDetails) SetStartTimezone(v string) {
	o.StartTimezone = v
}

// GetEnd returns the End field value
func (o *PublicApiCreateMeetingDetails) GetEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *PublicApiCreateMeetingDetails) GetEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *PublicApiCreateMeetingDetails) SetEnd(v time.Time) {
	o.End = v
}

// GetEndTimezone returns the EndTimezone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetEndTimezone() string {
	if o == nil || IsNil(o.EndTimezone.Get()) {
		var ret string
		return ret
	}
	return *o.EndTimezone.Get()
}

// GetEndTimezoneOk returns a tuple with the EndTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetEndTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndTimezone.Get(), o.EndTimezone.IsSet()
}

// HasEndTimezone returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasEndTimezone() bool {
	if o != nil && o.EndTimezone.IsSet() {
		return true
	}

	return false
}

// SetEndTimezone gets a reference to the given NullableString and assigns it to the EndTimezone field.
func (o *PublicApiCreateMeetingDetails) SetEndTimezone(v string) {
	o.EndTimezone.Set(&v)
}

// SetEndTimezoneNil sets the value for EndTimezone to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetEndTimezoneNil() {
	o.EndTimezone.Set(nil)
}

// UnsetEndTimezone ensures that no value is present for EndTimezone, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetEndTimezone() {
	o.EndTimezone.Unset()
}

// GetIsAllDay returns the IsAllDay field value if set, zero value otherwise.
func (o *PublicApiCreateMeetingDetails) GetIsAllDay() bool {
	if o == nil || IsNil(o.IsAllDay) {
		var ret bool
		return ret
	}
	return *o.IsAllDay
}

// GetIsAllDayOk returns a tuple with the IsAllDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicApiCreateMeetingDetails) GetIsAllDayOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAllDay) {
		return nil, false
	}
	return o.IsAllDay, true
}

// HasIsAllDay returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasIsAllDay() bool {
	if o != nil && !IsNil(o.IsAllDay) {
		return true
	}

	return false
}

// SetIsAllDay gets a reference to the given bool and assigns it to the IsAllDay field.
func (o *PublicApiCreateMeetingDetails) SetIsAllDay(v bool) {
	o.IsAllDay = &v
}

// GetRequiredAttendees returns the RequiredAttendees field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetRequiredAttendees() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RequiredAttendees
}

// GetRequiredAttendeesOk returns a tuple with the RequiredAttendees field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetRequiredAttendeesOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredAttendees) {
		return nil, false
	}
	return o.RequiredAttendees, true
}

// HasRequiredAttendees returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasRequiredAttendees() bool {
	if o != nil && !IsNil(o.RequiredAttendees) {
		return true
	}

	return false
}

// SetRequiredAttendees gets a reference to the given []string and assigns it to the RequiredAttendees field.
func (o *PublicApiCreateMeetingDetails) SetRequiredAttendees(v []string) {
	o.RequiredAttendees = v
}

// GetOptionalAttendees returns the OptionalAttendees field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetOptionalAttendees() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.OptionalAttendees
}

// GetOptionalAttendeesOk returns a tuple with the OptionalAttendees field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetOptionalAttendeesOk() ([]string, bool) {
	if o == nil || IsNil(o.OptionalAttendees) {
		return nil, false
	}
	return o.OptionalAttendees, true
}

// HasOptionalAttendees returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasOptionalAttendees() bool {
	if o != nil && !IsNil(o.OptionalAttendees) {
		return true
	}

	return false
}

// SetOptionalAttendees gets a reference to the given []string and assigns it to the OptionalAttendees field.
func (o *PublicApiCreateMeetingDetails) SetOptionalAttendees(v []string) {
	o.OptionalAttendees = v
}

// GetSendInvite returns the SendInvite field value if set, zero value otherwise.
func (o *PublicApiCreateMeetingDetails) GetSendInvite() bool {
	if o == nil || IsNil(o.SendInvite) {
		var ret bool
		return ret
	}
	return *o.SendInvite
}

// GetSendInviteOk returns a tuple with the SendInvite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicApiCreateMeetingDetails) GetSendInviteOk() (*bool, bool) {
	if o == nil || IsNil(o.SendInvite) {
		return nil, false
	}
	return o.SendInvite, true
}

// HasSendInvite returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasSendInvite() bool {
	if o != nil && !IsNil(o.SendInvite) {
		return true
	}

	return false
}

// SetSendInvite gets a reference to the given bool and assigns it to the SendInvite field.
func (o *PublicApiCreateMeetingDetails) SetSendInvite(v bool) {
	o.SendInvite = &v
}

// GetAddress1 returns the Address1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetAddress1() string {
	if o == nil || IsNil(o.Address1.Get()) {
		var ret string
		return ret
	}
	return *o.Address1.Get()
}

// GetAddress1Ok returns a tuple with the Address1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetAddress1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address1.Get(), o.Address1.IsSet()
}

// HasAddress1 returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasAddress1() bool {
	if o != nil && o.Address1.IsSet() {
		return true
	}

	return false
}

// SetAddress1 gets a reference to the given NullableString and assigns it to the Address1 field.
func (o *PublicApiCreateMeetingDetails) SetAddress1(v string) {
	o.Address1.Set(&v)
}

// SetAddress1Nil sets the value for Address1 to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetAddress1Nil() {
	o.Address1.Set(nil)
}

// UnsetAddress1 ensures that no value is present for Address1, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetAddress1() {
	o.Address1.Unset()
}

// GetAddress2 returns the Address2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetAddress2() string {
	if o == nil || IsNil(o.Address2.Get()) {
		var ret string
		return ret
	}
	return *o.Address2.Get()
}

// GetAddress2Ok returns a tuple with the Address2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetAddress2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address2.Get(), o.Address2.IsSet()
}

// HasAddress2 returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasAddress2() bool {
	if o != nil && o.Address2.IsSet() {
		return true
	}

	return false
}

// SetAddress2 gets a reference to the given NullableString and assigns it to the Address2 field.
func (o *PublicApiCreateMeetingDetails) SetAddress2(v string) {
	o.Address2.Set(&v)
}

// SetAddress2Nil sets the value for Address2 to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetAddress2Nil() {
	o.Address2.Set(nil)
}

// UnsetAddress2 ensures that no value is present for Address2, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetAddress2() {
	o.Address2.Unset()
}

// GetCity returns the City field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetCity() string {
	if o == nil || IsNil(o.City.Get()) {
		var ret string
		return ret
	}
	return *o.City.Get()
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.City.Get(), o.City.IsSet()
}

// HasCity returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasCity() bool {
	if o != nil && o.City.IsSet() {
		return true
	}

	return false
}

// SetCity gets a reference to the given NullableString and assigns it to the City field.
func (o *PublicApiCreateMeetingDetails) SetCity(v string) {
	o.City.Set(&v)
}

// SetCityNil sets the value for City to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetCityNil() {
	o.City.Set(nil)
}

// UnsetCity ensures that no value is present for City, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetCity() {
	o.City.Unset()
}

// GetState returns the State field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetState() string {
	if o == nil || IsNil(o.State.Get()) {
		var ret string
		return ret
	}
	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// HasState returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasState() bool {
	if o != nil && o.State.IsSet() {
		return true
	}

	return false
}

// SetState gets a reference to the given NullableString and assigns it to the State field.
func (o *PublicApiCreateMeetingDetails) SetState(v string) {
	o.State.Set(&v)
}

// SetStateNil sets the value for State to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetStateNil() {
	o.State.Set(nil)
}

// UnsetState ensures that no value is present for State, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetState() {
	o.State.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *PublicApiCreateMeetingDetails) SetCountry(v string) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetCountry() {
	o.Country.Unset()
}

// GetZipCode returns the ZipCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetZipCode() string {
	if o == nil || IsNil(o.ZipCode.Get()) {
		var ret string
		return ret
	}
	return *o.ZipCode.Get()
}

// GetZipCodeOk returns a tuple with the ZipCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetZipCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ZipCode.Get(), o.ZipCode.IsSet()
}

// HasZipCode returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasZipCode() bool {
	if o != nil && o.ZipCode.IsSet() {
		return true
	}

	return false
}

// SetZipCode gets a reference to the given NullableString and assigns it to the ZipCode field.
func (o *PublicApiCreateMeetingDetails) SetZipCode(v string) {
	o.ZipCode.Set(&v)
}

// SetZipCodeNil sets the value for ZipCode to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetZipCodeNil() {
	o.ZipCode.Set(nil)
}

// UnsetZipCode ensures that no value is present for ZipCode, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetZipCode() {
	o.ZipCode.Unset()
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetCreatedBy() int64 {
	if o == nil || IsNil(o.CreatedBy.Get()) {
		var ret int64
		return ret
	}
	return *o.CreatedBy.Get()
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetCreatedByOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedBy.Get(), o.CreatedBy.IsSet()
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasCreatedBy() bool {
	if o != nil && o.CreatedBy.IsSet() {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given NullableInt64 and assigns it to the CreatedBy field.
func (o *PublicApiCreateMeetingDetails) SetCreatedBy(v int64) {
	o.CreatedBy.Set(&v)
}

// SetCreatedByNil sets the value for CreatedBy to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetCreatedByNil() {
	o.CreatedBy.Set(nil)
}

// UnsetCreatedBy ensures that no value is present for CreatedBy, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetCreatedBy() {
	o.CreatedBy.Unset()
}

// GetOrganizerEmail returns the OrganizerEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetOrganizerEmail() string {
	if o == nil || IsNil(o.OrganizerEmail.Get()) {
		var ret string
		return ret
	}
	return *o.OrganizerEmail.Get()
}

// GetOrganizerEmailOk returns a tuple with the OrganizerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetOrganizerEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizerEmail.Get(), o.OrganizerEmail.IsSet()
}

// HasOrganizerEmail returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasOrganizerEmail() bool {
	if o != nil && o.OrganizerEmail.IsSet() {
		return true
	}

	return false
}

// SetOrganizerEmail gets a reference to the given NullableString and assigns it to the OrganizerEmail field.
func (o *PublicApiCreateMeetingDetails) SetOrganizerEmail(v string) {
	o.OrganizerEmail.Set(&v)
}

// SetOrganizerEmailNil sets the value for OrganizerEmail to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetOrganizerEmailNil() {
	o.OrganizerEmail.Set(nil)
}

// UnsetOrganizerEmail ensures that no value is present for OrganizerEmail, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetOrganizerEmail() {
	o.OrganizerEmail.Unset()
}

// GetScheduleCategoryId returns the ScheduleCategoryId field value if set, zero value otherwise.
func (o *PublicApiCreateMeetingDetails) GetScheduleCategoryId() int64 {
	if o == nil || IsNil(o.ScheduleCategoryId) {
		var ret int64
		return ret
	}
	return *o.ScheduleCategoryId
}

// GetScheduleCategoryIdOk returns a tuple with the ScheduleCategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicApiCreateMeetingDetails) GetScheduleCategoryIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ScheduleCategoryId) {
		return nil, false
	}
	return o.ScheduleCategoryId, true
}

// HasScheduleCategoryId returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasScheduleCategoryId() bool {
	if o != nil && !IsNil(o.ScheduleCategoryId) {
		return true
	}

	return false
}

// SetScheduleCategoryId gets a reference to the given int64 and assigns it to the ScheduleCategoryId field.
func (o *PublicApiCreateMeetingDetails) SetScheduleCategoryId(v int64) {
	o.ScheduleCategoryId = &v
}

// GetTagData returns the TagData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetTagData() []TagData {
	if o == nil {
		var ret []TagData
		return ret
	}
	return o.TagData
}

// GetTagDataOk returns a tuple with the TagData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetTagDataOk() ([]TagData, bool) {
	if o == nil || IsNil(o.TagData) {
		return nil, false
	}
	return o.TagData, true
}

// HasTagData returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasTagData() bool {
	if o != nil && !IsNil(o.TagData) {
		return true
	}

	return false
}

// SetTagData gets a reference to the given []TagData and assigns it to the TagData field.
func (o *PublicApiCreateMeetingDetails) SetTagData(v []TagData) {
	o.TagData = v
}

// GetStatusIcon returns the StatusIcon field value if set, zero value otherwise.
func (o *PublicApiCreateMeetingDetails) GetStatusIcon() MeetingEventStatusIcon {
	if o == nil || IsNil(o.StatusIcon) {
		var ret MeetingEventStatusIcon
		return ret
	}
	return *o.StatusIcon
}

// GetStatusIconOk returns a tuple with the StatusIcon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicApiCreateMeetingDetails) GetStatusIconOk() (*MeetingEventStatusIcon, bool) {
	if o == nil || IsNil(o.StatusIcon) {
		return nil, false
	}
	return o.StatusIcon, true
}

// HasStatusIcon returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasStatusIcon() bool {
	if o != nil && !IsNil(o.StatusIcon) {
		return true
	}

	return false
}

// SetStatusIcon gets a reference to the given MeetingEventStatusIcon and assigns it to the StatusIcon field.
func (o *PublicApiCreateMeetingDetails) SetStatusIcon(v MeetingEventStatusIcon) {
	o.StatusIcon = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude.Get()) {
		var ret float64
		return ret
	}
	return *o.Longitude.Get()
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Longitude.Get(), o.Longitude.IsSet()
}

// HasLongitude returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasLongitude() bool {
	if o != nil && o.Longitude.IsSet() {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given NullableFloat64 and assigns it to the Longitude field.
func (o *PublicApiCreateMeetingDetails) SetLongitude(v float64) {
	o.Longitude.Set(&v)
}

// SetLongitudeNil sets the value for Longitude to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetLongitudeNil() {
	o.Longitude.Set(nil)
}

// UnsetLongitude ensures that no value is present for Longitude, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetLongitude() {
	o.Longitude.Unset()
}

// GetLatitude returns the Latitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicApiCreateMeetingDetails) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude.Get()) {
		var ret float64
		return ret
	}
	return *o.Latitude.Get()
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicApiCreateMeetingDetails) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Latitude.Get(), o.Latitude.IsSet()
}

// HasLatitude returns a boolean if a field has been set.
func (o *PublicApiCreateMeetingDetails) HasLatitude() bool {
	if o != nil && o.Latitude.IsSet() {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given NullableFloat64 and assigns it to the Latitude field.
func (o *PublicApiCreateMeetingDetails) SetLatitude(v float64) {
	o.Latitude.Set(&v)
}

// SetLatitudeNil sets the value for Latitude to be an explicit nil
func (o *PublicApiCreateMeetingDetails) SetLatitudeNil() {
	o.Latitude.Set(nil)
}

// UnsetLatitude ensures that no value is present for Latitude, not even an explicit nil
func (o *PublicApiCreateMeetingDetails) UnsetLatitude() {
	o.Latitude.Unset()
}

func (o PublicApiCreateMeetingDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicApiCreateMeetingDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["projectId"] = o.ProjectId.Get()
	}
	if o.ProjectName.IsSet() {
		toSerialize["projectName"] = o.ProjectName.Get()
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	toSerialize["start"] = o.Start
	toSerialize["startTimezone"] = o.StartTimezone
	toSerialize["end"] = o.End
	if o.EndTimezone.IsSet() {
		toSerialize["endTimezone"] = o.EndTimezone.Get()
	}
	if !IsNil(o.IsAllDay) {
		toSerialize["isAllDay"] = o.IsAllDay
	}
	if o.RequiredAttendees != nil {
		toSerialize["requiredAttendees"] = o.RequiredAttendees
	}
	if o.OptionalAttendees != nil {
		toSerialize["optionalAttendees"] = o.OptionalAttendees
	}
	if !IsNil(o.SendInvite) {
		toSerialize["sendInvite"] = o.SendInvite
	}
	if o.Address1.IsSet() {
		toSerialize["address1"] = o.Address1.Get()
	}
	if o.Address2.IsSet() {
		toSerialize["address2"] = o.Address2.Get()
	}
	if o.City.IsSet() {
		toSerialize["city"] = o.City.Get()
	}
	if o.State.IsSet() {
		toSerialize["state"] = o.State.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.ZipCode.IsSet() {
		toSerialize["zipCode"] = o.ZipCode.Get()
	}
	if o.CreatedBy.IsSet() {
		toSerialize["createdBy"] = o.CreatedBy.Get()
	}
	if o.OrganizerEmail.IsSet() {
		toSerialize["organizerEmail"] = o.OrganizerEmail.Get()
	}
	if !IsNil(o.ScheduleCategoryId) {
		toSerialize["scheduleCategoryId"] = o.ScheduleCategoryId
	}
	if o.TagData != nil {
		toSerialize["tagData"] = o.TagData
	}
	if !IsNil(o.StatusIcon) {
		toSerialize["statusIcon"] = o.StatusIcon
	}
	if o.Longitude.IsSet() {
		toSerialize["longitude"] = o.Longitude.Get()
	}
	if o.Latitude.IsSet() {
		toSerialize["latitude"] = o.Latitude.Get()
	}
	return toSerialize, nil
}

func (o *PublicApiCreateMeetingDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"start",
		"startTimezone",
		"end",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicApiCreateMeetingDetails := _PublicApiCreateMeetingDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicApiCreateMeetingDetails)

	if err != nil {
		return err
	}

	*o = PublicApiCreateMeetingDetails(varPublicApiCreateMeetingDetails)

	return err
}

type NullablePublicApiCreateMeetingDetails struct {
	value *PublicApiCreateMeetingDetails
	isSet bool
}

func (v NullablePublicApiCreateMeetingDetails) Get() *PublicApiCreateMeetingDetails {
	return v.value
}

func (v *NullablePublicApiCreateMeetingDetails) Set(val *PublicApiCreateMeetingDetails) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicApiCreateMeetingDetails) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicApiCreateMeetingDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicApiCreateMeetingDetails(val *PublicApiCreateMeetingDetails) *NullablePublicApiCreateMeetingDetails {
	return &NullablePublicApiCreateMeetingDetails{value: val, isSet: true}
}

func (v NullablePublicApiCreateMeetingDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicApiCreateMeetingDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
