/*
Albi Api - v5

This Api will be responsible for overall data distribution and authorization.

API version: v5
Contact: support@albiware.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the EquipmentDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EquipmentDto{}

// EquipmentDto struct for EquipmentDto
type EquipmentDto struct {
	Id                *int64          `json:"id,omitempty"`
	EquipmentCustomId string          `json:"equipmentCustomId"`
	EquipmentTypeId   int64           `json:"equipmentTypeId"`
	EquipmentTypeName NullableString  `json:"equipmentTypeName,omitempty"`
	Status            string          `json:"status"`
	StatusName        NullableString  `json:"statusName,omitempty"`
	LocationId        int64           `json:"locationId"`
	LocationName      NullableString  `json:"locationName,omitempty"`
	ProjectId         NullableInt64   `json:"projectId,omitempty"`
	ProjectName       NullableString  `json:"projectName,omitempty"`
	PurchaseDate      NullableTime    `json:"purchaseDate,omitempty"`
	Manufacturer      NullableString  `json:"manufacturer,omitempty"`
	SerialNo          NullableString  `json:"serialNo,omitempty"`
	EquipmentModel    NullableString  `json:"equipmentModel,omitempty"`
	PurchasePrice     NullableFloat64 `json:"purchasePrice,omitempty"`
	BillingType       NullableString  `json:"billingType,omitempty"`
	BillingTypeName   NullableString  `json:"billingTypeName,omitempty"`
	BillingCost       NullableFloat64 `json:"billingCost,omitempty"`
	MaxDay            NullableInt32   `json:"maxDay,omitempty"`
	CurrentStaffId    NullableInt64   `json:"currentStaffId,omitempty"`
	CurrentCompanyId  NullableInt64   `json:"currentCompanyId,omitempty"`
	Source            NullableString  `json:"source,omitempty"`
	Barcode           NullableString  `json:"barcode,omitempty"`
}

type _EquipmentDto EquipmentDto

// NewEquipmentDto instantiates a new EquipmentDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEquipmentDto(equipmentCustomId string, equipmentTypeId int64, status string, locationId int64) *EquipmentDto {
	this := EquipmentDto{}
	this.EquipmentCustomId = equipmentCustomId
	this.EquipmentTypeId = equipmentTypeId
	this.Status = status
	this.LocationId = locationId
	return &this
}

// NewEquipmentDtoWithDefaults instantiates a new EquipmentDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEquipmentDtoWithDefaults() *EquipmentDto {
	this := EquipmentDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EquipmentDto) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentDto) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EquipmentDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *EquipmentDto) SetId(v int64) {
	o.Id = &v
}

// GetEquipmentCustomId returns the EquipmentCustomId field value
func (o *EquipmentDto) GetEquipmentCustomId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EquipmentCustomId
}

// GetEquipmentCustomIdOk returns a tuple with the EquipmentCustomId field value
// and a boolean to check if the value has been set.
func (o *EquipmentDto) GetEquipmentCustomIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EquipmentCustomId, true
}

// SetEquipmentCustomId sets field value
func (o *EquipmentDto) SetEquipmentCustomId(v string) {
	o.EquipmentCustomId = v
}

// GetEquipmentTypeId returns the EquipmentTypeId field value
func (o *EquipmentDto) GetEquipmentTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EquipmentTypeId
}

// GetEquipmentTypeIdOk returns a tuple with the EquipmentTypeId field value
// and a boolean to check if the value has been set.
func (o *EquipmentDto) GetEquipmentTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EquipmentTypeId, true
}

// SetEquipmentTypeId sets field value
func (o *EquipmentDto) SetEquipmentTypeId(v int64) {
	o.EquipmentTypeId = v
}

// GetEquipmentTypeName returns the EquipmentTypeName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetEquipmentTypeName() string {
	if o == nil || IsNil(o.EquipmentTypeName.Get()) {
		var ret string
		return ret
	}
	return *o.EquipmentTypeName.Get()
}

// GetEquipmentTypeNameOk returns a tuple with the EquipmentTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetEquipmentTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EquipmentTypeName.Get(), o.EquipmentTypeName.IsSet()
}

// HasEquipmentTypeName returns a boolean if a field has been set.
func (o *EquipmentDto) HasEquipmentTypeName() bool {
	if o != nil && o.EquipmentTypeName.IsSet() {
		return true
	}

	return false
}

// SetEquipmentTypeName gets a reference to the given NullableString and assigns it to the EquipmentTypeName field.
func (o *EquipmentDto) SetEquipmentTypeName(v string) {
	o.EquipmentTypeName.Set(&v)
}

// SetEquipmentTypeNameNil sets the value for EquipmentTypeName to be an explicit nil
func (o *EquipmentDto) SetEquipmentTypeNameNil() {
	o.EquipmentTypeName.Set(nil)
}

// UnsetEquipmentTypeName ensures that no value is present for EquipmentTypeName, not even an explicit nil
func (o *EquipmentDto) UnsetEquipmentTypeName() {
	o.EquipmentTypeName.Unset()
}

// GetStatus returns the Status field value
func (o *EquipmentDto) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *EquipmentDto) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *EquipmentDto) SetStatus(v string) {
	o.Status = v
}

// GetStatusName returns the StatusName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetStatusName() string {
	if o == nil || IsNil(o.StatusName.Get()) {
		var ret string
		return ret
	}
	return *o.StatusName.Get()
}

// GetStatusNameOk returns a tuple with the StatusName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetStatusNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusName.Get(), o.StatusName.IsSet()
}

// HasStatusName returns a boolean if a field has been set.
func (o *EquipmentDto) HasStatusName() bool {
	if o != nil && o.StatusName.IsSet() {
		return true
	}

	return false
}

// SetStatusName gets a reference to the given NullableString and assigns it to the StatusName field.
func (o *EquipmentDto) SetStatusName(v string) {
	o.StatusName.Set(&v)
}

// SetStatusNameNil sets the value for StatusName to be an explicit nil
func (o *EquipmentDto) SetStatusNameNil() {
	o.StatusName.Set(nil)
}

// UnsetStatusName ensures that no value is present for StatusName, not even an explicit nil
func (o *EquipmentDto) UnsetStatusName() {
	o.StatusName.Unset()
}

// GetLocationId returns the LocationId field value
func (o *EquipmentDto) GetLocationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value
// and a boolean to check if the value has been set.
func (o *EquipmentDto) GetLocationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationId, true
}

// SetLocationId sets field value
func (o *EquipmentDto) SetLocationId(v int64) {
	o.LocationId = v
}

// GetLocationName returns the LocationName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetLocationName() string {
	if o == nil || IsNil(o.LocationName.Get()) {
		var ret string
		return ret
	}
	return *o.LocationName.Get()
}

// GetLocationNameOk returns a tuple with the LocationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetLocationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LocationName.Get(), o.LocationName.IsSet()
}

// HasLocationName returns a boolean if a field has been set.
func (o *EquipmentDto) HasLocationName() bool {
	if o != nil && o.LocationName.IsSet() {
		return true
	}

	return false
}

// SetLocationName gets a reference to the given NullableString and assigns it to the LocationName field.
func (o *EquipmentDto) SetLocationName(v string) {
	o.LocationName.Set(&v)
}

// SetLocationNameNil sets the value for LocationName to be an explicit nil
func (o *EquipmentDto) SetLocationNameNil() {
	o.LocationName.Set(nil)
}

// UnsetLocationName ensures that no value is present for LocationName, not even an explicit nil
func (o *EquipmentDto) UnsetLocationName() {
	o.LocationName.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetProjectId() int64 {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret int64
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetProjectIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *EquipmentDto) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableInt64 and assigns it to the ProjectId field.
func (o *EquipmentDto) SetProjectId(v int64) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *EquipmentDto) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *EquipmentDto) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectName.Get()
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectName.Get(), o.ProjectName.IsSet()
}

// HasProjectName returns a boolean if a field has been set.
func (o *EquipmentDto) HasProjectName() bool {
	if o != nil && o.ProjectName.IsSet() {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given NullableString and assigns it to the ProjectName field.
func (o *EquipmentDto) SetProjectName(v string) {
	o.ProjectName.Set(&v)
}

// SetProjectNameNil sets the value for ProjectName to be an explicit nil
func (o *EquipmentDto) SetProjectNameNil() {
	o.ProjectName.Set(nil)
}

// UnsetProjectName ensures that no value is present for ProjectName, not even an explicit nil
func (o *EquipmentDto) UnsetProjectName() {
	o.ProjectName.Unset()
}

// GetPurchaseDate returns the PurchaseDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetPurchaseDate() time.Time {
	if o == nil || IsNil(o.PurchaseDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.PurchaseDate.Get()
}

// GetPurchaseDateOk returns a tuple with the PurchaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetPurchaseDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PurchaseDate.Get(), o.PurchaseDate.IsSet()
}

// HasPurchaseDate returns a boolean if a field has been set.
func (o *EquipmentDto) HasPurchaseDate() bool {
	if o != nil && o.PurchaseDate.IsSet() {
		return true
	}

	return false
}

// SetPurchaseDate gets a reference to the given NullableTime and assigns it to the PurchaseDate field.
func (o *EquipmentDto) SetPurchaseDate(v time.Time) {
	o.PurchaseDate.Set(&v)
}

// SetPurchaseDateNil sets the value for PurchaseDate to be an explicit nil
func (o *EquipmentDto) SetPurchaseDateNil() {
	o.PurchaseDate.Set(nil)
}

// UnsetPurchaseDate ensures that no value is present for PurchaseDate, not even an explicit nil
func (o *EquipmentDto) UnsetPurchaseDate() {
	o.PurchaseDate.Unset()
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer.Get()) {
		var ret string
		return ret
	}
	return *o.Manufacturer.Get()
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Manufacturer.Get(), o.Manufacturer.IsSet()
}

// HasManufacturer returns a boolean if a field has been set.
func (o *EquipmentDto) HasManufacturer() bool {
	if o != nil && o.Manufacturer.IsSet() {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given NullableString and assigns it to the Manufacturer field.
func (o *EquipmentDto) SetManufacturer(v string) {
	o.Manufacturer.Set(&v)
}

// SetManufacturerNil sets the value for Manufacturer to be an explicit nil
func (o *EquipmentDto) SetManufacturerNil() {
	o.Manufacturer.Set(nil)
}

// UnsetManufacturer ensures that no value is present for Manufacturer, not even an explicit nil
func (o *EquipmentDto) UnsetManufacturer() {
	o.Manufacturer.Unset()
}

// GetSerialNo returns the SerialNo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetSerialNo() string {
	if o == nil || IsNil(o.SerialNo.Get()) {
		var ret string
		return ret
	}
	return *o.SerialNo.Get()
}

// GetSerialNoOk returns a tuple with the SerialNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetSerialNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SerialNo.Get(), o.SerialNo.IsSet()
}

// HasSerialNo returns a boolean if a field has been set.
func (o *EquipmentDto) HasSerialNo() bool {
	if o != nil && o.SerialNo.IsSet() {
		return true
	}

	return false
}

// SetSerialNo gets a reference to the given NullableString and assigns it to the SerialNo field.
func (o *EquipmentDto) SetSerialNo(v string) {
	o.SerialNo.Set(&v)
}

// SetSerialNoNil sets the value for SerialNo to be an explicit nil
func (o *EquipmentDto) SetSerialNoNil() {
	o.SerialNo.Set(nil)
}

// UnsetSerialNo ensures that no value is present for SerialNo, not even an explicit nil
func (o *EquipmentDto) UnsetSerialNo() {
	o.SerialNo.Unset()
}

// GetEquipmentModel returns the EquipmentModel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetEquipmentModel() string {
	if o == nil || IsNil(o.EquipmentModel.Get()) {
		var ret string
		return ret
	}
	return *o.EquipmentModel.Get()
}

// GetEquipmentModelOk returns a tuple with the EquipmentModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetEquipmentModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EquipmentModel.Get(), o.EquipmentModel.IsSet()
}

// HasEquipmentModel returns a boolean if a field has been set.
func (o *EquipmentDto) HasEquipmentModel() bool {
	if o != nil && o.EquipmentModel.IsSet() {
		return true
	}

	return false
}

// SetEquipmentModel gets a reference to the given NullableString and assigns it to the EquipmentModel field.
func (o *EquipmentDto) SetEquipmentModel(v string) {
	o.EquipmentModel.Set(&v)
}

// SetEquipmentModelNil sets the value for EquipmentModel to be an explicit nil
func (o *EquipmentDto) SetEquipmentModelNil() {
	o.EquipmentModel.Set(nil)
}

// UnsetEquipmentModel ensures that no value is present for EquipmentModel, not even an explicit nil
func (o *EquipmentDto) UnsetEquipmentModel() {
	o.EquipmentModel.Unset()
}

// GetPurchasePrice returns the PurchasePrice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetPurchasePrice() float64 {
	if o == nil || IsNil(o.PurchasePrice.Get()) {
		var ret float64
		return ret
	}
	return *o.PurchasePrice.Get()
}

// GetPurchasePriceOk returns a tuple with the PurchasePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetPurchasePriceOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.PurchasePrice.Get(), o.PurchasePrice.IsSet()
}

// HasPurchasePrice returns a boolean if a field has been set.
func (o *EquipmentDto) HasPurchasePrice() bool {
	if o != nil && o.PurchasePrice.IsSet() {
		return true
	}

	return false
}

// SetPurchasePrice gets a reference to the given NullableFloat64 and assigns it to the PurchasePrice field.
func (o *EquipmentDto) SetPurchasePrice(v float64) {
	o.PurchasePrice.Set(&v)
}

// SetPurchasePriceNil sets the value for PurchasePrice to be an explicit nil
func (o *EquipmentDto) SetPurchasePriceNil() {
	o.PurchasePrice.Set(nil)
}

// UnsetPurchasePrice ensures that no value is present for PurchasePrice, not even an explicit nil
func (o *EquipmentDto) UnsetPurchasePrice() {
	o.PurchasePrice.Unset()
}

// GetBillingType returns the BillingType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetBillingType() string {
	if o == nil || IsNil(o.BillingType.Get()) {
		var ret string
		return ret
	}
	return *o.BillingType.Get()
}

// GetBillingTypeOk returns a tuple with the BillingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetBillingTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BillingType.Get(), o.BillingType.IsSet()
}

// HasBillingType returns a boolean if a field has been set.
func (o *EquipmentDto) HasBillingType() bool {
	if o != nil && o.BillingType.IsSet() {
		return true
	}

	return false
}

// SetBillingType gets a reference to the given NullableString and assigns it to the BillingType field.
func (o *EquipmentDto) SetBillingType(v string) {
	o.BillingType.Set(&v)
}

// SetBillingTypeNil sets the value for BillingType to be an explicit nil
func (o *EquipmentDto) SetBillingTypeNil() {
	o.BillingType.Set(nil)
}

// UnsetBillingType ensures that no value is present for BillingType, not even an explicit nil
func (o *EquipmentDto) UnsetBillingType() {
	o.BillingType.Unset()
}

// GetBillingTypeName returns the BillingTypeName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetBillingTypeName() string {
	if o == nil || IsNil(o.BillingTypeName.Get()) {
		var ret string
		return ret
	}
	return *o.BillingTypeName.Get()
}

// GetBillingTypeNameOk returns a tuple with the BillingTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetBillingTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BillingTypeName.Get(), o.BillingTypeName.IsSet()
}

// HasBillingTypeName returns a boolean if a field has been set.
func (o *EquipmentDto) HasBillingTypeName() bool {
	if o != nil && o.BillingTypeName.IsSet() {
		return true
	}

	return false
}

// SetBillingTypeName gets a reference to the given NullableString and assigns it to the BillingTypeName field.
func (o *EquipmentDto) SetBillingTypeName(v string) {
	o.BillingTypeName.Set(&v)
}

// SetBillingTypeNameNil sets the value for BillingTypeName to be an explicit nil
func (o *EquipmentDto) SetBillingTypeNameNil() {
	o.BillingTypeName.Set(nil)
}

// UnsetBillingTypeName ensures that no value is present for BillingTypeName, not even an explicit nil
func (o *EquipmentDto) UnsetBillingTypeName() {
	o.BillingTypeName.Unset()
}

// GetBillingCost returns the BillingCost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetBillingCost() float64 {
	if o == nil || IsNil(o.BillingCost.Get()) {
		var ret float64
		return ret
	}
	return *o.BillingCost.Get()
}

// GetBillingCostOk returns a tuple with the BillingCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetBillingCostOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.BillingCost.Get(), o.BillingCost.IsSet()
}

// HasBillingCost returns a boolean if a field has been set.
func (o *EquipmentDto) HasBillingCost() bool {
	if o != nil && o.BillingCost.IsSet() {
		return true
	}

	return false
}

// SetBillingCost gets a reference to the given NullableFloat64 and assigns it to the BillingCost field.
func (o *EquipmentDto) SetBillingCost(v float64) {
	o.BillingCost.Set(&v)
}

// SetBillingCostNil sets the value for BillingCost to be an explicit nil
func (o *EquipmentDto) SetBillingCostNil() {
	o.BillingCost.Set(nil)
}

// UnsetBillingCost ensures that no value is present for BillingCost, not even an explicit nil
func (o *EquipmentDto) UnsetBillingCost() {
	o.BillingCost.Unset()
}

// GetMaxDay returns the MaxDay field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetMaxDay() int32 {
	if o == nil || IsNil(o.MaxDay.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxDay.Get()
}

// GetMaxDayOk returns a tuple with the MaxDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetMaxDayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxDay.Get(), o.MaxDay.IsSet()
}

// HasMaxDay returns a boolean if a field has been set.
func (o *EquipmentDto) HasMaxDay() bool {
	if o != nil && o.MaxDay.IsSet() {
		return true
	}

	return false
}

// SetMaxDay gets a reference to the given NullableInt32 and assigns it to the MaxDay field.
func (o *EquipmentDto) SetMaxDay(v int32) {
	o.MaxDay.Set(&v)
}

// SetMaxDayNil sets the value for MaxDay to be an explicit nil
func (o *EquipmentDto) SetMaxDayNil() {
	o.MaxDay.Set(nil)
}

// UnsetMaxDay ensures that no value is present for MaxDay, not even an explicit nil
func (o *EquipmentDto) UnsetMaxDay() {
	o.MaxDay.Unset()
}

// GetCurrentStaffId returns the CurrentStaffId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetCurrentStaffId() int64 {
	if o == nil || IsNil(o.CurrentStaffId.Get()) {
		var ret int64
		return ret
	}
	return *o.CurrentStaffId.Get()
}

// GetCurrentStaffIdOk returns a tuple with the CurrentStaffId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetCurrentStaffIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentStaffId.Get(), o.CurrentStaffId.IsSet()
}

// HasCurrentStaffId returns a boolean if a field has been set.
func (o *EquipmentDto) HasCurrentStaffId() bool {
	if o != nil && o.CurrentStaffId.IsSet() {
		return true
	}

	return false
}

// SetCurrentStaffId gets a reference to the given NullableInt64 and assigns it to the CurrentStaffId field.
func (o *EquipmentDto) SetCurrentStaffId(v int64) {
	o.CurrentStaffId.Set(&v)
}

// SetCurrentStaffIdNil sets the value for CurrentStaffId to be an explicit nil
func (o *EquipmentDto) SetCurrentStaffIdNil() {
	o.CurrentStaffId.Set(nil)
}

// UnsetCurrentStaffId ensures that no value is present for CurrentStaffId, not even an explicit nil
func (o *EquipmentDto) UnsetCurrentStaffId() {
	o.CurrentStaffId.Unset()
}

// GetCurrentCompanyId returns the CurrentCompanyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetCurrentCompanyId() int64 {
	if o == nil || IsNil(o.CurrentCompanyId.Get()) {
		var ret int64
		return ret
	}
	return *o.CurrentCompanyId.Get()
}

// GetCurrentCompanyIdOk returns a tuple with the CurrentCompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetCurrentCompanyIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentCompanyId.Get(), o.CurrentCompanyId.IsSet()
}

// HasCurrentCompanyId returns a boolean if a field has been set.
func (o *EquipmentDto) HasCurrentCompanyId() bool {
	if o != nil && o.CurrentCompanyId.IsSet() {
		return true
	}

	return false
}

// SetCurrentCompanyId gets a reference to the given NullableInt64 and assigns it to the CurrentCompanyId field.
func (o *EquipmentDto) SetCurrentCompanyId(v int64) {
	o.CurrentCompanyId.Set(&v)
}

// SetCurrentCompanyIdNil sets the value for CurrentCompanyId to be an explicit nil
func (o *EquipmentDto) SetCurrentCompanyIdNil() {
	o.CurrentCompanyId.Set(nil)
}

// UnsetCurrentCompanyId ensures that no value is present for CurrentCompanyId, not even an explicit nil
func (o *EquipmentDto) UnsetCurrentCompanyId() {
	o.CurrentCompanyId.Unset()
}

// GetSource returns the Source field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetSource() string {
	if o == nil || IsNil(o.Source.Get()) {
		var ret string
		return ret
	}
	return *o.Source.Get()
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Source.Get(), o.Source.IsSet()
}

// HasSource returns a boolean if a field has been set.
func (o *EquipmentDto) HasSource() bool {
	if o != nil && o.Source.IsSet() {
		return true
	}

	return false
}

// SetSource gets a reference to the given NullableString and assigns it to the Source field.
func (o *EquipmentDto) SetSource(v string) {
	o.Source.Set(&v)
}

// SetSourceNil sets the value for Source to be an explicit nil
func (o *EquipmentDto) SetSourceNil() {
	o.Source.Set(nil)
}

// UnsetSource ensures that no value is present for Source, not even an explicit nil
func (o *EquipmentDto) UnsetSource() {
	o.Source.Unset()
}

// GetBarcode returns the Barcode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EquipmentDto) GetBarcode() string {
	if o == nil || IsNil(o.Barcode.Get()) {
		var ret string
		return ret
	}
	return *o.Barcode.Get()
}

// GetBarcodeOk returns a tuple with the Barcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EquipmentDto) GetBarcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Barcode.Get(), o.Barcode.IsSet()
}

// HasBarcode returns a boolean if a field has been set.
func (o *EquipmentDto) HasBarcode() bool {
	if o != nil && o.Barcode.IsSet() {
		return true
	}

	return false
}

// SetBarcode gets a reference to the given NullableString and assigns it to the Barcode field.
func (o *EquipmentDto) SetBarcode(v string) {
	o.Barcode.Set(&v)
}

// SetBarcodeNil sets the value for Barcode to be an explicit nil
func (o *EquipmentDto) SetBarcodeNil() {
	o.Barcode.Set(nil)
}

// UnsetBarcode ensures that no value is present for Barcode, not even an explicit nil
func (o *EquipmentDto) UnsetBarcode() {
	o.Barcode.Unset()
}

func (o EquipmentDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EquipmentDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["equipmentCustomId"] = o.EquipmentCustomId
	toSerialize["equipmentTypeId"] = o.EquipmentTypeId
	if o.EquipmentTypeName.IsSet() {
		toSerialize["equipmentTypeName"] = o.EquipmentTypeName.Get()
	}
	toSerialize["status"] = o.Status
	if o.StatusName.IsSet() {
		toSerialize["statusName"] = o.StatusName.Get()
	}
	toSerialize["locationId"] = o.LocationId
	if o.LocationName.IsSet() {
		toSerialize["locationName"] = o.LocationName.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["projectId"] = o.ProjectId.Get()
	}
	if o.ProjectName.IsSet() {
		toSerialize["projectName"] = o.ProjectName.Get()
	}
	if o.PurchaseDate.IsSet() {
		toSerialize["purchaseDate"] = o.PurchaseDate.Get()
	}
	if o.Manufacturer.IsSet() {
		toSerialize["manufacturer"] = o.Manufacturer.Get()
	}
	if o.SerialNo.IsSet() {
		toSerialize["serialNo"] = o.SerialNo.Get()
	}
	if o.EquipmentModel.IsSet() {
		toSerialize["equipmentModel"] = o.EquipmentModel.Get()
	}
	if o.PurchasePrice.IsSet() {
		toSerialize["purchasePrice"] = o.PurchasePrice.Get()
	}
	if o.BillingType.IsSet() {
		toSerialize["billingType"] = o.BillingType.Get()
	}
	if o.BillingTypeName.IsSet() {
		toSerialize["billingTypeName"] = o.BillingTypeName.Get()
	}
	if o.BillingCost.IsSet() {
		toSerialize["billingCost"] = o.BillingCost.Get()
	}
	if o.MaxDay.IsSet() {
		toSerialize["maxDay"] = o.MaxDay.Get()
	}
	if o.CurrentStaffId.IsSet() {
		toSerialize["currentStaffId"] = o.CurrentStaffId.Get()
	}
	if o.CurrentCompanyId.IsSet() {
		toSerialize["currentCompanyId"] = o.CurrentCompanyId.Get()
	}
	if o.Source.IsSet() {
		toSerialize["source"] = o.Source.Get()
	}
	if o.Barcode.IsSet() {
		toSerialize["barcode"] = o.Barcode.Get()
	}
	return toSerialize, nil
}

func (o *EquipmentDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"equipmentCustomId",
		"equipmentTypeId",
		"status",
		"locationId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEquipmentDto := _EquipmentDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEquipmentDto)

	if err != nil {
		return err
	}

	*o = EquipmentDto(varEquipmentDto)

	return err
}

type NullableEquipmentDto struct {
	value *EquipmentDto
	isSet bool
}

func (v NullableEquipmentDto) Get() *EquipmentDto {
	return v.value
}

func (v *NullableEquipmentDto) Set(val *EquipmentDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEquipmentDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEquipmentDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEquipmentDto(val *EquipmentDto) *NullableEquipmentDto {
	return &NullableEquipmentDto{value: val, isSet: true}
}

func (v NullableEquipmentDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEquipmentDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
