/*
Albi Api - v5

This Api will be responsible for overall data distribution and authorization.

API version: v5
Contact: support@albiware.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
)

// checks if the IFileData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IFileData{}

// IFileData struct for IFileData
type IFileData struct {
	ContentType NullableString `json:"contentType,omitempty"`
	Length      *int64         `json:"length,omitempty"`
	Name        NullableString `json:"name,omitempty"`
	FileName    NullableString `json:"fileName,omitempty"`
	Contents    NullableString `json:"contents,omitempty"`
}

// NewIFileData instantiates a new IFileData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIFileData() *IFileData {
	this := IFileData{}
	return &this
}

// NewIFileDataWithDefaults instantiates a new IFileData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIFileDataWithDefaults() *IFileData {
	this := IFileData{}
	return &this
}

// GetContentType returns the ContentType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IFileData) GetContentType() string {
	if o == nil || IsNil(o.ContentType.Get()) {
		var ret string
		return ret
	}
	return *o.ContentType.Get()
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IFileData) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContentType.Get(), o.ContentType.IsSet()
}

// HasContentType returns a boolean if a field has been set.
func (o *IFileData) HasContentType() bool {
	if o != nil && o.ContentType.IsSet() {
		return true
	}

	return false
}

// SetContentType gets a reference to the given NullableString and assigns it to the ContentType field.
func (o *IFileData) SetContentType(v string) {
	o.ContentType.Set(&v)
}

// SetContentTypeNil sets the value for ContentType to be an explicit nil
func (o *IFileData) SetContentTypeNil() {
	o.ContentType.Set(nil)
}

// UnsetContentType ensures that no value is present for ContentType, not even an explicit nil
func (o *IFileData) UnsetContentType() {
	o.ContentType.Unset()
}

// GetLength returns the Length field value if set, zero value otherwise.
func (o *IFileData) GetLength() int64 {
	if o == nil || IsNil(o.Length) {
		var ret int64
		return ret
	}
	return *o.Length
}

// GetLengthOk returns a tuple with the Length field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IFileData) GetLengthOk() (*int64, bool) {
	if o == nil || IsNil(o.Length) {
		return nil, false
	}
	return o.Length, true
}

// HasLength returns a boolean if a field has been set.
func (o *IFileData) HasLength() bool {
	if o != nil && !IsNil(o.Length) {
		return true
	}

	return false
}

// SetLength gets a reference to the given int64 and assigns it to the Length field.
func (o *IFileData) SetLength(v int64) {
	o.Length = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IFileData) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IFileData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *IFileData) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *IFileData) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *IFileData) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *IFileData) UnsetName() {
	o.Name.Unset()
}

// GetFileName returns the FileName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IFileData) GetFileName() string {
	if o == nil || IsNil(o.FileName.Get()) {
		var ret string
		return ret
	}
	return *o.FileName.Get()
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IFileData) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FileName.Get(), o.FileName.IsSet()
}

// HasFileName returns a boolean if a field has been set.
func (o *IFileData) HasFileName() bool {
	if o != nil && o.FileName.IsSet() {
		return true
	}

	return false
}

// SetFileName gets a reference to the given NullableString and assigns it to the FileName field.
func (o *IFileData) SetFileName(v string) {
	o.FileName.Set(&v)
}

// SetFileNameNil sets the value for FileName to be an explicit nil
func (o *IFileData) SetFileNameNil() {
	o.FileName.Set(nil)
}

// UnsetFileName ensures that no value is present for FileName, not even an explicit nil
func (o *IFileData) UnsetFileName() {
	o.FileName.Unset()
}

// GetContents returns the Contents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IFileData) GetContents() string {
	if o == nil || IsNil(o.Contents.Get()) {
		var ret string
		return ret
	}
	return *o.Contents.Get()
}

// GetContentsOk returns a tuple with the Contents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IFileData) GetContentsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contents.Get(), o.Contents.IsSet()
}

// HasContents returns a boolean if a field has been set.
func (o *IFileData) HasContents() bool {
	if o != nil && o.Contents.IsSet() {
		return true
	}

	return false
}

// SetContents gets a reference to the given NullableString and assigns it to the Contents field.
func (o *IFileData) SetContents(v string) {
	o.Contents.Set(&v)
}

// SetContentsNil sets the value for Contents to be an explicit nil
func (o *IFileData) SetContentsNil() {
	o.Contents.Set(nil)
}

// UnsetContents ensures that no value is present for Contents, not even an explicit nil
func (o *IFileData) UnsetContents() {
	o.Contents.Unset()
}

func (o IFileData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IFileData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ContentType.IsSet() {
		toSerialize["contentType"] = o.ContentType.Get()
	}
	if !IsNil(o.Length) {
		toSerialize["length"] = o.Length
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.FileName.IsSet() {
		toSerialize["fileName"] = o.FileName.Get()
	}
	if o.Contents.IsSet() {
		toSerialize["contents"] = o.Contents.Get()
	}
	return toSerialize, nil
}

type NullableIFileData struct {
	value *IFileData
	isSet bool
}

func (v NullableIFileData) Get() *IFileData {
	return v.value
}

func (v *NullableIFileData) Set(val *IFileData) {
	v.value = val
	v.isSet = true
}

func (v NullableIFileData) IsSet() bool {
	return v.isSet
}

func (v *NullableIFileData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIFileData(val *IFileData) *NullableIFileData {
	return &NullableIFileData{value: val, isSet: true}
}

func (v NullableIFileData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIFileData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
