/*
Core API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
)

// checks if the CreateWebhook200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWebhook200Response{}

// CreateWebhook200Response struct for CreateWebhook200Response
type CreateWebhook200Response struct {
	Message              *string `json:"message,omitempty"`
	Status               *int32  `json:"status,omitempty"`
	Data                 *int32  `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateWebhook200Response CreateWebhook200Response

// NewCreateWebhook200Response instantiates a new CreateWebhook200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWebhook200Response() *CreateWebhook200Response {
	this := CreateWebhook200Response{}
	var status int32 = 0
	this.Status = &status
	var data int32 = 0
	this.Data = &data
	return &this
}

// NewCreateWebhook200ResponseWithDefaults instantiates a new CreateWebhook200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWebhook200ResponseWithDefaults() *CreateWebhook200Response {
	this := CreateWebhook200Response{}
	var status int32 = 0
	this.Status = &status
	var data int32 = 0
	this.Data = &data
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateWebhook200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWebhook200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateWebhook200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateWebhook200Response) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateWebhook200Response) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWebhook200Response) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateWebhook200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *CreateWebhook200Response) SetStatus(v int32) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateWebhook200Response) GetData() int32 {
	if o == nil || IsNil(o.Data) {
		var ret int32
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWebhook200Response) GetDataOk() (*int32, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateWebhook200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given int32 and assigns it to the Data field.
func (o *CreateWebhook200Response) SetData(v int32) {
	o.Data = &v
}

func (o CreateWebhook200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWebhook200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateWebhook200Response) UnmarshalJSON(data []byte) (err error) {
	varCreateWebhook200Response := _CreateWebhook200Response{}

	err = json.Unmarshal(data, &varCreateWebhook200Response)

	if err != nil {
		return err
	}

	*o = CreateWebhook200Response(varCreateWebhook200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "status")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateWebhook200Response struct {
	value *CreateWebhook200Response
	isSet bool
}

func (v NullableCreateWebhook200Response) Get() *CreateWebhook200Response {
	return v.value
}

func (v *NullableCreateWebhook200Response) Set(val *CreateWebhook200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWebhook200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWebhook200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWebhook200Response(val *CreateWebhook200Response) *NullableCreateWebhook200Response {
	return &NullableCreateWebhook200Response{value: val, isSet: true}
}

func (v NullableCreateWebhook200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWebhook200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
