/*
Core API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateProjectRequestProjectReferrer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProjectRequestProjectReferrer{}

// CreateProjectRequestProjectReferrer struct for CreateProjectRequestProjectReferrer
type CreateProjectRequestProjectReferrer struct {
	// existing or new
	Type                     string   `json:"type"`
	ExistingSourceId         *int32   `json:"existingSourceId,omitempty"`
	ExistingReferralSourceId *int32   `json:"existingReferralSourceId,omitempty"`
	ExistingSalespersonId    *int32   `json:"existingSalespersonId,omitempty"`
	OrganizationName         *string  `json:"organizationName,omitempty"`
	FirstName                *string  `json:"firstName,omitempty"`
	LastName                 *string  `json:"lastName,omitempty"`
	Email                    *string  `json:"email,omitempty"`
	PhoneNumber              *string  `json:"phoneNumber,omitempty"`
	UseOrganizationAddress   *bool    `json:"useOrganizationAddress,omitempty"`
	OrganizationId           *int32   `json:"organizationId,omitempty"`
	ReferralSourceId         *int32   `json:"referralSourceId,omitempty"`
	ParentOrganizationId     *int32   `json:"parentOrganizationId,omitempty"`
	SalespersonId            *int32   `json:"salespersonId,omitempty"`
	Address1                 *string  `json:"address1,omitempty"`
	Address2                 *string  `json:"address2,omitempty"`
	City                     *string  `json:"city,omitempty"`
	State                    *string  `json:"state,omitempty"`
	ZipCode                  *string  `json:"zipCode,omitempty"`
	Country                  *string  `json:"country,omitempty"`
	Latitude                 *float64 `json:"latitude,omitempty"`
	Longitude                *float64 `json:"longitude,omitempty"`
	Sandbox                  *string  `json:"sandbox,omitempty"`
	AdditionalProperties     map[string]interface{}
}

type _CreateProjectRequestProjectReferrer CreateProjectRequestProjectReferrer

// NewCreateProjectRequestProjectReferrer instantiates a new CreateProjectRequestProjectReferrer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProjectRequestProjectReferrer(type_ string) *CreateProjectRequestProjectReferrer {
	this := CreateProjectRequestProjectReferrer{}
	this.Type = type_
	return &this
}

// NewCreateProjectRequestProjectReferrerWithDefaults instantiates a new CreateProjectRequestProjectReferrer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProjectRequestProjectReferrerWithDefaults() *CreateProjectRequestProjectReferrer {
	this := CreateProjectRequestProjectReferrer{}
	return &this
}

// GetType returns the Type field value
func (o *CreateProjectRequestProjectReferrer) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateProjectRequestProjectReferrer) SetType(v string) {
	o.Type = v
}

// GetExistingSourceId returns the ExistingSourceId field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetExistingSourceId() int32 {
	if o == nil || IsNil(o.ExistingSourceId) {
		var ret int32
		return ret
	}
	return *o.ExistingSourceId
}

// GetExistingSourceIdOk returns a tuple with the ExistingSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetExistingSourceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ExistingSourceId) {
		return nil, false
	}
	return o.ExistingSourceId, true
}

// HasExistingSourceId returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasExistingSourceId() bool {
	if o != nil && !IsNil(o.ExistingSourceId) {
		return true
	}

	return false
}

// SetExistingSourceId gets a reference to the given int32 and assigns it to the ExistingSourceId field.
func (o *CreateProjectRequestProjectReferrer) SetExistingSourceId(v int32) {
	o.ExistingSourceId = &v
}

// GetExistingReferralSourceId returns the ExistingReferralSourceId field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetExistingReferralSourceId() int32 {
	if o == nil || IsNil(o.ExistingReferralSourceId) {
		var ret int32
		return ret
	}
	return *o.ExistingReferralSourceId
}

// GetExistingReferralSourceIdOk returns a tuple with the ExistingReferralSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetExistingReferralSourceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ExistingReferralSourceId) {
		return nil, false
	}
	return o.ExistingReferralSourceId, true
}

// HasExistingReferralSourceId returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasExistingReferralSourceId() bool {
	if o != nil && !IsNil(o.ExistingReferralSourceId) {
		return true
	}

	return false
}

// SetExistingReferralSourceId gets a reference to the given int32 and assigns it to the ExistingReferralSourceId field.
func (o *CreateProjectRequestProjectReferrer) SetExistingReferralSourceId(v int32) {
	o.ExistingReferralSourceId = &v
}

// GetExistingSalespersonId returns the ExistingSalespersonId field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetExistingSalespersonId() int32 {
	if o == nil || IsNil(o.ExistingSalespersonId) {
		var ret int32
		return ret
	}
	return *o.ExistingSalespersonId
}

// GetExistingSalespersonIdOk returns a tuple with the ExistingSalespersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetExistingSalespersonIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ExistingSalespersonId) {
		return nil, false
	}
	return o.ExistingSalespersonId, true
}

// HasExistingSalespersonId returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasExistingSalespersonId() bool {
	if o != nil && !IsNil(o.ExistingSalespersonId) {
		return true
	}

	return false
}

// SetExistingSalespersonId gets a reference to the given int32 and assigns it to the ExistingSalespersonId field.
func (o *CreateProjectRequestProjectReferrer) SetExistingSalespersonId(v int32) {
	o.ExistingSalespersonId = &v
}

// GetOrganizationName returns the OrganizationName field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetOrganizationName() string {
	if o == nil || IsNil(o.OrganizationName) {
		var ret string
		return ret
	}
	return *o.OrganizationName
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetOrganizationNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationName) {
		return nil, false
	}
	return o.OrganizationName, true
}

// HasOrganizationName returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasOrganizationName() bool {
	if o != nil && !IsNil(o.OrganizationName) {
		return true
	}

	return false
}

// SetOrganizationName gets a reference to the given string and assigns it to the OrganizationName field.
func (o *CreateProjectRequestProjectReferrer) SetOrganizationName(v string) {
	o.OrganizationName = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *CreateProjectRequestProjectReferrer) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *CreateProjectRequestProjectReferrer) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CreateProjectRequestProjectReferrer) SetEmail(v string) {
	o.Email = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *CreateProjectRequestProjectReferrer) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetUseOrganizationAddress returns the UseOrganizationAddress field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetUseOrganizationAddress() bool {
	if o == nil || IsNil(o.UseOrganizationAddress) {
		var ret bool
		return ret
	}
	return *o.UseOrganizationAddress
}

// GetUseOrganizationAddressOk returns a tuple with the UseOrganizationAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetUseOrganizationAddressOk() (*bool, bool) {
	if o == nil || IsNil(o.UseOrganizationAddress) {
		return nil, false
	}
	return o.UseOrganizationAddress, true
}

// HasUseOrganizationAddress returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasUseOrganizationAddress() bool {
	if o != nil && !IsNil(o.UseOrganizationAddress) {
		return true
	}

	return false
}

// SetUseOrganizationAddress gets a reference to the given bool and assigns it to the UseOrganizationAddress field.
func (o *CreateProjectRequestProjectReferrer) SetUseOrganizationAddress(v bool) {
	o.UseOrganizationAddress = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetOrganizationId() int32 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int32
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetOrganizationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int32 and assigns it to the OrganizationId field.
func (o *CreateProjectRequestProjectReferrer) SetOrganizationId(v int32) {
	o.OrganizationId = &v
}

// GetReferralSourceId returns the ReferralSourceId field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetReferralSourceId() int32 {
	if o == nil || IsNil(o.ReferralSourceId) {
		var ret int32
		return ret
	}
	return *o.ReferralSourceId
}

// GetReferralSourceIdOk returns a tuple with the ReferralSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetReferralSourceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ReferralSourceId) {
		return nil, false
	}
	return o.ReferralSourceId, true
}

// HasReferralSourceId returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasReferralSourceId() bool {
	if o != nil && !IsNil(o.ReferralSourceId) {
		return true
	}

	return false
}

// SetReferralSourceId gets a reference to the given int32 and assigns it to the ReferralSourceId field.
func (o *CreateProjectRequestProjectReferrer) SetReferralSourceId(v int32) {
	o.ReferralSourceId = &v
}

// GetParentOrganizationId returns the ParentOrganizationId field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetParentOrganizationId() int32 {
	if o == nil || IsNil(o.ParentOrganizationId) {
		var ret int32
		return ret
	}
	return *o.ParentOrganizationId
}

// GetParentOrganizationIdOk returns a tuple with the ParentOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetParentOrganizationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ParentOrganizationId) {
		return nil, false
	}
	return o.ParentOrganizationId, true
}

// HasParentOrganizationId returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasParentOrganizationId() bool {
	if o != nil && !IsNil(o.ParentOrganizationId) {
		return true
	}

	return false
}

// SetParentOrganizationId gets a reference to the given int32 and assigns it to the ParentOrganizationId field.
func (o *CreateProjectRequestProjectReferrer) SetParentOrganizationId(v int32) {
	o.ParentOrganizationId = &v
}

// GetSalespersonId returns the SalespersonId field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetSalespersonId() int32 {
	if o == nil || IsNil(o.SalespersonId) {
		var ret int32
		return ret
	}
	return *o.SalespersonId
}

// GetSalespersonIdOk returns a tuple with the SalespersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetSalespersonIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SalespersonId) {
		return nil, false
	}
	return o.SalespersonId, true
}

// HasSalespersonId returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasSalespersonId() bool {
	if o != nil && !IsNil(o.SalespersonId) {
		return true
	}

	return false
}

// SetSalespersonId gets a reference to the given int32 and assigns it to the SalespersonId field.
func (o *CreateProjectRequestProjectReferrer) SetSalespersonId(v int32) {
	o.SalespersonId = &v
}

// GetAddress1 returns the Address1 field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetAddress1() string {
	if o == nil || IsNil(o.Address1) {
		var ret string
		return ret
	}
	return *o.Address1
}

// GetAddress1Ok returns a tuple with the Address1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetAddress1Ok() (*string, bool) {
	if o == nil || IsNil(o.Address1) {
		return nil, false
	}
	return o.Address1, true
}

// HasAddress1 returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasAddress1() bool {
	if o != nil && !IsNil(o.Address1) {
		return true
	}

	return false
}

// SetAddress1 gets a reference to the given string and assigns it to the Address1 field.
func (o *CreateProjectRequestProjectReferrer) SetAddress1(v string) {
	o.Address1 = &v
}

// GetAddress2 returns the Address2 field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetAddress2() string {
	if o == nil || IsNil(o.Address2) {
		var ret string
		return ret
	}
	return *o.Address2
}

// GetAddress2Ok returns a tuple with the Address2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetAddress2Ok() (*string, bool) {
	if o == nil || IsNil(o.Address2) {
		return nil, false
	}
	return o.Address2, true
}

// HasAddress2 returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasAddress2() bool {
	if o != nil && !IsNil(o.Address2) {
		return true
	}

	return false
}

// SetAddress2 gets a reference to the given string and assigns it to the Address2 field.
func (o *CreateProjectRequestProjectReferrer) SetAddress2(v string) {
	o.Address2 = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *CreateProjectRequestProjectReferrer) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *CreateProjectRequestProjectReferrer) SetState(v string) {
	o.State = &v
}

// GetZipCode returns the ZipCode field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetZipCode() string {
	if o == nil || IsNil(o.ZipCode) {
		var ret string
		return ret
	}
	return *o.ZipCode
}

// GetZipCodeOk returns a tuple with the ZipCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetZipCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ZipCode) {
		return nil, false
	}
	return o.ZipCode, true
}

// HasZipCode returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasZipCode() bool {
	if o != nil && !IsNil(o.ZipCode) {
		return true
	}

	return false
}

// SetZipCode gets a reference to the given string and assigns it to the ZipCode field.
func (o *CreateProjectRequestProjectReferrer) SetZipCode(v string) {
	o.ZipCode = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *CreateProjectRequestProjectReferrer) SetCountry(v string) {
	o.Country = &v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *CreateProjectRequestProjectReferrer) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *CreateProjectRequestProjectReferrer) SetLongitude(v float64) {
	o.Longitude = &v
}

// GetSandbox returns the Sandbox field value if set, zero value otherwise.
func (o *CreateProjectRequestProjectReferrer) GetSandbox() string {
	if o == nil || IsNil(o.Sandbox) {
		var ret string
		return ret
	}
	return *o.Sandbox
}

// GetSandboxOk returns a tuple with the Sandbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectRequestProjectReferrer) GetSandboxOk() (*string, bool) {
	if o == nil || IsNil(o.Sandbox) {
		return nil, false
	}
	return o.Sandbox, true
}

// HasSandbox returns a boolean if a field has been set.
func (o *CreateProjectRequestProjectReferrer) HasSandbox() bool {
	if o != nil && !IsNil(o.Sandbox) {
		return true
	}

	return false
}

// SetSandbox gets a reference to the given string and assigns it to the Sandbox field.
func (o *CreateProjectRequestProjectReferrer) SetSandbox(v string) {
	o.Sandbox = &v
}

func (o CreateProjectRequestProjectReferrer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProjectRequestProjectReferrer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.ExistingSourceId) {
		toSerialize["existingSourceId"] = o.ExistingSourceId
	}
	if !IsNil(o.ExistingReferralSourceId) {
		toSerialize["existingReferralSourceId"] = o.ExistingReferralSourceId
	}
	if !IsNil(o.ExistingSalespersonId) {
		toSerialize["existingSalespersonId"] = o.ExistingSalespersonId
	}
	if !IsNil(o.OrganizationName) {
		toSerialize["organizationName"] = o.OrganizationName
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if !IsNil(o.UseOrganizationAddress) {
		toSerialize["useOrganizationAddress"] = o.UseOrganizationAddress
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.ReferralSourceId) {
		toSerialize["referralSourceId"] = o.ReferralSourceId
	}
	if !IsNil(o.ParentOrganizationId) {
		toSerialize["parentOrganizationId"] = o.ParentOrganizationId
	}
	if !IsNil(o.SalespersonId) {
		toSerialize["salespersonId"] = o.SalespersonId
	}
	if !IsNil(o.Address1) {
		toSerialize["address1"] = o.Address1
	}
	if !IsNil(o.Address2) {
		toSerialize["address2"] = o.Address2
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.ZipCode) {
		toSerialize["zipCode"] = o.ZipCode
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	if !IsNil(o.Sandbox) {
		toSerialize["sandbox"] = o.Sandbox
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateProjectRequestProjectReferrer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProjectRequestProjectReferrer := _CreateProjectRequestProjectReferrer{}

	err = json.Unmarshal(data, &varCreateProjectRequestProjectReferrer)

	if err != nil {
		return err
	}

	*o = CreateProjectRequestProjectReferrer(varCreateProjectRequestProjectReferrer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "existingSourceId")
		delete(additionalProperties, "existingReferralSourceId")
		delete(additionalProperties, "existingSalespersonId")
		delete(additionalProperties, "organizationName")
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "email")
		delete(additionalProperties, "phoneNumber")
		delete(additionalProperties, "useOrganizationAddress")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "referralSourceId")
		delete(additionalProperties, "parentOrganizationId")
		delete(additionalProperties, "salespersonId")
		delete(additionalProperties, "address1")
		delete(additionalProperties, "address2")
		delete(additionalProperties, "city")
		delete(additionalProperties, "state")
		delete(additionalProperties, "zipCode")
		delete(additionalProperties, "country")
		delete(additionalProperties, "latitude")
		delete(additionalProperties, "longitude")
		delete(additionalProperties, "sandbox")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateProjectRequestProjectReferrer struct {
	value *CreateProjectRequestProjectReferrer
	isSet bool
}

func (v NullableCreateProjectRequestProjectReferrer) Get() *CreateProjectRequestProjectReferrer {
	return v.value
}

func (v *NullableCreateProjectRequestProjectReferrer) Set(val *CreateProjectRequestProjectReferrer) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProjectRequestProjectReferrer) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProjectRequestProjectReferrer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProjectRequestProjectReferrer(val *CreateProjectRequestProjectReferrer) *NullableCreateProjectRequestProjectReferrer {
	return &NullableCreateProjectRequestProjectReferrer{value: val, isSet: true}
}

func (v NullableCreateProjectRequestProjectReferrer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProjectRequestProjectReferrer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
