/*
Core API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
)

// checks if the GetProjectExpenseById200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectExpenseById200ResponseDataInner{}

// GetProjectExpenseById200ResponseDataInner struct for GetProjectExpenseById200ResponseDataInner
type GetProjectExpenseById200ResponseDataInner struct {
	Id                     *int32                   `json:"id,omitempty"`
	ProjectId              *int32                   `json:"projectId,omitempty"`
	ExpenseDate            *string                  `json:"expenseDate,omitempty"`
	TransactionType        interface{}              `json:"transactionType,omitempty"`
	Number                 *string                  `json:"number,omitempty"`
	Method                 interface{}              `json:"method,omitempty"`
	Memo                   *string                  `json:"memo,omitempty"`
	PaymentAccount         interface{}              `json:"paymentAccount,omitempty"`
	Total                  *int32                   `json:"total,omitempty"`
	Balance                *int32                   `json:"balance,omitempty"`
	StaffTimesheetId       interface{}              `json:"staffTimesheetId,omitempty"`
	EquipmentProjectId     *int32                   `json:"equipmentProjectId,omitempty"`
	FinancialCRMID         interface{}              `json:"financialCRMID,omitempty"`
	QboSubCustomerId       interface{}              `json:"qboSubCustomerId,omitempty"`
	Subcategory            *string                  `json:"subcategory,omitempty"`
	Payee                  interface{}              `json:"payee,omitempty"`
	Quantity               interface{}              `json:"quantity,omitempty"`
	Cost                   interface{}              `json:"cost,omitempty"`
	Status                 *string                  `json:"status,omitempty"`
	Deleted                *bool                    `json:"deleted,omitempty"`
	QboExpenseAccountId    interface{}              `json:"qboExpenseAccountId,omitempty"`
	QboPaymentAccountId    interface{}              `json:"qboPaymentAccountId,omitempty"`
	SyncToken              interface{}              `json:"syncToken,omitempty"`
	CreatedAt              *string                  `json:"createdAt,omitempty"`
	CreatedBy              *string                  `json:"createdBy,omitempty"`
	CreatedById            interface{}              `json:"createdById,omitempty"`
	UpdatedAt              interface{}              `json:"updatedAt,omitempty"`
	UpdatedBy              interface{}              `json:"updatedBy,omitempty"`
	ProjectExpenseItems    []map[string]interface{} `json:"projectExpenseItems,omitempty"`
	ExpenseSubcategories   interface{}              `json:"expenseSubcategories,omitempty"`
	ExpenseStaffTimesheets interface{}              `json:"expenseStaffTimesheets,omitempty"`
	ExpenseEquipments      interface{}              `json:"expenseEquipments,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _GetProjectExpenseById200ResponseDataInner GetProjectExpenseById200ResponseDataInner

// NewGetProjectExpenseById200ResponseDataInner instantiates a new GetProjectExpenseById200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectExpenseById200ResponseDataInner() *GetProjectExpenseById200ResponseDataInner {
	this := GetProjectExpenseById200ResponseDataInner{}
	var id int32 = 0
	this.Id = &id
	var projectId int32 = 0
	this.ProjectId = &projectId
	var total int32 = 0
	this.Total = &total
	var balance int32 = 0
	this.Balance = &balance
	var equipmentProjectId int32 = 0
	this.EquipmentProjectId = &equipmentProjectId
	var deleted bool = true
	this.Deleted = &deleted
	return &this
}

// NewGetProjectExpenseById200ResponseDataInnerWithDefaults instantiates a new GetProjectExpenseById200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectExpenseById200ResponseDataInnerWithDefaults() *GetProjectExpenseById200ResponseDataInner {
	this := GetProjectExpenseById200ResponseDataInner{}
	var id int32 = 0
	this.Id = &id
	var projectId int32 = 0
	this.ProjectId = &projectId
	var total int32 = 0
	this.Total = &total
	var balance int32 = 0
	this.Balance = &balance
	var equipmentProjectId int32 = 0
	this.EquipmentProjectId = &equipmentProjectId
	var deleted bool = true
	this.Deleted = &deleted
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetProjectExpenseById200ResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *GetProjectExpenseById200ResponseDataInner) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetExpenseDate returns the ExpenseDate field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetExpenseDate() string {
	if o == nil || IsNil(o.ExpenseDate) {
		var ret string
		return ret
	}
	return *o.ExpenseDate
}

// GetExpenseDateOk returns a tuple with the ExpenseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetExpenseDateOk() (*string, bool) {
	if o == nil || IsNil(o.ExpenseDate) {
		return nil, false
	}
	return o.ExpenseDate, true
}

// HasExpenseDate returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasExpenseDate() bool {
	if o != nil && !IsNil(o.ExpenseDate) {
		return true
	}

	return false
}

// SetExpenseDate gets a reference to the given string and assigns it to the ExpenseDate field.
func (o *GetProjectExpenseById200ResponseDataInner) SetExpenseDate(v string) {
	o.ExpenseDate = &v
}

// GetTransactionType returns the TransactionType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetTransactionType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.TransactionType
}

// GetTransactionTypeOk returns a tuple with the TransactionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetTransactionTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.TransactionType) {
		return nil, false
	}
	return &o.TransactionType, true
}

// HasTransactionType returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasTransactionType() bool {
	if o != nil && !IsNil(o.TransactionType) {
		return true
	}

	return false
}

// SetTransactionType gets a reference to the given interface{} and assigns it to the TransactionType field.
func (o *GetProjectExpenseById200ResponseDataInner) SetTransactionType(v interface{}) {
	o.TransactionType = v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetNumber() string {
	if o == nil || IsNil(o.Number) {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetNumberOk() (*string, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *GetProjectExpenseById200ResponseDataInner) SetNumber(v string) {
	o.Number = &v
}

// GetMethod returns the Method field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetMethod() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetMethodOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return &o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given interface{} and assigns it to the Method field.
func (o *GetProjectExpenseById200ResponseDataInner) SetMethod(v interface{}) {
	o.Method = v
}

// GetMemo returns the Memo field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetMemo() string {
	if o == nil || IsNil(o.Memo) {
		var ret string
		return ret
	}
	return *o.Memo
}

// GetMemoOk returns a tuple with the Memo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetMemoOk() (*string, bool) {
	if o == nil || IsNil(o.Memo) {
		return nil, false
	}
	return o.Memo, true
}

// HasMemo returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasMemo() bool {
	if o != nil && !IsNil(o.Memo) {
		return true
	}

	return false
}

// SetMemo gets a reference to the given string and assigns it to the Memo field.
func (o *GetProjectExpenseById200ResponseDataInner) SetMemo(v string) {
	o.Memo = &v
}

// GetPaymentAccount returns the PaymentAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetPaymentAccount() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PaymentAccount
}

// GetPaymentAccountOk returns a tuple with the PaymentAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetPaymentAccountOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PaymentAccount) {
		return nil, false
	}
	return &o.PaymentAccount, true
}

// HasPaymentAccount returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasPaymentAccount() bool {
	if o != nil && !IsNil(o.PaymentAccount) {
		return true
	}

	return false
}

// SetPaymentAccount gets a reference to the given interface{} and assigns it to the PaymentAccount field.
func (o *GetProjectExpenseById200ResponseDataInner) SetPaymentAccount(v interface{}) {
	o.PaymentAccount = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetProjectExpenseById200ResponseDataInner) SetTotal(v int32) {
	o.Total = &v
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetBalance() int32 {
	if o == nil || IsNil(o.Balance) {
		var ret int32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetBalanceOk() (*int32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given int32 and assigns it to the Balance field.
func (o *GetProjectExpenseById200ResponseDataInner) SetBalance(v int32) {
	o.Balance = &v
}

// GetStaffTimesheetId returns the StaffTimesheetId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetStaffTimesheetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.StaffTimesheetId
}

// GetStaffTimesheetIdOk returns a tuple with the StaffTimesheetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetStaffTimesheetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.StaffTimesheetId) {
		return nil, false
	}
	return &o.StaffTimesheetId, true
}

// HasStaffTimesheetId returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasStaffTimesheetId() bool {
	if o != nil && !IsNil(o.StaffTimesheetId) {
		return true
	}

	return false
}

// SetStaffTimesheetId gets a reference to the given interface{} and assigns it to the StaffTimesheetId field.
func (o *GetProjectExpenseById200ResponseDataInner) SetStaffTimesheetId(v interface{}) {
	o.StaffTimesheetId = v
}

// GetEquipmentProjectId returns the EquipmentProjectId field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetEquipmentProjectId() int32 {
	if o == nil || IsNil(o.EquipmentProjectId) {
		var ret int32
		return ret
	}
	return *o.EquipmentProjectId
}

// GetEquipmentProjectIdOk returns a tuple with the EquipmentProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetEquipmentProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.EquipmentProjectId) {
		return nil, false
	}
	return o.EquipmentProjectId, true
}

// HasEquipmentProjectId returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasEquipmentProjectId() bool {
	if o != nil && !IsNil(o.EquipmentProjectId) {
		return true
	}

	return false
}

// SetEquipmentProjectId gets a reference to the given int32 and assigns it to the EquipmentProjectId field.
func (o *GetProjectExpenseById200ResponseDataInner) SetEquipmentProjectId(v int32) {
	o.EquipmentProjectId = &v
}

// GetFinancialCRMID returns the FinancialCRMID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetFinancialCRMID() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.FinancialCRMID
}

// GetFinancialCRMIDOk returns a tuple with the FinancialCRMID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetFinancialCRMIDOk() (*interface{}, bool) {
	if o == nil || IsNil(o.FinancialCRMID) {
		return nil, false
	}
	return &o.FinancialCRMID, true
}

// HasFinancialCRMID returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasFinancialCRMID() bool {
	if o != nil && !IsNil(o.FinancialCRMID) {
		return true
	}

	return false
}

// SetFinancialCRMID gets a reference to the given interface{} and assigns it to the FinancialCRMID field.
func (o *GetProjectExpenseById200ResponseDataInner) SetFinancialCRMID(v interface{}) {
	o.FinancialCRMID = v
}

// GetQboSubCustomerId returns the QboSubCustomerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetQboSubCustomerId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.QboSubCustomerId
}

// GetQboSubCustomerIdOk returns a tuple with the QboSubCustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetQboSubCustomerIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.QboSubCustomerId) {
		return nil, false
	}
	return &o.QboSubCustomerId, true
}

// HasQboSubCustomerId returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasQboSubCustomerId() bool {
	if o != nil && !IsNil(o.QboSubCustomerId) {
		return true
	}

	return false
}

// SetQboSubCustomerId gets a reference to the given interface{} and assigns it to the QboSubCustomerId field.
func (o *GetProjectExpenseById200ResponseDataInner) SetQboSubCustomerId(v interface{}) {
	o.QboSubCustomerId = v
}

// GetSubcategory returns the Subcategory field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetSubcategory() string {
	if o == nil || IsNil(o.Subcategory) {
		var ret string
		return ret
	}
	return *o.Subcategory
}

// GetSubcategoryOk returns a tuple with the Subcategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetSubcategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Subcategory) {
		return nil, false
	}
	return o.Subcategory, true
}

// HasSubcategory returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasSubcategory() bool {
	if o != nil && !IsNil(o.Subcategory) {
		return true
	}

	return false
}

// SetSubcategory gets a reference to the given string and assigns it to the Subcategory field.
func (o *GetProjectExpenseById200ResponseDataInner) SetSubcategory(v string) {
	o.Subcategory = &v
}

// GetPayee returns the Payee field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetPayee() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Payee
}

// GetPayeeOk returns a tuple with the Payee field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetPayeeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Payee) {
		return nil, false
	}
	return &o.Payee, true
}

// HasPayee returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasPayee() bool {
	if o != nil && !IsNil(o.Payee) {
		return true
	}

	return false
}

// SetPayee gets a reference to the given interface{} and assigns it to the Payee field.
func (o *GetProjectExpenseById200ResponseDataInner) SetPayee(v interface{}) {
	o.Payee = v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetQuantity() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetQuantityOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return &o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given interface{} and assigns it to the Quantity field.
func (o *GetProjectExpenseById200ResponseDataInner) SetQuantity(v interface{}) {
	o.Quantity = v
}

// GetCost returns the Cost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetCost() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetCostOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Cost) {
		return nil, false
	}
	return &o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasCost() bool {
	if o != nil && !IsNil(o.Cost) {
		return true
	}

	return false
}

// SetCost gets a reference to the given interface{} and assigns it to the Cost field.
func (o *GetProjectExpenseById200ResponseDataInner) SetCost(v interface{}) {
	o.Cost = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetProjectExpenseById200ResponseDataInner) SetStatus(v string) {
	o.Status = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *GetProjectExpenseById200ResponseDataInner) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetQboExpenseAccountId returns the QboExpenseAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetQboExpenseAccountId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.QboExpenseAccountId
}

// GetQboExpenseAccountIdOk returns a tuple with the QboExpenseAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetQboExpenseAccountIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.QboExpenseAccountId) {
		return nil, false
	}
	return &o.QboExpenseAccountId, true
}

// HasQboExpenseAccountId returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasQboExpenseAccountId() bool {
	if o != nil && !IsNil(o.QboExpenseAccountId) {
		return true
	}

	return false
}

// SetQboExpenseAccountId gets a reference to the given interface{} and assigns it to the QboExpenseAccountId field.
func (o *GetProjectExpenseById200ResponseDataInner) SetQboExpenseAccountId(v interface{}) {
	o.QboExpenseAccountId = v
}

// GetQboPaymentAccountId returns the QboPaymentAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetQboPaymentAccountId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.QboPaymentAccountId
}

// GetQboPaymentAccountIdOk returns a tuple with the QboPaymentAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetQboPaymentAccountIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.QboPaymentAccountId) {
		return nil, false
	}
	return &o.QboPaymentAccountId, true
}

// HasQboPaymentAccountId returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasQboPaymentAccountId() bool {
	if o != nil && !IsNil(o.QboPaymentAccountId) {
		return true
	}

	return false
}

// SetQboPaymentAccountId gets a reference to the given interface{} and assigns it to the QboPaymentAccountId field.
func (o *GetProjectExpenseById200ResponseDataInner) SetQboPaymentAccountId(v interface{}) {
	o.QboPaymentAccountId = v
}

// GetSyncToken returns the SyncToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetSyncToken() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SyncToken
}

// GetSyncTokenOk returns a tuple with the SyncToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetSyncTokenOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SyncToken) {
		return nil, false
	}
	return &o.SyncToken, true
}

// HasSyncToken returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasSyncToken() bool {
	if o != nil && !IsNil(o.SyncToken) {
		return true
	}

	return false
}

// SetSyncToken gets a reference to the given interface{} and assigns it to the SyncToken field.
func (o *GetProjectExpenseById200ResponseDataInner) SetSyncToken(v interface{}) {
	o.SyncToken = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetProjectExpenseById200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *GetProjectExpenseById200ResponseDataInner) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetCreatedById returns the CreatedById field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetCreatedById() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CreatedById
}

// GetCreatedByIdOk returns a tuple with the CreatedById field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetCreatedByIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CreatedById) {
		return nil, false
	}
	return &o.CreatedById, true
}

// HasCreatedById returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasCreatedById() bool {
	if o != nil && !IsNil(o.CreatedById) {
		return true
	}

	return false
}

// SetCreatedById gets a reference to the given interface{} and assigns it to the CreatedById field.
func (o *GetProjectExpenseById200ResponseDataInner) SetCreatedById(v interface{}) {
	o.CreatedById = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetUpdatedAt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetUpdatedAtOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given interface{} and assigns it to the UpdatedAt field.
func (o *GetProjectExpenseById200ResponseDataInner) SetUpdatedAt(v interface{}) {
	o.UpdatedAt = v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetUpdatedBy() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetUpdatedByOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return &o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given interface{} and assigns it to the UpdatedBy field.
func (o *GetProjectExpenseById200ResponseDataInner) SetUpdatedBy(v interface{}) {
	o.UpdatedBy = v
}

// GetProjectExpenseItems returns the ProjectExpenseItems field value if set, zero value otherwise.
func (o *GetProjectExpenseById200ResponseDataInner) GetProjectExpenseItems() []map[string]interface{} {
	if o == nil || IsNil(o.ProjectExpenseItems) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ProjectExpenseItems
}

// GetProjectExpenseItemsOk returns a tuple with the ProjectExpenseItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectExpenseById200ResponseDataInner) GetProjectExpenseItemsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ProjectExpenseItems) {
		return nil, false
	}
	return o.ProjectExpenseItems, true
}

// HasProjectExpenseItems returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasProjectExpenseItems() bool {
	if o != nil && !IsNil(o.ProjectExpenseItems) {
		return true
	}

	return false
}

// SetProjectExpenseItems gets a reference to the given []map[string]interface{} and assigns it to the ProjectExpenseItems field.
func (o *GetProjectExpenseById200ResponseDataInner) SetProjectExpenseItems(v []map[string]interface{}) {
	o.ProjectExpenseItems = v
}

// GetExpenseSubcategories returns the ExpenseSubcategories field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetExpenseSubcategories() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ExpenseSubcategories
}

// GetExpenseSubcategoriesOk returns a tuple with the ExpenseSubcategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetExpenseSubcategoriesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ExpenseSubcategories) {
		return nil, false
	}
	return &o.ExpenseSubcategories, true
}

// HasExpenseSubcategories returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasExpenseSubcategories() bool {
	if o != nil && !IsNil(o.ExpenseSubcategories) {
		return true
	}

	return false
}

// SetExpenseSubcategories gets a reference to the given interface{} and assigns it to the ExpenseSubcategories field.
func (o *GetProjectExpenseById200ResponseDataInner) SetExpenseSubcategories(v interface{}) {
	o.ExpenseSubcategories = v
}

// GetExpenseStaffTimesheets returns the ExpenseStaffTimesheets field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetExpenseStaffTimesheets() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ExpenseStaffTimesheets
}

// GetExpenseStaffTimesheetsOk returns a tuple with the ExpenseStaffTimesheets field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetExpenseStaffTimesheetsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ExpenseStaffTimesheets) {
		return nil, false
	}
	return &o.ExpenseStaffTimesheets, true
}

// HasExpenseStaffTimesheets returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasExpenseStaffTimesheets() bool {
	if o != nil && !IsNil(o.ExpenseStaffTimesheets) {
		return true
	}

	return false
}

// SetExpenseStaffTimesheets gets a reference to the given interface{} and assigns it to the ExpenseStaffTimesheets field.
func (o *GetProjectExpenseById200ResponseDataInner) SetExpenseStaffTimesheets(v interface{}) {
	o.ExpenseStaffTimesheets = v
}

// GetExpenseEquipments returns the ExpenseEquipments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectExpenseById200ResponseDataInner) GetExpenseEquipments() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ExpenseEquipments
}

// GetExpenseEquipmentsOk returns a tuple with the ExpenseEquipments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectExpenseById200ResponseDataInner) GetExpenseEquipmentsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ExpenseEquipments) {
		return nil, false
	}
	return &o.ExpenseEquipments, true
}

// HasExpenseEquipments returns a boolean if a field has been set.
func (o *GetProjectExpenseById200ResponseDataInner) HasExpenseEquipments() bool {
	if o != nil && !IsNil(o.ExpenseEquipments) {
		return true
	}

	return false
}

// SetExpenseEquipments gets a reference to the given interface{} and assigns it to the ExpenseEquipments field.
func (o *GetProjectExpenseById200ResponseDataInner) SetExpenseEquipments(v interface{}) {
	o.ExpenseEquipments = v
}

func (o GetProjectExpenseById200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProjectExpenseById200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	if !IsNil(o.ExpenseDate) {
		toSerialize["expenseDate"] = o.ExpenseDate
	}
	if o.TransactionType != nil {
		toSerialize["transactionType"] = o.TransactionType
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if o.Method != nil {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Memo) {
		toSerialize["memo"] = o.Memo
	}
	if o.PaymentAccount != nil {
		toSerialize["paymentAccount"] = o.PaymentAccount
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if o.StaffTimesheetId != nil {
		toSerialize["staffTimesheetId"] = o.StaffTimesheetId
	}
	if !IsNil(o.EquipmentProjectId) {
		toSerialize["equipmentProjectId"] = o.EquipmentProjectId
	}
	if o.FinancialCRMID != nil {
		toSerialize["financialCRMID"] = o.FinancialCRMID
	}
	if o.QboSubCustomerId != nil {
		toSerialize["qboSubCustomerId"] = o.QboSubCustomerId
	}
	if !IsNil(o.Subcategory) {
		toSerialize["subcategory"] = o.Subcategory
	}
	if o.Payee != nil {
		toSerialize["payee"] = o.Payee
	}
	if o.Quantity != nil {
		toSerialize["quantity"] = o.Quantity
	}
	if o.Cost != nil {
		toSerialize["cost"] = o.Cost
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	if o.QboExpenseAccountId != nil {
		toSerialize["qboExpenseAccountId"] = o.QboExpenseAccountId
	}
	if o.QboPaymentAccountId != nil {
		toSerialize["qboPaymentAccountId"] = o.QboPaymentAccountId
	}
	if o.SyncToken != nil {
		toSerialize["syncToken"] = o.SyncToken
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if o.CreatedById != nil {
		toSerialize["createdById"] = o.CreatedById
	}
	if o.UpdatedAt != nil {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.UpdatedBy != nil {
		toSerialize["updatedBy"] = o.UpdatedBy
	}
	if !IsNil(o.ProjectExpenseItems) {
		toSerialize["projectExpenseItems"] = o.ProjectExpenseItems
	}
	if o.ExpenseSubcategories != nil {
		toSerialize["expenseSubcategories"] = o.ExpenseSubcategories
	}
	if o.ExpenseStaffTimesheets != nil {
		toSerialize["expenseStaffTimesheets"] = o.ExpenseStaffTimesheets
	}
	if o.ExpenseEquipments != nil {
		toSerialize["expenseEquipments"] = o.ExpenseEquipments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetProjectExpenseById200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	varGetProjectExpenseById200ResponseDataInner := _GetProjectExpenseById200ResponseDataInner{}

	err = json.Unmarshal(data, &varGetProjectExpenseById200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = GetProjectExpenseById200ResponseDataInner(varGetProjectExpenseById200ResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "projectId")
		delete(additionalProperties, "expenseDate")
		delete(additionalProperties, "transactionType")
		delete(additionalProperties, "number")
		delete(additionalProperties, "method")
		delete(additionalProperties, "memo")
		delete(additionalProperties, "paymentAccount")
		delete(additionalProperties, "total")
		delete(additionalProperties, "balance")
		delete(additionalProperties, "staffTimesheetId")
		delete(additionalProperties, "equipmentProjectId")
		delete(additionalProperties, "financialCRMID")
		delete(additionalProperties, "qboSubCustomerId")
		delete(additionalProperties, "subcategory")
		delete(additionalProperties, "payee")
		delete(additionalProperties, "quantity")
		delete(additionalProperties, "cost")
		delete(additionalProperties, "status")
		delete(additionalProperties, "deleted")
		delete(additionalProperties, "qboExpenseAccountId")
		delete(additionalProperties, "qboPaymentAccountId")
		delete(additionalProperties, "syncToken")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "createdBy")
		delete(additionalProperties, "createdById")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "updatedBy")
		delete(additionalProperties, "projectExpenseItems")
		delete(additionalProperties, "expenseSubcategories")
		delete(additionalProperties, "expenseStaffTimesheets")
		delete(additionalProperties, "expenseEquipments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetProjectExpenseById200ResponseDataInner struct {
	value *GetProjectExpenseById200ResponseDataInner
	isSet bool
}

func (v NullableGetProjectExpenseById200ResponseDataInner) Get() *GetProjectExpenseById200ResponseDataInner {
	return v.value
}

func (v *NullableGetProjectExpenseById200ResponseDataInner) Set(val *GetProjectExpenseById200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectExpenseById200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectExpenseById200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectExpenseById200ResponseDataInner(val *GetProjectExpenseById200ResponseDataInner) *NullableGetProjectExpenseById200ResponseDataInner {
	return &NullableGetProjectExpenseById200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetProjectExpenseById200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectExpenseById200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
