/*
Core API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"encoding/json"
)

// checks if the GetAllContactsCopy1200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllContactsCopy1200ResponseInner{}

// GetAllContactsCopy1200ResponseInner struct for GetAllContactsCopy1200ResponseInner
type GetAllContactsCopy1200ResponseInner struct {
	ContactId              *int32      `json:"contactId,omitempty"`
	Id                     *int32      `json:"id,omitempty"`
	Name                   *string     `json:"name,omitempty"`
	FirstName              *string     `json:"firstName,omitempty"`
	LastName               *string     `json:"lastName,omitempty"`
	Address1               *string     `json:"address1,omitempty"`
	Address2               interface{} `json:"address2,omitempty"`
	City                   interface{} `json:"city,omitempty"`
	State                  *string     `json:"state,omitempty"`
	Zipcode                *string     `json:"zipcode,omitempty"`
	Country                *string     `json:"country,omitempty"`
	Longitude              *float32    `json:"longitude,omitempty"`
	Latitude               *float32    `json:"latitude,omitempty"`
	PhoneNumber            *string     `json:"phoneNumber,omitempty"`
	MobileNumber           *string     `json:"mobileNumber,omitempty"`
	Email                  interface{} `json:"email,omitempty"`
	OrganizationId         interface{} `json:"organizationId,omitempty"`
	OrganizationName       interface{} `json:"organizationName,omitempty"`
	ParentOrganizationId   interface{} `json:"parentOrganizationId,omitempty"`
	ParentOrganizationName interface{} `json:"parentOrganizationName,omitempty"`
	ContactTypeIds         interface{} `json:"contactTypeIds,omitempty"`
	Types                  interface{} `json:"types,omitempty"`
	Type                   *string     `json:"type,omitempty"`
	Sandbox                interface{} `json:"sandbox,omitempty"`
	ReferralSourceID       *int32      `json:"referralSourceID,omitempty"`
	ReferralSource         *string     `json:"referralSource,omitempty"`
	RelationshipStatusID   *int32      `json:"relationshipStatusID,omitempty"`
	RelationshipStatus     *string     `json:"relationshipStatus,omitempty"`
	SalespersonId          interface{} `json:"salespersonId,omitempty"`
	SalespersonName        interface{} `json:"salespersonName,omitempty"`
	CanDelete              *bool       `json:"canDelete,omitempty"`
	CreatedAt              *string     `json:"createdAt,omitempty"`
	UpdatedAt              *string     `json:"updatedAt,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _GetAllContactsCopy1200ResponseInner GetAllContactsCopy1200ResponseInner

// NewGetAllContactsCopy1200ResponseInner instantiates a new GetAllContactsCopy1200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllContactsCopy1200ResponseInner() *GetAllContactsCopy1200ResponseInner {
	this := GetAllContactsCopy1200ResponseInner{}
	var contactId int32 = 0
	this.ContactId = &contactId
	var id int32 = 0
	this.Id = &id
	var longitude float32 = 0
	this.Longitude = &longitude
	var latitude float32 = 0
	this.Latitude = &latitude
	var referralSourceID int32 = 0
	this.ReferralSourceID = &referralSourceID
	var relationshipStatusID int32 = 0
	this.RelationshipStatusID = &relationshipStatusID
	var canDelete bool = true
	this.CanDelete = &canDelete
	return &this
}

// NewGetAllContactsCopy1200ResponseInnerWithDefaults instantiates a new GetAllContactsCopy1200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllContactsCopy1200ResponseInnerWithDefaults() *GetAllContactsCopy1200ResponseInner {
	this := GetAllContactsCopy1200ResponseInner{}
	var contactId int32 = 0
	this.ContactId = &contactId
	var id int32 = 0
	this.Id = &id
	var longitude float32 = 0
	this.Longitude = &longitude
	var latitude float32 = 0
	this.Latitude = &latitude
	var referralSourceID int32 = 0
	this.ReferralSourceID = &referralSourceID
	var relationshipStatusID int32 = 0
	this.RelationshipStatusID = &relationshipStatusID
	var canDelete bool = true
	this.CanDelete = &canDelete
	return &this
}

// GetContactId returns the ContactId field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetContactId() int32 {
	if o == nil || IsNil(o.ContactId) {
		var ret int32
		return ret
	}
	return *o.ContactId
}

// GetContactIdOk returns a tuple with the ContactId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetContactIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ContactId) {
		return nil, false
	}
	return o.ContactId, true
}

// HasContactId returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasContactId() bool {
	if o != nil && !IsNil(o.ContactId) {
		return true
	}

	return false
}

// SetContactId gets a reference to the given int32 and assigns it to the ContactId field.
func (o *GetAllContactsCopy1200ResponseInner) SetContactId(v int32) {
	o.ContactId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetAllContactsCopy1200ResponseInner) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetAllContactsCopy1200ResponseInner) SetName(v string) {
	o.Name = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *GetAllContactsCopy1200ResponseInner) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *GetAllContactsCopy1200ResponseInner) SetLastName(v string) {
	o.LastName = &v
}

// GetAddress1 returns the Address1 field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetAddress1() string {
	if o == nil || IsNil(o.Address1) {
		var ret string
		return ret
	}
	return *o.Address1
}

// GetAddress1Ok returns a tuple with the Address1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetAddress1Ok() (*string, bool) {
	if o == nil || IsNil(o.Address1) {
		return nil, false
	}
	return o.Address1, true
}

// HasAddress1 returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasAddress1() bool {
	if o != nil && !IsNil(o.Address1) {
		return true
	}

	return false
}

// SetAddress1 gets a reference to the given string and assigns it to the Address1 field.
func (o *GetAllContactsCopy1200ResponseInner) SetAddress1(v string) {
	o.Address1 = &v
}

// GetAddress2 returns the Address2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetAddress2() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Address2
}

// GetAddress2Ok returns a tuple with the Address2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetAddress2Ok() (*interface{}, bool) {
	if o == nil || IsNil(o.Address2) {
		return nil, false
	}
	return &o.Address2, true
}

// HasAddress2 returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasAddress2() bool {
	if o != nil && !IsNil(o.Address2) {
		return true
	}

	return false
}

// SetAddress2 gets a reference to the given interface{} and assigns it to the Address2 field.
func (o *GetAllContactsCopy1200ResponseInner) SetAddress2(v interface{}) {
	o.Address2 = v
}

// GetCity returns the City field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetCity() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetCityOk() (*interface{}, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return &o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given interface{} and assigns it to the City field.
func (o *GetAllContactsCopy1200ResponseInner) SetCity(v interface{}) {
	o.City = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *GetAllContactsCopy1200ResponseInner) SetState(v string) {
	o.State = &v
}

// GetZipcode returns the Zipcode field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetZipcode() string {
	if o == nil || IsNil(o.Zipcode) {
		var ret string
		return ret
	}
	return *o.Zipcode
}

// GetZipcodeOk returns a tuple with the Zipcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetZipcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Zipcode) {
		return nil, false
	}
	return o.Zipcode, true
}

// HasZipcode returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasZipcode() bool {
	if o != nil && !IsNil(o.Zipcode) {
		return true
	}

	return false
}

// SetZipcode gets a reference to the given string and assigns it to the Zipcode field.
func (o *GetAllContactsCopy1200ResponseInner) SetZipcode(v string) {
	o.Zipcode = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *GetAllContactsCopy1200ResponseInner) SetCountry(v string) {
	o.Country = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetLongitude() float32 {
	if o == nil || IsNil(o.Longitude) {
		var ret float32
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetLongitudeOk() (*float32, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float32 and assigns it to the Longitude field.
func (o *GetAllContactsCopy1200ResponseInner) SetLongitude(v float32) {
	o.Longitude = &v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetLatitude() float32 {
	if o == nil || IsNil(o.Latitude) {
		var ret float32
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetLatitudeOk() (*float32, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float32 and assigns it to the Latitude field.
func (o *GetAllContactsCopy1200ResponseInner) SetLatitude(v float32) {
	o.Latitude = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *GetAllContactsCopy1200ResponseInner) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetMobileNumber returns the MobileNumber field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetMobileNumber() string {
	if o == nil || IsNil(o.MobileNumber) {
		var ret string
		return ret
	}
	return *o.MobileNumber
}

// GetMobileNumberOk returns a tuple with the MobileNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetMobileNumberOk() (*string, bool) {
	if o == nil || IsNil(o.MobileNumber) {
		return nil, false
	}
	return o.MobileNumber, true
}

// HasMobileNumber returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasMobileNumber() bool {
	if o != nil && !IsNil(o.MobileNumber) {
		return true
	}

	return false
}

// SetMobileNumber gets a reference to the given string and assigns it to the MobileNumber field.
func (o *GetAllContactsCopy1200ResponseInner) SetMobileNumber(v string) {
	o.MobileNumber = &v
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetEmail() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetEmailOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return &o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given interface{} and assigns it to the Email field.
func (o *GetAllContactsCopy1200ResponseInner) SetEmail(v interface{}) {
	o.Email = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetOrganizationId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetOrganizationIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return &o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given interface{} and assigns it to the OrganizationId field.
func (o *GetAllContactsCopy1200ResponseInner) SetOrganizationId(v interface{}) {
	o.OrganizationId = v
}

// GetOrganizationName returns the OrganizationName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetOrganizationName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.OrganizationName
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetOrganizationNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.OrganizationName) {
		return nil, false
	}
	return &o.OrganizationName, true
}

// HasOrganizationName returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasOrganizationName() bool {
	if o != nil && !IsNil(o.OrganizationName) {
		return true
	}

	return false
}

// SetOrganizationName gets a reference to the given interface{} and assigns it to the OrganizationName field.
func (o *GetAllContactsCopy1200ResponseInner) SetOrganizationName(v interface{}) {
	o.OrganizationName = v
}

// GetParentOrganizationId returns the ParentOrganizationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetParentOrganizationId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ParentOrganizationId
}

// GetParentOrganizationIdOk returns a tuple with the ParentOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetParentOrganizationIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ParentOrganizationId) {
		return nil, false
	}
	return &o.ParentOrganizationId, true
}

// HasParentOrganizationId returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasParentOrganizationId() bool {
	if o != nil && !IsNil(o.ParentOrganizationId) {
		return true
	}

	return false
}

// SetParentOrganizationId gets a reference to the given interface{} and assigns it to the ParentOrganizationId field.
func (o *GetAllContactsCopy1200ResponseInner) SetParentOrganizationId(v interface{}) {
	o.ParentOrganizationId = v
}

// GetParentOrganizationName returns the ParentOrganizationName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetParentOrganizationName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ParentOrganizationName
}

// GetParentOrganizationNameOk returns a tuple with the ParentOrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetParentOrganizationNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ParentOrganizationName) {
		return nil, false
	}
	return &o.ParentOrganizationName, true
}

// HasParentOrganizationName returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasParentOrganizationName() bool {
	if o != nil && !IsNil(o.ParentOrganizationName) {
		return true
	}

	return false
}

// SetParentOrganizationName gets a reference to the given interface{} and assigns it to the ParentOrganizationName field.
func (o *GetAllContactsCopy1200ResponseInner) SetParentOrganizationName(v interface{}) {
	o.ParentOrganizationName = v
}

// GetContactTypeIds returns the ContactTypeIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetContactTypeIds() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ContactTypeIds
}

// GetContactTypeIdsOk returns a tuple with the ContactTypeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetContactTypeIdsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ContactTypeIds) {
		return nil, false
	}
	return &o.ContactTypeIds, true
}

// HasContactTypeIds returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasContactTypeIds() bool {
	if o != nil && !IsNil(o.ContactTypeIds) {
		return true
	}

	return false
}

// SetContactTypeIds gets a reference to the given interface{} and assigns it to the ContactTypeIds field.
func (o *GetAllContactsCopy1200ResponseInner) SetContactTypeIds(v interface{}) {
	o.ContactTypeIds = v
}

// GetTypes returns the Types field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetTypes() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Types
}

// GetTypesOk returns a tuple with the Types field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetTypesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Types) {
		return nil, false
	}
	return &o.Types, true
}

// HasTypes returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasTypes() bool {
	if o != nil && !IsNil(o.Types) {
		return true
	}

	return false
}

// SetTypes gets a reference to the given interface{} and assigns it to the Types field.
func (o *GetAllContactsCopy1200ResponseInner) SetTypes(v interface{}) {
	o.Types = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetAllContactsCopy1200ResponseInner) SetType(v string) {
	o.Type = &v
}

// GetSandbox returns the Sandbox field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetSandbox() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Sandbox
}

// GetSandboxOk returns a tuple with the Sandbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetSandboxOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Sandbox) {
		return nil, false
	}
	return &o.Sandbox, true
}

// HasSandbox returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasSandbox() bool {
	if o != nil && !IsNil(o.Sandbox) {
		return true
	}

	return false
}

// SetSandbox gets a reference to the given interface{} and assigns it to the Sandbox field.
func (o *GetAllContactsCopy1200ResponseInner) SetSandbox(v interface{}) {
	o.Sandbox = v
}

// GetReferralSourceID returns the ReferralSourceID field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetReferralSourceID() int32 {
	if o == nil || IsNil(o.ReferralSourceID) {
		var ret int32
		return ret
	}
	return *o.ReferralSourceID
}

// GetReferralSourceIDOk returns a tuple with the ReferralSourceID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetReferralSourceIDOk() (*int32, bool) {
	if o == nil || IsNil(o.ReferralSourceID) {
		return nil, false
	}
	return o.ReferralSourceID, true
}

// HasReferralSourceID returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasReferralSourceID() bool {
	if o != nil && !IsNil(o.ReferralSourceID) {
		return true
	}

	return false
}

// SetReferralSourceID gets a reference to the given int32 and assigns it to the ReferralSourceID field.
func (o *GetAllContactsCopy1200ResponseInner) SetReferralSourceID(v int32) {
	o.ReferralSourceID = &v
}

// GetReferralSource returns the ReferralSource field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetReferralSource() string {
	if o == nil || IsNil(o.ReferralSource) {
		var ret string
		return ret
	}
	return *o.ReferralSource
}

// GetReferralSourceOk returns a tuple with the ReferralSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetReferralSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ReferralSource) {
		return nil, false
	}
	return o.ReferralSource, true
}

// HasReferralSource returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasReferralSource() bool {
	if o != nil && !IsNil(o.ReferralSource) {
		return true
	}

	return false
}

// SetReferralSource gets a reference to the given string and assigns it to the ReferralSource field.
func (o *GetAllContactsCopy1200ResponseInner) SetReferralSource(v string) {
	o.ReferralSource = &v
}

// GetRelationshipStatusID returns the RelationshipStatusID field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetRelationshipStatusID() int32 {
	if o == nil || IsNil(o.RelationshipStatusID) {
		var ret int32
		return ret
	}
	return *o.RelationshipStatusID
}

// GetRelationshipStatusIDOk returns a tuple with the RelationshipStatusID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetRelationshipStatusIDOk() (*int32, bool) {
	if o == nil || IsNil(o.RelationshipStatusID) {
		return nil, false
	}
	return o.RelationshipStatusID, true
}

// HasRelationshipStatusID returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasRelationshipStatusID() bool {
	if o != nil && !IsNil(o.RelationshipStatusID) {
		return true
	}

	return false
}

// SetRelationshipStatusID gets a reference to the given int32 and assigns it to the RelationshipStatusID field.
func (o *GetAllContactsCopy1200ResponseInner) SetRelationshipStatusID(v int32) {
	o.RelationshipStatusID = &v
}

// GetRelationshipStatus returns the RelationshipStatus field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetRelationshipStatus() string {
	if o == nil || IsNil(o.RelationshipStatus) {
		var ret string
		return ret
	}
	return *o.RelationshipStatus
}

// GetRelationshipStatusOk returns a tuple with the RelationshipStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetRelationshipStatusOk() (*string, bool) {
	if o == nil || IsNil(o.RelationshipStatus) {
		return nil, false
	}
	return o.RelationshipStatus, true
}

// HasRelationshipStatus returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasRelationshipStatus() bool {
	if o != nil && !IsNil(o.RelationshipStatus) {
		return true
	}

	return false
}

// SetRelationshipStatus gets a reference to the given string and assigns it to the RelationshipStatus field.
func (o *GetAllContactsCopy1200ResponseInner) SetRelationshipStatus(v string) {
	o.RelationshipStatus = &v
}

// GetSalespersonId returns the SalespersonId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetSalespersonId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SalespersonId
}

// GetSalespersonIdOk returns a tuple with the SalespersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetSalespersonIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SalespersonId) {
		return nil, false
	}
	return &o.SalespersonId, true
}

// HasSalespersonId returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasSalespersonId() bool {
	if o != nil && !IsNil(o.SalespersonId) {
		return true
	}

	return false
}

// SetSalespersonId gets a reference to the given interface{} and assigns it to the SalespersonId field.
func (o *GetAllContactsCopy1200ResponseInner) SetSalespersonId(v interface{}) {
	o.SalespersonId = v
}

// GetSalespersonName returns the SalespersonName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAllContactsCopy1200ResponseInner) GetSalespersonName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SalespersonName
}

// GetSalespersonNameOk returns a tuple with the SalespersonName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAllContactsCopy1200ResponseInner) GetSalespersonNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SalespersonName) {
		return nil, false
	}
	return &o.SalespersonName, true
}

// HasSalespersonName returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasSalespersonName() bool {
	if o != nil && !IsNil(o.SalespersonName) {
		return true
	}

	return false
}

// SetSalespersonName gets a reference to the given interface{} and assigns it to the SalespersonName field.
func (o *GetAllContactsCopy1200ResponseInner) SetSalespersonName(v interface{}) {
	o.SalespersonName = v
}

// GetCanDelete returns the CanDelete field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetCanDelete() bool {
	if o == nil || IsNil(o.CanDelete) {
		var ret bool
		return ret
	}
	return *o.CanDelete
}

// GetCanDeleteOk returns a tuple with the CanDelete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetCanDeleteOk() (*bool, bool) {
	if o == nil || IsNil(o.CanDelete) {
		return nil, false
	}
	return o.CanDelete, true
}

// HasCanDelete returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasCanDelete() bool {
	if o != nil && !IsNil(o.CanDelete) {
		return true
	}

	return false
}

// SetCanDelete gets a reference to the given bool and assigns it to the CanDelete field.
func (o *GetAllContactsCopy1200ResponseInner) SetCanDelete(v bool) {
	o.CanDelete = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetAllContactsCopy1200ResponseInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetAllContactsCopy1200ResponseInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllContactsCopy1200ResponseInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetAllContactsCopy1200ResponseInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GetAllContactsCopy1200ResponseInner) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o GetAllContactsCopy1200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllContactsCopy1200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContactId) {
		toSerialize["contactId"] = o.ContactId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.Address1) {
		toSerialize["address1"] = o.Address1
	}
	if o.Address2 != nil {
		toSerialize["address2"] = o.Address2
	}
	if o.City != nil {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Zipcode) {
		toSerialize["zipcode"] = o.Zipcode
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if !IsNil(o.MobileNumber) {
		toSerialize["mobileNumber"] = o.MobileNumber
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.OrganizationId != nil {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if o.OrganizationName != nil {
		toSerialize["organizationName"] = o.OrganizationName
	}
	if o.ParentOrganizationId != nil {
		toSerialize["parentOrganizationId"] = o.ParentOrganizationId
	}
	if o.ParentOrganizationName != nil {
		toSerialize["parentOrganizationName"] = o.ParentOrganizationName
	}
	if o.ContactTypeIds != nil {
		toSerialize["contactTypeIds"] = o.ContactTypeIds
	}
	if o.Types != nil {
		toSerialize["types"] = o.Types
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Sandbox != nil {
		toSerialize["sandbox"] = o.Sandbox
	}
	if !IsNil(o.ReferralSourceID) {
		toSerialize["referralSourceID"] = o.ReferralSourceID
	}
	if !IsNil(o.ReferralSource) {
		toSerialize["referralSource"] = o.ReferralSource
	}
	if !IsNil(o.RelationshipStatusID) {
		toSerialize["relationshipStatusID"] = o.RelationshipStatusID
	}
	if !IsNil(o.RelationshipStatus) {
		toSerialize["relationshipStatus"] = o.RelationshipStatus
	}
	if o.SalespersonId != nil {
		toSerialize["salespersonId"] = o.SalespersonId
	}
	if o.SalespersonName != nil {
		toSerialize["salespersonName"] = o.SalespersonName
	}
	if !IsNil(o.CanDelete) {
		toSerialize["canDelete"] = o.CanDelete
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAllContactsCopy1200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	varGetAllContactsCopy1200ResponseInner := _GetAllContactsCopy1200ResponseInner{}

	err = json.Unmarshal(data, &varGetAllContactsCopy1200ResponseInner)

	if err != nil {
		return err
	}

	*o = GetAllContactsCopy1200ResponseInner(varGetAllContactsCopy1200ResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "contactId")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "address1")
		delete(additionalProperties, "address2")
		delete(additionalProperties, "city")
		delete(additionalProperties, "state")
		delete(additionalProperties, "zipcode")
		delete(additionalProperties, "country")
		delete(additionalProperties, "longitude")
		delete(additionalProperties, "latitude")
		delete(additionalProperties, "phoneNumber")
		delete(additionalProperties, "mobileNumber")
		delete(additionalProperties, "email")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "organizationName")
		delete(additionalProperties, "parentOrganizationId")
		delete(additionalProperties, "parentOrganizationName")
		delete(additionalProperties, "contactTypeIds")
		delete(additionalProperties, "types")
		delete(additionalProperties, "type")
		delete(additionalProperties, "sandbox")
		delete(additionalProperties, "referralSourceID")
		delete(additionalProperties, "referralSource")
		delete(additionalProperties, "relationshipStatusID")
		delete(additionalProperties, "relationshipStatus")
		delete(additionalProperties, "salespersonId")
		delete(additionalProperties, "salespersonName")
		delete(additionalProperties, "canDelete")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAllContactsCopy1200ResponseInner struct {
	value *GetAllContactsCopy1200ResponseInner
	isSet bool
}

func (v NullableGetAllContactsCopy1200ResponseInner) Get() *GetAllContactsCopy1200ResponseInner {
	return v.value
}

func (v *NullableGetAllContactsCopy1200ResponseInner) Set(val *GetAllContactsCopy1200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllContactsCopy1200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllContactsCopy1200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllContactsCopy1200ResponseInner(val *GetAllContactsCopy1200ResponseInner) *NullableGetAllContactsCopy1200ResponseInner {
	return &NullableGetAllContactsCopy1200ResponseInner{value: val, isSet: true}
}

func (v NullableGetAllContactsCopy1200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllContactsCopy1200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
