/*
Albi Api - v5

This Api will be responsible for overall data distribution and authorization.

API version: v5
Contact: support@albiware.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package albiwareapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NewProjectCustomerDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewProjectCustomerDto{}

// NewProjectCustomerDto struct for NewProjectCustomerDto
type NewProjectCustomerDto struct {
	Type                                   string          `json:"type"`
	ExistingContactId                      NullableInt64   `json:"existingContactId,omitempty"`
	ExistingContactIdentifier              NullableString  `json:"existingContactIdentifier,omitempty"`
	ExistingOrganizationId                 NullableInt64   `json:"existingOrganizationId,omitempty"`
	ExistingOrganizationIdentifier         NullableString  `json:"existingOrganizationIdentifier,omitempty"`
	ExistingOrganizationContactIds         []int64         `json:"existingOrganizationContactIds,omitempty"`
	ExistingOrganizationContactIdentifiers []string        `json:"existingOrganizationContactIdentifiers,omitempty"`
	OrganizationName                       NullableString  `json:"organizationName,omitempty"`
	FirstName                              NullableString  `json:"firstName,omitempty"`
	LastName                               NullableString  `json:"lastName,omitempty"`
	Email                                  NullableString  `json:"email,omitempty"`
	PhoneNumber                            NullableString  `json:"phoneNumber,omitempty"`
	UseOrganizationAddress                 *bool           `json:"useOrganizationAddress,omitempty"`
	OrganizationId                         NullableInt64   `json:"organizationId,omitempty"`
	OrganizationIdentifier                 NullableString  `json:"organizationIdentifier,omitempty"`
	ReferralSourceId                       NullableInt64   `json:"referralSourceId,omitempty"`
	ReferralSourceIdentifier               NullableString  `json:"referralSourceIdentifier,omitempty"`
	RelationshipStatusId                   NullableInt64   `json:"relationshipStatusId,omitempty"`
	RelationshipStatusIdentifier           NullableString  `json:"relationshipStatusIdentifier,omitempty"`
	ParentOrganizationId                   NullableInt64   `json:"parentOrganizationId,omitempty"`
	ParentOrganizationIdentifier           NullableString  `json:"parentOrganizationIdentifier,omitempty"`
	SalespersonId                          NullableInt64   `json:"salespersonId,omitempty"`
	SalespersonIdentifier                  NullableString  `json:"salespersonIdentifier,omitempty"`
	Address1                               NullableString  `json:"address1,omitempty"`
	Address2                               NullableString  `json:"address2,omitempty"`
	City                                   NullableString  `json:"city,omitempty"`
	State                                  NullableString  `json:"state,omitempty"`
	ZipCode                                NullableString  `json:"zipCode,omitempty"`
	Country                                NullableString  `json:"country,omitempty"`
	Latitude                               NullableFloat64 `json:"latitude,omitempty"`
	Longitude                              NullableFloat64 `json:"longitude,omitempty"`
	Sandbox                                NullableString  `json:"sandbox,omitempty"`
}

type _NewProjectCustomerDto NewProjectCustomerDto

// NewNewProjectCustomerDto instantiates a new NewProjectCustomerDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewProjectCustomerDto(type_ string) *NewProjectCustomerDto {
	this := NewProjectCustomerDto{}
	this.Type = type_
	return &this
}

// NewNewProjectCustomerDtoWithDefaults instantiates a new NewProjectCustomerDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewProjectCustomerDtoWithDefaults() *NewProjectCustomerDto {
	this := NewProjectCustomerDto{}
	return &this
}

// GetType returns the Type field value
func (o *NewProjectCustomerDto) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NewProjectCustomerDto) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NewProjectCustomerDto) SetType(v string) {
	o.Type = v
}

// GetExistingContactId returns the ExistingContactId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetExistingContactId() int64 {
	if o == nil || IsNil(o.ExistingContactId.Get()) {
		var ret int64
		return ret
	}
	return *o.ExistingContactId.Get()
}

// GetExistingContactIdOk returns a tuple with the ExistingContactId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetExistingContactIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExistingContactId.Get(), o.ExistingContactId.IsSet()
}

// HasExistingContactId returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasExistingContactId() bool {
	if o != nil && o.ExistingContactId.IsSet() {
		return true
	}

	return false
}

// SetExistingContactId gets a reference to the given NullableInt64 and assigns it to the ExistingContactId field.
func (o *NewProjectCustomerDto) SetExistingContactId(v int64) {
	o.ExistingContactId.Set(&v)
}

// SetExistingContactIdNil sets the value for ExistingContactId to be an explicit nil
func (o *NewProjectCustomerDto) SetExistingContactIdNil() {
	o.ExistingContactId.Set(nil)
}

// UnsetExistingContactId ensures that no value is present for ExistingContactId, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetExistingContactId() {
	o.ExistingContactId.Unset()
}

// GetExistingContactIdentifier returns the ExistingContactIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetExistingContactIdentifier() string {
	if o == nil || IsNil(o.ExistingContactIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.ExistingContactIdentifier.Get()
}

// GetExistingContactIdentifierOk returns a tuple with the ExistingContactIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetExistingContactIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExistingContactIdentifier.Get(), o.ExistingContactIdentifier.IsSet()
}

// HasExistingContactIdentifier returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasExistingContactIdentifier() bool {
	if o != nil && o.ExistingContactIdentifier.IsSet() {
		return true
	}

	return false
}

// SetExistingContactIdentifier gets a reference to the given NullableString and assigns it to the ExistingContactIdentifier field.
func (o *NewProjectCustomerDto) SetExistingContactIdentifier(v string) {
	o.ExistingContactIdentifier.Set(&v)
}

// SetExistingContactIdentifierNil sets the value for ExistingContactIdentifier to be an explicit nil
func (o *NewProjectCustomerDto) SetExistingContactIdentifierNil() {
	o.ExistingContactIdentifier.Set(nil)
}

// UnsetExistingContactIdentifier ensures that no value is present for ExistingContactIdentifier, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetExistingContactIdentifier() {
	o.ExistingContactIdentifier.Unset()
}

// GetExistingOrganizationId returns the ExistingOrganizationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetExistingOrganizationId() int64 {
	if o == nil || IsNil(o.ExistingOrganizationId.Get()) {
		var ret int64
		return ret
	}
	return *o.ExistingOrganizationId.Get()
}

// GetExistingOrganizationIdOk returns a tuple with the ExistingOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetExistingOrganizationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExistingOrganizationId.Get(), o.ExistingOrganizationId.IsSet()
}

// HasExistingOrganizationId returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasExistingOrganizationId() bool {
	if o != nil && o.ExistingOrganizationId.IsSet() {
		return true
	}

	return false
}

// SetExistingOrganizationId gets a reference to the given NullableInt64 and assigns it to the ExistingOrganizationId field.
func (o *NewProjectCustomerDto) SetExistingOrganizationId(v int64) {
	o.ExistingOrganizationId.Set(&v)
}

// SetExistingOrganizationIdNil sets the value for ExistingOrganizationId to be an explicit nil
func (o *NewProjectCustomerDto) SetExistingOrganizationIdNil() {
	o.ExistingOrganizationId.Set(nil)
}

// UnsetExistingOrganizationId ensures that no value is present for ExistingOrganizationId, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetExistingOrganizationId() {
	o.ExistingOrganizationId.Unset()
}

// GetExistingOrganizationIdentifier returns the ExistingOrganizationIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetExistingOrganizationIdentifier() string {
	if o == nil || IsNil(o.ExistingOrganizationIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.ExistingOrganizationIdentifier.Get()
}

// GetExistingOrganizationIdentifierOk returns a tuple with the ExistingOrganizationIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetExistingOrganizationIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExistingOrganizationIdentifier.Get(), o.ExistingOrganizationIdentifier.IsSet()
}

// HasExistingOrganizationIdentifier returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasExistingOrganizationIdentifier() bool {
	if o != nil && o.ExistingOrganizationIdentifier.IsSet() {
		return true
	}

	return false
}

// SetExistingOrganizationIdentifier gets a reference to the given NullableString and assigns it to the ExistingOrganizationIdentifier field.
func (o *NewProjectCustomerDto) SetExistingOrganizationIdentifier(v string) {
	o.ExistingOrganizationIdentifier.Set(&v)
}

// SetExistingOrganizationIdentifierNil sets the value for ExistingOrganizationIdentifier to be an explicit nil
func (o *NewProjectCustomerDto) SetExistingOrganizationIdentifierNil() {
	o.ExistingOrganizationIdentifier.Set(nil)
}

// UnsetExistingOrganizationIdentifier ensures that no value is present for ExistingOrganizationIdentifier, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetExistingOrganizationIdentifier() {
	o.ExistingOrganizationIdentifier.Unset()
}

// GetExistingOrganizationContactIds returns the ExistingOrganizationContactIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetExistingOrganizationContactIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}
	return o.ExistingOrganizationContactIds
}

// GetExistingOrganizationContactIdsOk returns a tuple with the ExistingOrganizationContactIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetExistingOrganizationContactIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.ExistingOrganizationContactIds) {
		return nil, false
	}
	return o.ExistingOrganizationContactIds, true
}

// HasExistingOrganizationContactIds returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasExistingOrganizationContactIds() bool {
	if o != nil && !IsNil(o.ExistingOrganizationContactIds) {
		return true
	}

	return false
}

// SetExistingOrganizationContactIds gets a reference to the given []int64 and assigns it to the ExistingOrganizationContactIds field.
func (o *NewProjectCustomerDto) SetExistingOrganizationContactIds(v []int64) {
	o.ExistingOrganizationContactIds = v
}

// GetExistingOrganizationContactIdentifiers returns the ExistingOrganizationContactIdentifiers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetExistingOrganizationContactIdentifiers() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ExistingOrganizationContactIdentifiers
}

// GetExistingOrganizationContactIdentifiersOk returns a tuple with the ExistingOrganizationContactIdentifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetExistingOrganizationContactIdentifiersOk() ([]string, bool) {
	if o == nil || IsNil(o.ExistingOrganizationContactIdentifiers) {
		return nil, false
	}
	return o.ExistingOrganizationContactIdentifiers, true
}

// HasExistingOrganizationContactIdentifiers returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasExistingOrganizationContactIdentifiers() bool {
	if o != nil && !IsNil(o.ExistingOrganizationContactIdentifiers) {
		return true
	}

	return false
}

// SetExistingOrganizationContactIdentifiers gets a reference to the given []string and assigns it to the ExistingOrganizationContactIdentifiers field.
func (o *NewProjectCustomerDto) SetExistingOrganizationContactIdentifiers(v []string) {
	o.ExistingOrganizationContactIdentifiers = v
}

// GetOrganizationName returns the OrganizationName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetOrganizationName() string {
	if o == nil || IsNil(o.OrganizationName.Get()) {
		var ret string
		return ret
	}
	return *o.OrganizationName.Get()
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetOrganizationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationName.Get(), o.OrganizationName.IsSet()
}

// HasOrganizationName returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasOrganizationName() bool {
	if o != nil && o.OrganizationName.IsSet() {
		return true
	}

	return false
}

// SetOrganizationName gets a reference to the given NullableString and assigns it to the OrganizationName field.
func (o *NewProjectCustomerDto) SetOrganizationName(v string) {
	o.OrganizationName.Set(&v)
}

// SetOrganizationNameNil sets the value for OrganizationName to be an explicit nil
func (o *NewProjectCustomerDto) SetOrganizationNameNil() {
	o.OrganizationName.Set(nil)
}

// UnsetOrganizationName ensures that no value is present for OrganizationName, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetOrganizationName() {
	o.OrganizationName.Unset()
}

// GetFirstName returns the FirstName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetFirstName() string {
	if o == nil || IsNil(o.FirstName.Get()) {
		var ret string
		return ret
	}
	return *o.FirstName.Get()
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstName.Get(), o.FirstName.IsSet()
}

// HasFirstName returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasFirstName() bool {
	if o != nil && o.FirstName.IsSet() {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given NullableString and assigns it to the FirstName field.
func (o *NewProjectCustomerDto) SetFirstName(v string) {
	o.FirstName.Set(&v)
}

// SetFirstNameNil sets the value for FirstName to be an explicit nil
func (o *NewProjectCustomerDto) SetFirstNameNil() {
	o.FirstName.Set(nil)
}

// UnsetFirstName ensures that no value is present for FirstName, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetFirstName() {
	o.FirstName.Unset()
}

// GetLastName returns the LastName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetLastName() string {
	if o == nil || IsNil(o.LastName.Get()) {
		var ret string
		return ret
	}
	return *o.LastName.Get()
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastName.Get(), o.LastName.IsSet()
}

// HasLastName returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasLastName() bool {
	if o != nil && o.LastName.IsSet() {
		return true
	}

	return false
}

// SetLastName gets a reference to the given NullableString and assigns it to the LastName field.
func (o *NewProjectCustomerDto) SetLastName(v string) {
	o.LastName.Set(&v)
}

// SetLastNameNil sets the value for LastName to be an explicit nil
func (o *NewProjectCustomerDto) SetLastNameNil() {
	o.LastName.Set(nil)
}

// UnsetLastName ensures that no value is present for LastName, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetLastName() {
	o.LastName.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *NewProjectCustomerDto) SetEmail(v string) {
	o.Email.Set(&v)
}

// SetEmailNil sets the value for Email to be an explicit nil
func (o *NewProjectCustomerDto) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetEmail() {
	o.Email.Unset()
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneNumber.Get()
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumber.Get(), o.PhoneNumber.IsSet()
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber.IsSet() {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given NullableString and assigns it to the PhoneNumber field.
func (o *NewProjectCustomerDto) SetPhoneNumber(v string) {
	o.PhoneNumber.Set(&v)
}

// SetPhoneNumberNil sets the value for PhoneNumber to be an explicit nil
func (o *NewProjectCustomerDto) SetPhoneNumberNil() {
	o.PhoneNumber.Set(nil)
}

// UnsetPhoneNumber ensures that no value is present for PhoneNumber, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetPhoneNumber() {
	o.PhoneNumber.Unset()
}

// GetUseOrganizationAddress returns the UseOrganizationAddress field value if set, zero value otherwise.
func (o *NewProjectCustomerDto) GetUseOrganizationAddress() bool {
	if o == nil || IsNil(o.UseOrganizationAddress) {
		var ret bool
		return ret
	}
	return *o.UseOrganizationAddress
}

// GetUseOrganizationAddressOk returns a tuple with the UseOrganizationAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewProjectCustomerDto) GetUseOrganizationAddressOk() (*bool, bool) {
	if o == nil || IsNil(o.UseOrganizationAddress) {
		return nil, false
	}
	return o.UseOrganizationAddress, true
}

// HasUseOrganizationAddress returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasUseOrganizationAddress() bool {
	if o != nil && !IsNil(o.UseOrganizationAddress) {
		return true
	}

	return false
}

// SetUseOrganizationAddress gets a reference to the given bool and assigns it to the UseOrganizationAddress field.
func (o *NewProjectCustomerDto) SetUseOrganizationAddress(v bool) {
	o.UseOrganizationAddress = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetOrganizationId() int64 {
	if o == nil || IsNil(o.OrganizationId.Get()) {
		var ret int64
		return ret
	}
	return *o.OrganizationId.Get()
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetOrganizationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationId.Get(), o.OrganizationId.IsSet()
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasOrganizationId() bool {
	if o != nil && o.OrganizationId.IsSet() {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given NullableInt64 and assigns it to the OrganizationId field.
func (o *NewProjectCustomerDto) SetOrganizationId(v int64) {
	o.OrganizationId.Set(&v)
}

// SetOrganizationIdNil sets the value for OrganizationId to be an explicit nil
func (o *NewProjectCustomerDto) SetOrganizationIdNil() {
	o.OrganizationId.Set(nil)
}

// UnsetOrganizationId ensures that no value is present for OrganizationId, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetOrganizationId() {
	o.OrganizationId.Unset()
}

// GetOrganizationIdentifier returns the OrganizationIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetOrganizationIdentifier() string {
	if o == nil || IsNil(o.OrganizationIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.OrganizationIdentifier.Get()
}

// GetOrganizationIdentifierOk returns a tuple with the OrganizationIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetOrganizationIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationIdentifier.Get(), o.OrganizationIdentifier.IsSet()
}

// HasOrganizationIdentifier returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasOrganizationIdentifier() bool {
	if o != nil && o.OrganizationIdentifier.IsSet() {
		return true
	}

	return false
}

// SetOrganizationIdentifier gets a reference to the given NullableString and assigns it to the OrganizationIdentifier field.
func (o *NewProjectCustomerDto) SetOrganizationIdentifier(v string) {
	o.OrganizationIdentifier.Set(&v)
}

// SetOrganizationIdentifierNil sets the value for OrganizationIdentifier to be an explicit nil
func (o *NewProjectCustomerDto) SetOrganizationIdentifierNil() {
	o.OrganizationIdentifier.Set(nil)
}

// UnsetOrganizationIdentifier ensures that no value is present for OrganizationIdentifier, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetOrganizationIdentifier() {
	o.OrganizationIdentifier.Unset()
}

// GetReferralSourceId returns the ReferralSourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetReferralSourceId() int64 {
	if o == nil || IsNil(o.ReferralSourceId.Get()) {
		var ret int64
		return ret
	}
	return *o.ReferralSourceId.Get()
}

// GetReferralSourceIdOk returns a tuple with the ReferralSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetReferralSourceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferralSourceId.Get(), o.ReferralSourceId.IsSet()
}

// HasReferralSourceId returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasReferralSourceId() bool {
	if o != nil && o.ReferralSourceId.IsSet() {
		return true
	}

	return false
}

// SetReferralSourceId gets a reference to the given NullableInt64 and assigns it to the ReferralSourceId field.
func (o *NewProjectCustomerDto) SetReferralSourceId(v int64) {
	o.ReferralSourceId.Set(&v)
}

// SetReferralSourceIdNil sets the value for ReferralSourceId to be an explicit nil
func (o *NewProjectCustomerDto) SetReferralSourceIdNil() {
	o.ReferralSourceId.Set(nil)
}

// UnsetReferralSourceId ensures that no value is present for ReferralSourceId, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetReferralSourceId() {
	o.ReferralSourceId.Unset()
}

// GetReferralSourceIdentifier returns the ReferralSourceIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetReferralSourceIdentifier() string {
	if o == nil || IsNil(o.ReferralSourceIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.ReferralSourceIdentifier.Get()
}

// GetReferralSourceIdentifierOk returns a tuple with the ReferralSourceIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetReferralSourceIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferralSourceIdentifier.Get(), o.ReferralSourceIdentifier.IsSet()
}

// HasReferralSourceIdentifier returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasReferralSourceIdentifier() bool {
	if o != nil && o.ReferralSourceIdentifier.IsSet() {
		return true
	}

	return false
}

// SetReferralSourceIdentifier gets a reference to the given NullableString and assigns it to the ReferralSourceIdentifier field.
func (o *NewProjectCustomerDto) SetReferralSourceIdentifier(v string) {
	o.ReferralSourceIdentifier.Set(&v)
}

// SetReferralSourceIdentifierNil sets the value for ReferralSourceIdentifier to be an explicit nil
func (o *NewProjectCustomerDto) SetReferralSourceIdentifierNil() {
	o.ReferralSourceIdentifier.Set(nil)
}

// UnsetReferralSourceIdentifier ensures that no value is present for ReferralSourceIdentifier, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetReferralSourceIdentifier() {
	o.ReferralSourceIdentifier.Unset()
}

// GetRelationshipStatusId returns the RelationshipStatusId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetRelationshipStatusId() int64 {
	if o == nil || IsNil(o.RelationshipStatusId.Get()) {
		var ret int64
		return ret
	}
	return *o.RelationshipStatusId.Get()
}

// GetRelationshipStatusIdOk returns a tuple with the RelationshipStatusId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetRelationshipStatusIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.RelationshipStatusId.Get(), o.RelationshipStatusId.IsSet()
}

// HasRelationshipStatusId returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasRelationshipStatusId() bool {
	if o != nil && o.RelationshipStatusId.IsSet() {
		return true
	}

	return false
}

// SetRelationshipStatusId gets a reference to the given NullableInt64 and assigns it to the RelationshipStatusId field.
func (o *NewProjectCustomerDto) SetRelationshipStatusId(v int64) {
	o.RelationshipStatusId.Set(&v)
}

// SetRelationshipStatusIdNil sets the value for RelationshipStatusId to be an explicit nil
func (o *NewProjectCustomerDto) SetRelationshipStatusIdNil() {
	o.RelationshipStatusId.Set(nil)
}

// UnsetRelationshipStatusId ensures that no value is present for RelationshipStatusId, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetRelationshipStatusId() {
	o.RelationshipStatusId.Unset()
}

// GetRelationshipStatusIdentifier returns the RelationshipStatusIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetRelationshipStatusIdentifier() string {
	if o == nil || IsNil(o.RelationshipStatusIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.RelationshipStatusIdentifier.Get()
}

// GetRelationshipStatusIdentifierOk returns a tuple with the RelationshipStatusIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetRelationshipStatusIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RelationshipStatusIdentifier.Get(), o.RelationshipStatusIdentifier.IsSet()
}

// HasRelationshipStatusIdentifier returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasRelationshipStatusIdentifier() bool {
	if o != nil && o.RelationshipStatusIdentifier.IsSet() {
		return true
	}

	return false
}

// SetRelationshipStatusIdentifier gets a reference to the given NullableString and assigns it to the RelationshipStatusIdentifier field.
func (o *NewProjectCustomerDto) SetRelationshipStatusIdentifier(v string) {
	o.RelationshipStatusIdentifier.Set(&v)
}

// SetRelationshipStatusIdentifierNil sets the value for RelationshipStatusIdentifier to be an explicit nil
func (o *NewProjectCustomerDto) SetRelationshipStatusIdentifierNil() {
	o.RelationshipStatusIdentifier.Set(nil)
}

// UnsetRelationshipStatusIdentifier ensures that no value is present for RelationshipStatusIdentifier, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetRelationshipStatusIdentifier() {
	o.RelationshipStatusIdentifier.Unset()
}

// GetParentOrganizationId returns the ParentOrganizationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetParentOrganizationId() int64 {
	if o == nil || IsNil(o.ParentOrganizationId.Get()) {
		var ret int64
		return ret
	}
	return *o.ParentOrganizationId.Get()
}

// GetParentOrganizationIdOk returns a tuple with the ParentOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetParentOrganizationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentOrganizationId.Get(), o.ParentOrganizationId.IsSet()
}

// HasParentOrganizationId returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasParentOrganizationId() bool {
	if o != nil && o.ParentOrganizationId.IsSet() {
		return true
	}

	return false
}

// SetParentOrganizationId gets a reference to the given NullableInt64 and assigns it to the ParentOrganizationId field.
func (o *NewProjectCustomerDto) SetParentOrganizationId(v int64) {
	o.ParentOrganizationId.Set(&v)
}

// SetParentOrganizationIdNil sets the value for ParentOrganizationId to be an explicit nil
func (o *NewProjectCustomerDto) SetParentOrganizationIdNil() {
	o.ParentOrganizationId.Set(nil)
}

// UnsetParentOrganizationId ensures that no value is present for ParentOrganizationId, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetParentOrganizationId() {
	o.ParentOrganizationId.Unset()
}

// GetParentOrganizationIdentifier returns the ParentOrganizationIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetParentOrganizationIdentifier() string {
	if o == nil || IsNil(o.ParentOrganizationIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.ParentOrganizationIdentifier.Get()
}

// GetParentOrganizationIdentifierOk returns a tuple with the ParentOrganizationIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetParentOrganizationIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentOrganizationIdentifier.Get(), o.ParentOrganizationIdentifier.IsSet()
}

// HasParentOrganizationIdentifier returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasParentOrganizationIdentifier() bool {
	if o != nil && o.ParentOrganizationIdentifier.IsSet() {
		return true
	}

	return false
}

// SetParentOrganizationIdentifier gets a reference to the given NullableString and assigns it to the ParentOrganizationIdentifier field.
func (o *NewProjectCustomerDto) SetParentOrganizationIdentifier(v string) {
	o.ParentOrganizationIdentifier.Set(&v)
}

// SetParentOrganizationIdentifierNil sets the value for ParentOrganizationIdentifier to be an explicit nil
func (o *NewProjectCustomerDto) SetParentOrganizationIdentifierNil() {
	o.ParentOrganizationIdentifier.Set(nil)
}

// UnsetParentOrganizationIdentifier ensures that no value is present for ParentOrganizationIdentifier, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetParentOrganizationIdentifier() {
	o.ParentOrganizationIdentifier.Unset()
}

// GetSalespersonId returns the SalespersonId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetSalespersonId() int64 {
	if o == nil || IsNil(o.SalespersonId.Get()) {
		var ret int64
		return ret
	}
	return *o.SalespersonId.Get()
}

// GetSalespersonIdOk returns a tuple with the SalespersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetSalespersonIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.SalespersonId.Get(), o.SalespersonId.IsSet()
}

// HasSalespersonId returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasSalespersonId() bool {
	if o != nil && o.SalespersonId.IsSet() {
		return true
	}

	return false
}

// SetSalespersonId gets a reference to the given NullableInt64 and assigns it to the SalespersonId field.
func (o *NewProjectCustomerDto) SetSalespersonId(v int64) {
	o.SalespersonId.Set(&v)
}

// SetSalespersonIdNil sets the value for SalespersonId to be an explicit nil
func (o *NewProjectCustomerDto) SetSalespersonIdNil() {
	o.SalespersonId.Set(nil)
}

// UnsetSalespersonId ensures that no value is present for SalespersonId, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetSalespersonId() {
	o.SalespersonId.Unset()
}

// GetSalespersonIdentifier returns the SalespersonIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetSalespersonIdentifier() string {
	if o == nil || IsNil(o.SalespersonIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.SalespersonIdentifier.Get()
}

// GetSalespersonIdentifierOk returns a tuple with the SalespersonIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetSalespersonIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SalespersonIdentifier.Get(), o.SalespersonIdentifier.IsSet()
}

// HasSalespersonIdentifier returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasSalespersonIdentifier() bool {
	if o != nil && o.SalespersonIdentifier.IsSet() {
		return true
	}

	return false
}

// SetSalespersonIdentifier gets a reference to the given NullableString and assigns it to the SalespersonIdentifier field.
func (o *NewProjectCustomerDto) SetSalespersonIdentifier(v string) {
	o.SalespersonIdentifier.Set(&v)
}

// SetSalespersonIdentifierNil sets the value for SalespersonIdentifier to be an explicit nil
func (o *NewProjectCustomerDto) SetSalespersonIdentifierNil() {
	o.SalespersonIdentifier.Set(nil)
}

// UnsetSalespersonIdentifier ensures that no value is present for SalespersonIdentifier, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetSalespersonIdentifier() {
	o.SalespersonIdentifier.Unset()
}

// GetAddress1 returns the Address1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetAddress1() string {
	if o == nil || IsNil(o.Address1.Get()) {
		var ret string
		return ret
	}
	return *o.Address1.Get()
}

// GetAddress1Ok returns a tuple with the Address1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetAddress1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address1.Get(), o.Address1.IsSet()
}

// HasAddress1 returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasAddress1() bool {
	if o != nil && o.Address1.IsSet() {
		return true
	}

	return false
}

// SetAddress1 gets a reference to the given NullableString and assigns it to the Address1 field.
func (o *NewProjectCustomerDto) SetAddress1(v string) {
	o.Address1.Set(&v)
}

// SetAddress1Nil sets the value for Address1 to be an explicit nil
func (o *NewProjectCustomerDto) SetAddress1Nil() {
	o.Address1.Set(nil)
}

// UnsetAddress1 ensures that no value is present for Address1, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetAddress1() {
	o.Address1.Unset()
}

// GetAddress2 returns the Address2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetAddress2() string {
	if o == nil || IsNil(o.Address2.Get()) {
		var ret string
		return ret
	}
	return *o.Address2.Get()
}

// GetAddress2Ok returns a tuple with the Address2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetAddress2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address2.Get(), o.Address2.IsSet()
}

// HasAddress2 returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasAddress2() bool {
	if o != nil && o.Address2.IsSet() {
		return true
	}

	return false
}

// SetAddress2 gets a reference to the given NullableString and assigns it to the Address2 field.
func (o *NewProjectCustomerDto) SetAddress2(v string) {
	o.Address2.Set(&v)
}

// SetAddress2Nil sets the value for Address2 to be an explicit nil
func (o *NewProjectCustomerDto) SetAddress2Nil() {
	o.Address2.Set(nil)
}

// UnsetAddress2 ensures that no value is present for Address2, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetAddress2() {
	o.Address2.Unset()
}

// GetCity returns the City field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetCity() string {
	if o == nil || IsNil(o.City.Get()) {
		var ret string
		return ret
	}
	return *o.City.Get()
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.City.Get(), o.City.IsSet()
}

// HasCity returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasCity() bool {
	if o != nil && o.City.IsSet() {
		return true
	}

	return false
}

// SetCity gets a reference to the given NullableString and assigns it to the City field.
func (o *NewProjectCustomerDto) SetCity(v string) {
	o.City.Set(&v)
}

// SetCityNil sets the value for City to be an explicit nil
func (o *NewProjectCustomerDto) SetCityNil() {
	o.City.Set(nil)
}

// UnsetCity ensures that no value is present for City, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetCity() {
	o.City.Unset()
}

// GetState returns the State field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetState() string {
	if o == nil || IsNil(o.State.Get()) {
		var ret string
		return ret
	}
	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// HasState returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasState() bool {
	if o != nil && o.State.IsSet() {
		return true
	}

	return false
}

// SetState gets a reference to the given NullableString and assigns it to the State field.
func (o *NewProjectCustomerDto) SetState(v string) {
	o.State.Set(&v)
}

// SetStateNil sets the value for State to be an explicit nil
func (o *NewProjectCustomerDto) SetStateNil() {
	o.State.Set(nil)
}

// UnsetState ensures that no value is present for State, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetState() {
	o.State.Unset()
}

// GetZipCode returns the ZipCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetZipCode() string {
	if o == nil || IsNil(o.ZipCode.Get()) {
		var ret string
		return ret
	}
	return *o.ZipCode.Get()
}

// GetZipCodeOk returns a tuple with the ZipCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetZipCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ZipCode.Get(), o.ZipCode.IsSet()
}

// HasZipCode returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasZipCode() bool {
	if o != nil && o.ZipCode.IsSet() {
		return true
	}

	return false
}

// SetZipCode gets a reference to the given NullableString and assigns it to the ZipCode field.
func (o *NewProjectCustomerDto) SetZipCode(v string) {
	o.ZipCode.Set(&v)
}

// SetZipCodeNil sets the value for ZipCode to be an explicit nil
func (o *NewProjectCustomerDto) SetZipCodeNil() {
	o.ZipCode.Set(nil)
}

// UnsetZipCode ensures that no value is present for ZipCode, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetZipCode() {
	o.ZipCode.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *NewProjectCustomerDto) SetCountry(v string) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *NewProjectCustomerDto) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetCountry() {
	o.Country.Unset()
}

// GetLatitude returns the Latitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude.Get()) {
		var ret float64
		return ret
	}
	return *o.Latitude.Get()
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Latitude.Get(), o.Latitude.IsSet()
}

// HasLatitude returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasLatitude() bool {
	if o != nil && o.Latitude.IsSet() {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given NullableFloat64 and assigns it to the Latitude field.
func (o *NewProjectCustomerDto) SetLatitude(v float64) {
	o.Latitude.Set(&v)
}

// SetLatitudeNil sets the value for Latitude to be an explicit nil
func (o *NewProjectCustomerDto) SetLatitudeNil() {
	o.Latitude.Set(nil)
}

// UnsetLatitude ensures that no value is present for Latitude, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetLatitude() {
	o.Latitude.Unset()
}

// GetLongitude returns the Longitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude.Get()) {
		var ret float64
		return ret
	}
	return *o.Longitude.Get()
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Longitude.Get(), o.Longitude.IsSet()
}

// HasLongitude returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasLongitude() bool {
	if o != nil && o.Longitude.IsSet() {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given NullableFloat64 and assigns it to the Longitude field.
func (o *NewProjectCustomerDto) SetLongitude(v float64) {
	o.Longitude.Set(&v)
}

// SetLongitudeNil sets the value for Longitude to be an explicit nil
func (o *NewProjectCustomerDto) SetLongitudeNil() {
	o.Longitude.Set(nil)
}

// UnsetLongitude ensures that no value is present for Longitude, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetLongitude() {
	o.Longitude.Unset()
}

// GetSandbox returns the Sandbox field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewProjectCustomerDto) GetSandbox() string {
	if o == nil || IsNil(o.Sandbox.Get()) {
		var ret string
		return ret
	}
	return *o.Sandbox.Get()
}

// GetSandboxOk returns a tuple with the Sandbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewProjectCustomerDto) GetSandboxOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sandbox.Get(), o.Sandbox.IsSet()
}

// HasSandbox returns a boolean if a field has been set.
func (o *NewProjectCustomerDto) HasSandbox() bool {
	if o != nil && o.Sandbox.IsSet() {
		return true
	}

	return false
}

// SetSandbox gets a reference to the given NullableString and assigns it to the Sandbox field.
func (o *NewProjectCustomerDto) SetSandbox(v string) {
	o.Sandbox.Set(&v)
}

// SetSandboxNil sets the value for Sandbox to be an explicit nil
func (o *NewProjectCustomerDto) SetSandboxNil() {
	o.Sandbox.Set(nil)
}

// UnsetSandbox ensures that no value is present for Sandbox, not even an explicit nil
func (o *NewProjectCustomerDto) UnsetSandbox() {
	o.Sandbox.Unset()
}

func (o NewProjectCustomerDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewProjectCustomerDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if o.ExistingContactId.IsSet() {
		toSerialize["existingContactId"] = o.ExistingContactId.Get()
	}
	if o.ExistingContactIdentifier.IsSet() {
		toSerialize["existingContactIdentifier"] = o.ExistingContactIdentifier.Get()
	}
	if o.ExistingOrganizationId.IsSet() {
		toSerialize["existingOrganizationId"] = o.ExistingOrganizationId.Get()
	}
	if o.ExistingOrganizationIdentifier.IsSet() {
		toSerialize["existingOrganizationIdentifier"] = o.ExistingOrganizationIdentifier.Get()
	}
	if o.ExistingOrganizationContactIds != nil {
		toSerialize["existingOrganizationContactIds"] = o.ExistingOrganizationContactIds
	}
	if o.ExistingOrganizationContactIdentifiers != nil {
		toSerialize["existingOrganizationContactIdentifiers"] = o.ExistingOrganizationContactIdentifiers
	}
	if o.OrganizationName.IsSet() {
		toSerialize["organizationName"] = o.OrganizationName.Get()
	}
	if o.FirstName.IsSet() {
		toSerialize["firstName"] = o.FirstName.Get()
	}
	if o.LastName.IsSet() {
		toSerialize["lastName"] = o.LastName.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.PhoneNumber.IsSet() {
		toSerialize["phoneNumber"] = o.PhoneNumber.Get()
	}
	if !IsNil(o.UseOrganizationAddress) {
		toSerialize["useOrganizationAddress"] = o.UseOrganizationAddress
	}
	if o.OrganizationId.IsSet() {
		toSerialize["organizationId"] = o.OrganizationId.Get()
	}
	if o.OrganizationIdentifier.IsSet() {
		toSerialize["organizationIdentifier"] = o.OrganizationIdentifier.Get()
	}
	if o.ReferralSourceId.IsSet() {
		toSerialize["referralSourceId"] = o.ReferralSourceId.Get()
	}
	if o.ReferralSourceIdentifier.IsSet() {
		toSerialize["referralSourceIdentifier"] = o.ReferralSourceIdentifier.Get()
	}
	if o.RelationshipStatusId.IsSet() {
		toSerialize["relationshipStatusId"] = o.RelationshipStatusId.Get()
	}
	if o.RelationshipStatusIdentifier.IsSet() {
		toSerialize["relationshipStatusIdentifier"] = o.RelationshipStatusIdentifier.Get()
	}
	if o.ParentOrganizationId.IsSet() {
		toSerialize["parentOrganizationId"] = o.ParentOrganizationId.Get()
	}
	if o.ParentOrganizationIdentifier.IsSet() {
		toSerialize["parentOrganizationIdentifier"] = o.ParentOrganizationIdentifier.Get()
	}
	if o.SalespersonId.IsSet() {
		toSerialize["salespersonId"] = o.SalespersonId.Get()
	}
	if o.SalespersonIdentifier.IsSet() {
		toSerialize["salespersonIdentifier"] = o.SalespersonIdentifier.Get()
	}
	if o.Address1.IsSet() {
		toSerialize["address1"] = o.Address1.Get()
	}
	if o.Address2.IsSet() {
		toSerialize["address2"] = o.Address2.Get()
	}
	if o.City.IsSet() {
		toSerialize["city"] = o.City.Get()
	}
	if o.State.IsSet() {
		toSerialize["state"] = o.State.Get()
	}
	if o.ZipCode.IsSet() {
		toSerialize["zipCode"] = o.ZipCode.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.Latitude.IsSet() {
		toSerialize["latitude"] = o.Latitude.Get()
	}
	if o.Longitude.IsSet() {
		toSerialize["longitude"] = o.Longitude.Get()
	}
	if o.Sandbox.IsSet() {
		toSerialize["sandbox"] = o.Sandbox.Get()
	}
	return toSerialize, nil
}

func (o *NewProjectCustomerDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewProjectCustomerDto := _NewProjectCustomerDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewProjectCustomerDto)

	if err != nil {
		return err
	}

	*o = NewProjectCustomerDto(varNewProjectCustomerDto)

	return err
}

type NullableNewProjectCustomerDto struct {
	value *NewProjectCustomerDto
	isSet bool
}

func (v NullableNewProjectCustomerDto) Get() *NewProjectCustomerDto {
	return v.value
}

func (v *NullableNewProjectCustomerDto) Set(val *NewProjectCustomerDto) {
	v.value = val
	v.isSet = true
}

func (v NullableNewProjectCustomerDto) IsSet() bool {
	return v.isSet
}

func (v *NullableNewProjectCustomerDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewProjectCustomerDto(val *NewProjectCustomerDto) *NullableNewProjectCustomerDto {
	return &NullableNewProjectCustomerDto{value: val, isSet: true}
}

func (v NullableNewProjectCustomerDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewProjectCustomerDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
